### ISSUE TITLE
TimeInTransit issue

### ISSUE THREAD

**Issue by foxted** [gabrielbull/php-ups-api#10]
Hi,

I am trying to get the estimated delivery times on my website using the TimeInTransit API. Everything seems to work well but I have this issue and I can't figure out why : 

`Failure (Hard): The XML document is well formed but the document is not valid`

Any idea?
Thanks!

**Comment by stefandoorn** [comment]
@foxted I assume you don't have the problem anymore. If you do, please share your code and I'm happy to help.
