### ISSUE TITLE
Unterminated entity reference in DOMDocument::createElement().

### ISSUE THREAD

**Issue by travis-bradbury** [gabrielbull/php-ups-api#103]
```
Warning: DOMDocument::createElement(): unterminated entity reference B ENTERPRISES in Ups\Entity\Address->toNode() (line 270 of /path/to/gabrielbull/ups-api/src/Entity/Address.php).
```

The offending value was "A & B ENTERPRISES" in the customer's address.
#73 appears to be a similar issue, solved using createTextNode().

It seems a little weird to me that the user entered a business name in an address field (with street information in the second line), but it looks like the same issue would have occurred if they used that same name in the CompanyName element instead.

**Comment by stefandoorn** [comment]
Interesting matter. This would potentially mean that all fields that take user input (a lot) would need to be adjusted to use `createTextNode`. I've never experienced it before, but I'm mainly dealing with customer names and no business names.

There is probably also a dirty fix: iterating over all elements before creating the XML string out of it, but that feels quite dirty to me. 

@gabrielbull Any thoughts on this?

**Comment by gabrielbull** [comment]
We could replace the `$xml->createElement` method with our own method. In an ideal world, we would wrap the whole XML creation with our own class so that we control what happens everywhere.

**Comment by Demonslay335** [comment]
Is there any update on patching this officially? We ran into the issue when a business name had an ampersand as well, being sent to `\Ups\Entity\Address::setAttentionName()` in our case. In the meantime, we will likely just have to use `htmlentities()` and the like on all inputs to this library.

**Comment by Demonslay335** [comment]
Also possibly related, I found the UPS API will totally barf if certain parameters (such as the recipient name) has multiple sequential spaces (`  `). I just added my own filtering function that strips `!\s+!`. I also ran into the UPS API not accepting ampersands at all in some fields, even when escaped with `htmlentities()`.

**Comment by travis-bradbury** [comment]
@gabrielbull do you know if this was fixed at some point, or is this closed because it's super stale?
