### ISSUE TITLE
Create a return label

### ISSUE THREAD

**Issue by sibidharan** [gabrielbull/php-ups-api#109]
How to create a return label? I tried so hard to understand, but the documentation is missing!! Can you provide an example of how to create return label?

**Comment by stefandoorn** [comment]
I'll try to write some documentation over the next days (#110). In the meanwhile, see the closed issues for some suggestions / links to other issues that might help you.

**Comment by stefandoorn** [comment]
I've added some documentation. Could you let me know this helps to solve your problem?
