### ISSUE TITLE
Failure: Missing or invalid shipper number (120100)

### ISSUE THREAD

**Issue by sibidharan** [gabrielbull/php-ups-api#111]
I have linked the ups account in Manage Accounts and I got the shipper number in hands. But where to add it in the code? And why am I getting the error

Failure: Missing or invalid shipper number (120100)

**Comment by stefandoorn** [comment]
@sibidharan Take a look at https://github.com/gabrielbull/php-ups-api#example-6. In the beginning of the example a ShipperNumber is registered to the class, this might be what you are looking for.
