### ISSUE TITLE
Failure: The requested service is invalid for the shipment origin (121100)

### ISSUE THREAD

**Issue by sibidharan** [gabrielbull/php-ups-api#113]
// To address
    $address = new \Ups\Entity\Address();
    $address->setAddressLine1('AlterKnit New York');
    $address->setAddressLine2('245 W');
    $address->setAddressLine3('29th St');
    $address->setPostalCode('10001');
    $address->setCity('New York');
    $address->setCountryCode('US');
    $address->setStateProvinceCode('NY');
    $shipTo = new \Ups\Entity\ShipTo();
    $shipTo->setAddress($address);
    $shipTo->setCompanyName('KNIT NY LLC');
    $shipTo->setAttentionName('AlterKnit New York');
    $shipTo->setEmailAddress('request@alterknitnewyork.com'); 
    $shipTo->setPhoneNumber('2124736363');
    $shipment->setShipTo($shipTo);

    // From address
   
    $address = new \Ups\Entity\Address();
    $address->setAddressLine1('CHRIS NISWANDEE, SMALLSYS INC');
    $address->setAddressLine2('795 E DRAGRAM');
    $address->setPostalCode('85705');
    $address->setCity('TUCSON');
    $address->setCountryCode('US');
    $address->setStateProvinceCode('AZ');
    $shipFrom = new \Ups\Entity\ShipFrom();
    $shipFrom->setAddress($address);
    $shipFrom->setName('Joseph Daniel');
    $shipFrom->setAttentionName($shipFrom->getName());
    $shipFrom->setCompanyName($shipFrom->getName());
    $shipFrom->setEmailAddress('sibi.nandhu@gmail.com');
    $shipFrom->setPhoneNumber('8903444595');
    $shipment->setShipFrom($shipFrom);

I have no idea where I am doing a mistake. I am getting Failure: The requested service is invalid for the shipment origin (121100). Please help.

**Comment by stefandoorn** [comment]
Which API are you using and where are you setting the service type?

**Comment by sibidharan** [comment]
Shipping API. I am trying to create a return label.

```
<?php
require('vendor/autoload.php');

$accessKey = "*************";
$userId = "*********";
$password = "****************";
$return = true;

 $shipment = new Ups\Entity\Shipment;

    // Set shipper
    $shipper = $shipment->getShipper();
    $shipper->setShipperNumber("E17W09");
    $shipper->setName("AlterKnit New York");
    $shipper->setAttentionName("AlterKnit New York");
    $shipperAddress = $shipper->getAddress();
    $shipperAddress->setAddressLine1('AlterKnit New York');
    $shipperAddress->setAddressLine2('245 W');
    $shipperAddress->setAddressLine3('29th St');
    $shipperAddress->setPostalCode('10001');
    $shipperAddress->setCity('NEW YORK');
    $shipperAddress->setCountryCode('US');
    $shipperAddress->setStateProvinceCode('NY');
    $shipper->setAddress($shipperAddress);
    $shipper->setEmailAddress('request@alterknitnewyork.com'); 
    $shipper->setPhoneNumber('2124736363');
    $shipment->setShipper($shipper);

    // To address
    $address = new \Ups\Entity\Address();
    $address->setAddressLine1('AlterKnit New York');
    $address->setAddressLine2('245 W');
    $address->setAddressLine3('29th St');
    $address->setPostalCode('10001');
    $address->setCity('New York');
    $address->setCountryCode('US');
    $address->setStateProvinceCode('NY');
    $shipTo = new \Ups\Entity\ShipTo();
    $shipTo->setAddress($address);
    $shipTo->setCompanyName('KNIT NY LLC');
    $shipTo->setAttentionName('AlterKnit New York');
    $shipTo->setEmailAddress('request@alterknitnewyork.com'); 
    $shipTo->setPhoneNumber('2124736363');
    $shipment->setShipTo($shipTo);

    // From address
   
    $address = new \Ups\Entity\Address();
    $address->setAddressLine1('CHRIS NISWANDEE, SMALLSYS INC');
    $address->setAddressLine2('795 E DRAGRAM');
    $address->setPostalCode('85705');
    $address->setCity('TUCSON');
    $address->setCountryCode('US');
    $address->setStateProvinceCode('AZ');
    $shipFrom = new \Ups\Entity\ShipFrom();
    $shipFrom->setAddress($address);
    $shipFrom->setName('Joseph Daniel');
    $shipFrom->setAttentionName($shipFrom->getName());
    $shipFrom->setCompanyName($shipFrom->getName());
    $shipFrom->setEmailAddress('sibi.nandhu@gmail.com');
    $shipFrom->setPhoneNumber('8903444595');
    $shipment->setShipFrom($shipFrom);

    // // Sold to
    // $address = new \Ups\Entity\Address();
    // $address->setAddressLine1('350 5th Avenue');
    // $address->setPostalCode('10118');
    // $address->setCity('New York');
    // $address->setCountryCode('US');
    // $address->setStateProvinceCode('NY');
    // $soldTo = new \Ups\Entity\SoldTo;
    // $soldTo->setAddress($address);
    // $soldTo->setAttentionName('Joseph Daniel');
    // $soldTo->setCompanyName($soldTo->getAttentionName());
    // $soldTo->setEmailAddress('sibi.nandhu@gmail.com');
    // $soldTo->setPhoneNumber('8903444595');
    // $shipment->setSoldTo($soldTo);

    // Set service
    $service = new \Ups\Entity\Service;
    $service->setCode(\Ups\Entity\Service::S_STANDARD);
    $service->setDescription($service->getName());
    $shipment->setService($service);

    // Mark as a return (if return)
    if ($return) {
        $returnService = new \Ups\Entity\ReturnService;
        $returnService->setCode(\Ups\Entity\ReturnService::PRINT_RETURN_LABEL_PRL);
        $shipment->setReturnService($returnService);
    }

    // Set description
    $shipment->setDescription('Test');

    // Add Package
    $package = new \Ups\Entity\Package();
    $package->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
    $package->getPackageWeight()->setWeight(1);
    $unit = new \Ups\Entity\UnitOfMeasurement;
    $unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_KGS);
    $package->getPackageWeight()->setUnitOfMeasurement($unit);

    // Set dimensions
    $dimensions = new \Ups\Entity\Dimensions();
    $dimensions->setHeight(1);
    $dimensions->setWidth(1);
    $dimensions->setLength(1);
    $unit = new \Ups\Entity\UnitOfMeasurement;
    $unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_CM);
    $dimensions->setUnitOfMeasurement($unit);
    $package->setDimensions($dimensions);

    // Add descriptions because it is a package
    $package->setDescription('Test');

    // Add this package
    $shipment->addPackage($package);

    // Set Reference Number
    // $referenceNumber = new \Ups\Entity\ReferenceNumber;
    // if ($return) {
    //     $referenceNumber->setCode(\Ups\Entity\ReferenceNumber::CODE_RETURN_AUTHORIZATION_NUMBER);
    //     $referenceNumber->setValue("12345678");
    // } else {
    //     $referenceNumber->setCode(\Ups\Entity\ReferenceNumber::CODE_INVOICE_NUMBER);
    //     $referenceNumber->setValue("98765432");
    // }
    // $shipment->setReferenceNumber($referenceNumber);

    // Set payment information
    $shipment->setPaymentInformation(new \Ups\Entity\PaymentInformation('prepaid', (object)array('AccountNumber' => 'E17W09')));

    // Ask for negotiated rates (optional)
    // $rateInformation = new \Ups\Entity\RateInformation;
    // $rateInformation->setNegotiatedRatesIndicator(1);
    // $shipment->setRateInformation($rateInformation);

    // Get shipment info
    try {
        $api = new Ups\Shipping($accessKey, $userId, $password); 

        $confirm = $api->confirm(\Ups\Shipping::REQ_VALIDATE, $shipment);
        echo "<pre>";var_dump($confirm, true);echo "</pre>"; // Confirm holds the digest you need to accept the result

        if ($confirm) {
            $accept = $api->accept($confirm->ShipmentDigest);
            echo "<pre>";var_dump($accept, true);echo "</pre>"; // Accept holds the label and additional information
        }
    } catch (\Exception $e) {
        echo "<pre>";var_dump($e, true);echo "</pre>";
    }
```

**Comment by stefandoorn** [comment]
Looks ok, but maybe the STANDARD service is not allowed from that origin. It's an error UPS is generating, not this package. I don't see weird things actually, but it might just be the information you are providing. Could you test with some other services and without return? Will help you to find out what is causing the error.

**Comment by sibidharan** [comment]
@stefandoorn All I need is to create a return label.. I have no need for other services..!!

**Comment by stefandoorn** [comment]
Sure, but I'm trying to help you. I have no clue where the error is besides UPS telling that the service is not available from that origin location. So you need to try to adjust some things to find out when things are allowed. Else I also can't help you.

**Comment by sibidharan** [comment]
@stefandoorn Sure, I am trying. 

I changed the service from STANDARD to S_GROUND.. WHich produced the error "Failure: This measurement system is not valid for the selected country. (121057)"

But when I changed it to TT_S_US_GROUND,

Notice: Undefined index: GND in /Users/sibidharan/websites/ups/vendor/gabrielbull/ups-api/src/Entity/Service.php on line 153 with error Failure: Missing or invalid service code (120500)

**Comment by stefandoorn** [comment]
And what about saver? And try to disable $return. It might be also a setting on your account, so might be worth trying.

**Comment by sibidharan** [comment]
@stefandoorn I set $return=false, and I got Failure: This measurement system is not valid for the selected country. (121057)"

**Comment by stefandoorn** [comment]
Ah ja. US doesn't allow CM and KG probably. You have to change things to inches etc.

**Comment by sibidharan** [comment]
@stefandoorn Failure: A shipment cannot have a KGS/IN or LBS/CM or OZS/CM as its unit of measurements (120548) ?? It sucks :(

**Comment by sibidharan** [comment]
@stefandoorn 

```
// Add Package
    $package = new \Ups\Entity\Package();
    $package->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
    $package->getPackageWeight()->setWeight(1);
    $unit = new \Ups\Entity\UnitOfMeasurement;
    $unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_KGS);
    $package->getPackageWeight()->setUnitOfMeasurement($unit);

    // Set dimensions
    $dimensions = new \Ups\Entity\Dimensions();
    $dimensions->setHeight(1);
    $dimensions->setWidth(1);
    $dimensions->setLength(1);
    $unit = new \Ups\Entity\UnitOfMeasurement;
    $unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_IN);
    $dimensions->setUnitOfMeasurement($unit);
    $package->setDimensions($dimensions);
```

**Comment by stefandoorn** [comment]
Yes, it's on kilograms. Shouldn't that be pounds?

**Comment by sibidharan** [comment]
@sblondeau Yea man it seem to work.. Please hold I am checking further :)

**Comment by sibidharan** [comment]
@stefandoorn It is working man!! Thanks a lott :) 👍

**Comment by stefandoorn** [comment]
Great! :)

**Comment by shivaniClassic** [comment]
Hi @sibidharan  

I tried your code as mentioned but I am unable to get reference number for shipping label. Please help!

    $shipment = new \Ups\Entity\Shipment;

		// Set shipper
		$shipper = $shipment->getShipper();
		$shipper->setShipperNumber("078FF1");
		$shipper->setName("Cardknox");
		$shipper->setAttentionName("Cardknox");
		$shipperAddress = $shipper->getAddress();
		$shipperAddress->setAddressLine1('895 Towbin Ave');
		$shipperAddress->setAddressLine2('Suite A');
		$shipperAddress->setPostalCode('08701');
		$shipperAddress->setCity('Lakewood');
		$shipperAddress->setCountryCode('US');
		$shipperAddress->setStateProvinceCode('NJ');
		$shipper->setAddress($shipperAddress);
		$shipper->setEmailAddress('ah@g.com'); 
		$shipper->setPhoneNumber('2124736363');
		$shipment->setShipper($shipper);

		// To address
		$address = new \Ups\Entity\Address();
		$address->setAddressLine1('AlterKnit New York');
		$address->setAddressLine2('245 W');
		$address->setAddressLine3('29th St');
		$address->setPostalCode('10001');
		$address->setCity('New York');
		$address->setCountryCode('US');
		$address->setStateProvinceCode('NY');
		$shipTo = new \Ups\Entity\ShipTo();
		$shipTo->setAddress($address);
		$shipTo->setCompanyName('KNIT NY LLC');
		$shipTo->setAttentionName('AlterKnit New York');
		$shipTo->setEmailAddress('request@alterknitnewyork.com'); 
		$shipTo->setPhoneNumber('2124736363');
		$shipment->setShipTo($shipTo);

		// From address

		$address = new \Ups\Entity\Address();
		$address->setAddressLine1('CHRIS NISWANDEE, SMALLSYS INC');
		$address->setAddressLine2('795 E DRAGRAM');
		$address->setPostalCode('85705');
		$address->setCity('TUCSON');
		$address->setCountryCode('US');
		$address->setStateProvinceCode('AZ');
		$shipFrom = new \Ups\Entity\ShipFrom();
		$shipFrom->setAddress($address);
		$shipFrom->setName('Joseph Daniel');
		$shipFrom->setAttentionName($shipFrom->getName());
		$shipFrom->setCompanyName($shipFrom->getName());
		$shipFrom->setEmailAddress('ad@g.com');
		$shipFrom->setPhoneNumber('2124736363');
		$shipment->setShipFrom($shipFrom);

		// // Sold to
		$address = new \Ups\Entity\Address();
		$address->setAddressLine1('350 5th Avenue');
		$address->setPostalCode('10118');
		$address->setCity('New York');
		$address->setCountryCode('US');
		$address->setStateProvinceCode('NY');
		$soldTo = new \Ups\Entity\SoldTo;
		$soldTo->setAddress($address);
		$soldTo->setAttentionName('Joseph Daniel');
		$soldTo->setCompanyName($soldTo->getAttentionName());
		$soldTo->setEmailAddress('dfd@g.com');
		$soldTo->setPhoneNumber('2124736363');
		$shipment->setSoldTo($soldTo);

		// Set service
		$service = new \Ups\Entity\Service;
		$service->setCode("03");
		$service->setDescription($service->getName());
		$shipment->setService($service);

		// Mark as a return (if return)
		if ($return) {
			$returnService = new \Ups\Entity\ReturnService;
			$returnService->setCode(\Ups\Entity\ReturnService::PRINT_RETURN_LABEL_PRL);
			$shipment->setReturnService($returnService);
		}
      
		// Set description
		$shipment->setDescription('jkl');

		// Add Package
		$package = new \Ups\Entity\Package();
		$package->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
		$package->getPackageWeight()->setWeight(10);
		
		$unit = new \Ups\Entity\UnitOfMeasurement;
		$unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_LBS);
		$package->getPackageWeight()->setUnitOfMeasurement($unit);

		// Set dimensions
		$dimensions = new \Ups\Entity\Dimensions();
		$dimensions->setHeight('10');
		$dimensions->setWidth('10');
		$dimensions->setLength('10');
		$unit = new \Ups\Entity\UnitOfMeasurement;
		$unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_IN);
		$dimensions->setUnitOfMeasurement($unit);
		$package->setDimensions($dimensions); 

		// Add descriptions because it is a package
		$package->setDescription('test');
		$referenceNumber = new \Ups\Entity\ReferenceNumber;
		//$referenceNumber->setCode(\Ups\Entity\ReferenceNumber::CODE_INVOICE_NUMBER);
	    $referenceNumber->setValue("54987");
		$package->setReferenceNumber($referenceNumber);

		// Add this package
		$shipment->addPackage($package);
        
		    // Set Reference Number
			//$referenceNumber = new \Ups\Entity\ReferenceNumber;
			/* if ($return) {
				$referenceNumber->setCode(\Ups\Entity\ReferenceNumber::CODE_RETURN_AUTHORIZATION_NUMBER);
				$referenceNumber->setValue('123456');
			} else {
				$referenceNumber->setCode(\Ups\Entity\ReferenceNumber::CODE_INVOICE_NUMBER);
				$referenceNumber->setValue($order_id);
			} */
			//$shipment->setReferenceNumber($referenceNumber);
		// $shipment->getPackages()[0]->setReferenceNumber($referenceNumber);
		 
		 $shipment->getPackages()[0]->setReferenceNumber($referenceNumber);
         // Set payment information
		$shipment->setPaymentInformation(new \Ups\Entity\PaymentInformation('prepaid', (object)array('AccountNumber' => '078FF1')));

		// Ask for negotiated rates (optional)
		// $rateInformation = new \Ups\Entity\RateInformation;
		// $rateInformation->setNegotiatedRatesIndicator(1);
		// $shipment->setRateInformation($rateInformation);

		// Get shipment info
		
		try {
			$api = new \Ups\Shipping("******", "*****","******"); 
			$confirm = $api->confirm('nonvalidate', $shipment);
			//echo "ress".'<br>'.$confirm;
			echo "<pre>";var_dump($confirm, true);echo "</pre>"; // Confirm holds the digest you need to accept the result
           
			if ($confirm) {
				
				$accept = $api->accept($confirm->ShipmentDigest);
				//echo "<pre>";var_dump($accept, true);echo "</pre>";die;
				$tracking_number = $accept->PackageResults->TrackingNumber;
			    $imageformat = $accept->PackageResults->LabelImage->LabelImageFormat->Code;
					
				$base64image = $accept->PackageResults->LabelImage->GraphicImage;
				$image = base64_decode($base64image);
				if($image){
					$root_path=public_path();
					$destination=$root_path."/doc/shipping-labels/Agent-Shipping.pdf";
					$html ='<!DOCTYPE html>
					<html>
					<head>
					<meta charset="utf-8">
					<style>body{font-size: 16px;color: black;}</style>
					<title>Agent</title>
					</head>
					<body>
					<h2>Dear Tesr</h2>
					<img src="data:image/gif;base64,'. $base64image . '" />
					</body>
					</html>';
					// reference the Dompdf namespace
					$dompdf = new Dompdf();
					$dompdf->loadHtml($html);
					// (Optional) Setup the paper size and orientation
					$dompdf->setPaper('A4', 'portrait');
					// Render the HTML as PDF
					$dompdf->render();
					$pdf_gen = $dompdf->output();
					
					//Save Pdf on server
					if(file_put_contents($destination, $pdf_gen)){
					echo 1;
					}else{
					echo 0;
					}
				}else{
					echo 0;
				}
				exit;		
				echo "<pre>";var_dump($accept, true);echo "</pre>"; // Accept holds the label and additional information
			}
		} catch (\Exception $e) {
			echo "error".$e;die;
			
		}

where I am wrong? Please correct me.  I make some modification but unable to achieve that. Only getting Shipping label with tracking number.
