### ISSUE TITLE
How to know if it is in production or integration mode?

### ISSUE THREAD

**Issue by sibidharan** [gabrielbull/php-ups-api#114]
UPS is giving API access in 2 modes: Production and Integration (Testing) modes. There is no option here to decide if I am using it in which mode. 

I am using this to create a return label. API is working good, no issues with that. All I need to know is this. How to switch from/to Production/Integration.

**Comment by stefandoorn** [comment]
Every API class has an $useIntegration parameter, defaulting to `false`. If you set it to `true`, you will be using the Integration API. By default it is using the Production API.

````
    public function __construct($accessKey = null, $userId = null, $password = null, $useIntegration = false, RequestInterface $request = null, LoggerInterface $logger = null)
````
