### ISSUE TITLE
How to set ShipmentServiceOptions for email delivery

### ISSUE THREAD

**Issue by cdtweb** [gabrielbull/php-ups-api#116]
First off, thank you very much for this project. It has been hugely helpful.

I'm wondering how I can achieve adding `<ShipmentServiceOptions/>` to the request XML?

Per UPS, the following XML needs to be added to the request in addition to setting the returnService code to 8 (ReturnService::ELECTRONIC_RETURN_LABEL_ERL):

```
   <ShipmentServiceOptions>

     <LabelDelivery>

       <LabelLinksIndicator/>

       <EMail>

         <EMailAddress>emailaddress@email.com</EMailAddress>

         <FromEMailAddress>emailaddress@email.com</FromEMailAddress>

         <FromName>From Name</FromName>

         <Memo/>

         <Subject>Subject</Subject>

       </EMail>

     </LabelDelivery>

   </ShipmentServiceOptions>
```

There is a `\UPS\Entity\ShipmentServiceOptions` class, but it doesn't appear that I can do what I'm looking for without modifying the class. 

Do you have any suggestions? Thanks in advance for any help you can provide.

**Comment by stefandoorn** [comment]
Hi @cdtweb,

It might be you have some use cases we haven't tackled in this library yet. I see the 'LabelLinksIndicator' is available but not complete, but the underlying 'Email' class is not available yet. The ShipmentServiceOptions doesn't seem to be compatible with 'LabelLinksIndicator' either.

Anyway, we are open to Pull Requests that do make sure the library will support these features from that point. Would you be able to make the adjustments (there are plenty of examples in the Entity folder) and submit a PR?

**Comment by cdtweb** [comment]
If I have some spare time in the near future I will give this a go. Thanks.
