### ISSUE TITLE
PickupDateRange

### ISSUE THREAD

**Issue by palomino5** [gabrielbull/php-ups-api#120]
Hi,
Thank you very much for this project!! :+1: 

I've seen in your code that you have created an PickupDateRange class.
Is there any way to use it you choose a pickup date for a Shipment?

Thanks and regards

**Comment by stefandoorn** [comment]
Actually I don't know what the usage for this class is, as I myself haven't used it yet. I see @sebvergnes introduced it, maybe he can help you out with some instructions. Else of course the UPS documentation tells you how and what to use it for. I suspect it to be to let UPS know it's a variable pick-up, but I'm not 100% sure.
