### ISSUE TITLE
I'm having trouble generating C.O.D labels

### ISSUE THREAD

**Issue by TheRealBobaFett** [gabrielbull/php-ups-api#121]
The Ups api documentation is very confusing. But looking at the COD class it looks like there are three fields that need to be defined: ` 
/**
     * @param mixed $CODCode
     * @return COD
     */
    public function setCODCode($CODCode)
    {
              $this->CODCode = $CODCode;
             return $this;
    }

  /**
     * @param mixed $CODFundsCode
     * @return COD
     */   

  public function setCODFundsCode($CODFundsCode)
    {
             $this->CODFundsCode = $CODFundsCode;
             return $this;
    }
/**
     * @param mixed $CODAmount
     * @return COD
     */
    public function setCODAmount($CODAmount)
    {
             $this->CODAmount = $CODAmount;
             return $this;
    }
`
The one I'm having trouble with is 'CODCode', I can't find any documentation anywhere that explains what this field is and what the valid value options are... any insight/help would be much appreciated. 
Thanks!!!

**Comment by stefandoorn** [comment]
@TheRealBobaFett Can you share the results / solution?

**Comment by TheRealBobaFett** [comment]
Yes, of course, sorry... From my correspondence with UPS tech support: The only valid CODCode for the XML Shipping is '3' for Tagless COD.
