### ISSUE TITLE
Will this repositery get and update if we api is updated?

### ISSUE THREAD

**Issue by parthustad** [gabrielbull/php-ups-api#124]
Will this repositery get and update if we api is updated?

**Comment by gabrielbull** [comment]
What is "we" api?

**Comment by parthustad** [comment]
Will this repositery updated if api is updated?

**Comment by gabrielbull** [comment]
Yes it will, it is maintained by a community of [27 amazing contributors](https://github.com/gabrielbull/php-ups-api/graphs/contributors). Have fun using it!

**Comment by parthustad** [comment]
For Address Validation you have given below code

$address = new \Ups\Entity\Address();
$address->setStateProvinceCode('NY');
$address->setCity('New York');
$address->setCountryCode('US');
$address->setPostalCode('10000');

$av = new \Ups\SimpleAddressValidation($accessKey, $userId, $password);
try {
 $response = $av->validate($address);
 var_dump($response);
} catch (Exception $e) {
 var_dump($e);
}


How to use it?
in which file i have to put this code?
and which files should i add in require_once ?

**Comment by gabrielbull** [comment]
You need to use composer to install the library, here's how to get started using composer: https://getcomposer.org/doc/00-intro.md

Once the library is installed using composer, you can include the code in any PHP file like so:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php'; // path to autoload.php generate by the composer install

$address = new \Ups\Entity\Address();
$address->setStateProvinceCode('NY');
$address->setCity('New York');
$address->setCountryCode('US');
$address->setPostalCode('10000');

$av = new \Ups\SimpleAddressValidation($accessKey, $userId, $password);
try {
    $response = $av->validate($address);
    var_dump($response);
} catch (Exception $e) {
     var_dump($e);
}
```

**Comment by gabrielbull** [comment]
Edited example above to make it clearer

**Comment by parthustad** [comment]
but what if i want to use it on server?

**Comment by gabrielbull** [comment]
There is nothing stopping you from using it on a server.

**Comment by parthustad** [comment]
object(Ups\Exception\RequestException)#32 (7) { ["message":protected]=> string(143) "Failure: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(62) "C:\xampp\htdocs\ups\vendor\gabrielbull\ups-api\src\Request.php" ["line":protected]=> int(156) ["trace":"Exception":private]=> array(2) { [0]=> array(6) { ["file"]=> string(78) "C:\xampp\htdocs\ups\vendor\gabrielbull\ups-api\src\SimpleAddressValidation.php" ["line"]=> int(77) ["function"]=> string(7) "request" ["class"]=> string(11) "Ups\Request" ["type"]=> string(2) "->" ["args"]=> array(3) { [0]=> string(192) " AD18B89593298A0E soowop Test@123 " [1]=> string(351) " AV
NY New York US 10000
" [2]=> string(42) "https://onlinetools.ups.com/ups.app/xml/AV" } } [1]=> array(6) { ["file"]=> string(28) "C:\xampp\htdocs\ups\test.php" ["line"]=> int(15) ["function"]=> string(8) "validate" ["class"]=> string(27) "Ups\SimpleAddressValidation" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> object(Ups\Entity\Address)#3 (47) { ["AddressLine1"]=> NULL ["AddressLine2"]=> NULL ["AddressLine3"]=> NULL ["City"]=> string(8) "New York" ["StateProvinceCode"]=> string(2) "NY" ["PostalCode"]=> string(5) "10000" ["CountryCode"]=> string(2) "US" ["PoliticalDivision1"]=> NULL ["PoliticalDivision2"]=> NULL ["PoliticalDivision3"]=> NULL ["PostcodePrimaryLow"]=> NULL ["PostcodePrimaryHigh"]=> NULL ["PostcodeExtendedLow"]=> NULL ["ResidentialAddressIndicator"]=> NULL ["ConsigneeName"]=> NULL ["StreetNumberLow"]=> NULL ["StreetPrefix"]=> NULL ["PostcodeextendedLow"]=> NULL ["StreetName"]=> NULL ["StreetType"]=> NULL ["StreetSuffix"]=> NULL ["BuildingName"]=> NULL ["AttentionName"]=> NULL ["AddressExtendedInformation"]=> array(0) { } ["addressLine1":"Ups\Entity\Address":private]=> NULL ["addressLine2":"Ups\Entity\Address":private]=> NULL ["addressLine3":"Ups\Entity\Address":private]=> NULL ["city":"Ups\Entity\Address":private]=> string(8) "New York" ["stateProvinceCode":"Ups\Entity\Address":private]=> string(2) "NY" ["postalCode":"Ups\Entity\Address":private]=> string(5) "10000" ["countryCode":"Ups\Entity\Address":private]=> string(2) "US" ["politicalDivision1":"Ups\Entity\Address":private]=> NULL ["politicalDivision2":"Ups\Entity\Address":private]=> NULL ["politicalDivision3":"Ups\Entity\Address":private]=> NULL ["postcodePrimaryLow":"Ups\Entity\Address":private]=> NULL ["postcodePrimaryHigh":"Ups\Entity\Address":private]=> NULL ["postcodeExtendedLow":"Ups\Entity\Address":private]=> NULL ["residentialAddressIndicator":"Ups\Entity\Address":private]=> NULL ["consigneeName":"Ups\Entity\Address":private]=> NULL ["streetNumberLow":"Ups\Entity\Address":private]=> NULL ["streetPrefix":"Ups\Entity\Address":private]=> NULL ["streetName":"Ups\Entity\Address":private]=> NULL ["streetType":"Ups\Entity\Address":private]=> NULL ["streetSuffix":"Ups\Entity\Address":private]=> NULL ["buildingName":"Ups\Entity\Address":private]=> NULL ["attentionName":"Ups\Entity\Address":private]=> NULL ["addressExtendedInformation":"Ups\Entity\Address":private]=> array(0) { } } } } } ["previous":"Exception":private]=> NULL }


getting error

**Comment by gabrielbull** [comment]
You need to install CURL with SSL, here's how: http://stackoverflow.com/questions/9507353/how-do-i-install-set-up-and-use-curl-on-a-windows
