### ISSUE TITLE
Address Validation

### ISSUE THREAD

**Issue by parthustad** [gabrielbull/php-ups-api#125]
For Address Validation you have given below code

$address = new \Ups\Entity\Address();
$address->setStateProvinceCode('NY');
$address->setCity('New York');
$address->setCountryCode('US');
$address->setPostalCode('10000');

$av = new \Ups\SimpleAddressValidation($accessKey, $userId, $password);
try {
$response = $av->validate($address);
var_dump($response);
} catch (Exception $e) {
var_dump($e);
}

How to use it?
in which file i have to put this code?
and which files should i add in require_once ?

**Comment by gabrielbull** [comment]
See response in #124 here: https://github.com/gabrielbull/php-ups-api/issues/124#issuecomment-255926835
