### ISSUE TITLE
How to use shipping example in sandbox mode?

### ISSUE THREAD

**Issue by parthustad** [gabrielbull/php-ups-api#127]
How to use shipping example in sandbox mode?

**Comment by parthustad** [comment]
https://onlinetools.ups.com/ups.app/xml/ShipConfirm

is this url for production mode or test mode?
i want to use api in test mode
can you please let me know where can i change?

**Comment by stefandoorn** [comment]
Every class allows you to set a $useIntegration flag false/true on creating an object of it. You will find it if you take a look at the Shipping class constructor. Keep it at false and you will hit the integration server of UPS, setting it to true will connect to the production environment. The URL above is the production environment.

**Comment by cottton** [comment]
> Keep it at false and you will hit the integration server of UPS, setting it to true will connect to the production environment. The URL above is the production environment.

The other way around, isnt it?

    $useIntegration = true; // test servers
    if ($this->/*you method to check environment*/isProduction()) {
        $useIntegration = false; // production servers
    }
    $shipping = new \Ups\Shipping($accessKey, $userId, $password, $useIntegration);

**Comment by nomlas1** [comment]
Hello - I am doing essentially exactly what is described here, and yet I seem to be getting responses from the production environment. I can't see why that would be.  Any suggestions would be much appreciated!

**Comment by nomlas1** [comment]
I'm still not sure why, but this does not work (I get the production URL):

$useIntegration = true;
$api = new Ups\Shipping($accessKey, $userId, $password, $useIntegration);

If however I add:

if($useIntegration){
      $api->useIntegration=true;
}

Then I am able to get the sandbox URL. Perhaps this will help someone else.  And perhaps someone can explain why the first case doesn't work.
