### ISSUE TITLE
I am getting error in shipping example

### ISSUE THREAD

**Issue by parthustad** [gabrielbull/php-ups-api#129]
object(Ups\Exception\InvalidResponseException)#43 (7) {
  ["message":protected]=>
  string(62) "Failure: Missing or invalid shipper StateProvinceCode (120106)"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>

**Comment by gabrielbull** [comment]
> Failure: Missing or invalid shipper StateProvinceCode

What State code are you providing?

**Comment by parthustad** [comment]
$address->setStateProvinceCode('BC');

BC = british columbia

**Comment by gabrielbull** [comment]
As the error mention, this is for the shipper. Do you use BC for both shipper and shipto? 
`120106 Hard Missing/Invalid Shipper StateProvinceCode`

**Comment by parthustad** [comment]
YES

**Comment by parthustad** [comment]
STATE IS SAME FOR BOTH

**Comment by gabrielbull** [comment]
Can you share your code here?

**Comment by parthustad** [comment]
$shipment = new Ups\Entity\Shipment;

    // Set shipper
    $shipper = $shipment->getShipper();
    $shipper->setShipperNumber('123456');
    $shipper->setName('Parth Shah');
    $shipper->setAttentionName('Pappu Shah');
    $shipperAddress = $shipper->getAddress();
    $shipperAddress->setAddressLine1('3728 Thurston St');
    $shipperAddress->setPostalCode('V5H0E6');
    $shipperAddress->setCity('Burnaby');
    $shipperAddress->setCountryCode('CA');
    $shipper->setAddress($shipperAddress);
    $shipper->setEmailAddress('parthforweb@gmail.com'); 
    $shipper->setPhoneNumber('6046165795');
    $shipment->setShipper($shipper);

    // To address
    $address = new \Ups\Entity\Address();
    $address->setAddressLine1('5449 Aberdeen St');
    $address->setPostalCode('V5R4M4');
    $address->setCity('Vancouver');
    $address->setCountryCode('CA');
    $shipTo = new \Ups\Entity\ShipTo();
    $shipTo->setAddress($address);
    $shipTo->setCompanyName('Bay Stranger');
    $shipTo->setAttentionName('Rajiv Sharma');
    $shipTo->setEmailAddress('shahparthpappu7028@yahoo.com'); 
    $shipTo->setPhoneNumber('6046165794');
    $shipment->setShipTo($shipTo);

    // From address
    $address = new \Ups\Entity\Address();
    $address->setAddressLine1('3728 Thurston St');
    $address->setPostalCode('V5H0E6');
    $address->setCity('Burnaby');
    $address->setCountryCode('CA');
    $address->setStateProvinceCode('BC');
    $shipFrom = new \Ups\Entity\ShipFrom();
    $shipFrom->setAddress($address);
    $shipFrom->setName('Parth Shah');
    $shipFrom->setAttentionName($shipFrom->getName());
    $shipFrom->setCompanyName($shipFrom->getName());
    $shipFrom->setEmailAddress('parthforweb@gmail');
    $shipFrom->setPhoneNumber('6046165795');
    $shipment->setShipFrom($shipFrom);

    // Sold to
    $address = new \Ups\Entity\Address();
    $address->setAddressLine1('5449 Aberdeen St');
    $address->setPostalCode('V5R4M4');
    $address->setCity('Vancouver');
    $address->setCountryCode('CA');
    $address->setStateProvinceCode('BC');
    $soldTo = new \Ups\Entity\SoldTo;
    $soldTo->setAddress($address);
    $soldTo->setAttentionName('Rajiv Sharma');
    $soldTo->setCompanyName($soldTo->getAttentionName());
    $soldTo->setEmailAddress('testuser1@soowop.ca');
    $soldTo->setPhoneNumber('6046165794');
    $shipment->setSoldTo($soldTo);

**Comment by parthustad** [comment]
$shipment = new Ups\Entity\Shipment;

    // Set shipper
    $shipper = $shipment->getShipper();
    $shipper->setShipperNumber('123456');
    $shipper->setName('Parth Shah');
    $shipper->setAttentionName('Pappu Shah');
    $shipperAddress = $shipper->getAddress();
    $shipperAddress->setAddressLine1('3728 Thurston St');
    $shipperAddress->setPostalCode('V5H0E6');
    $shipperAddress->setCity('Burnaby');
    $shipperAddress->setCountryCode('CA');
    $shipper->setAddress($shipperAddress);
    $shipper->setEmailAddress('parthforweb@gmail.com'); 
    $shipper->setPhoneNumber('6046165794');
    $shipment->setShipper($shipper);

    // To address
    $address = new \Ups\Entity\Address();
    $address->setAddressLine1('5449 Aberdeen St');
    $address->setPostalCode('V5R4M4');
    $address->setCity('Vancouver');
    $address->setCountryCode('CA');
    $shipTo = new \Ups\Entity\ShipTo();
    $shipTo->setAddress($address);
    $shipTo->setCompanyName('Parthcreation');
    $shipTo->setAttentionName('Parth Sharma');
    $shipTo->setEmailAddress('testuser1@asdasd.com'); 
    $shipTo->setPhoneNumber('6046165793');
    $shipment->setShipTo($shipTo);

    // From address
    $address = new \Ups\Entity\Address();
    $address->setAddressLine1('3728 Thurston St');
    $address->setPostalCode('V5H0E6');
    $address->setCity('Burnaby');
    $address->setCountryCode('CA');
    $address->setStateProvinceCode('BC');
    $shipFrom = new \Ups\Entity\ShipFrom();
    $shipFrom->setAddress($address);
    $shipFrom->setName('Parth Shah');
    $shipFrom->setAttentionName($shipFrom->getName());
    $shipFrom->setCompanyName($shipFrom->getName());
    $shipFrom->setEmailAddress('parthforweb@gmail');
    $shipFrom->setPhoneNumber('6046165794');
    $shipment->setShipFrom($shipFrom);

    // Sold to
    $address = new \Ups\Entity\Address();
    $address->setAddressLine1('5449 Aberdeen St');
    $address->setPostalCode('V5R4M4');
    $address->setCity('Vancouver');
    $address->setCountryCode('CA');
    $address->setStateProvinceCode('BC');
    $soldTo = new \Ups\Entity\SoldTo;
    $soldTo->setAddress($address);
    $soldTo->setAttentionName('Rasdajiva Sharma');
    $soldTo->setCompanyName($soldTo->getAttentionName());
    $soldTo->setEmailAddress('asdada@asdasd.com');
    $soldTo->setPhoneNumber('6046165793');
    $shipment->setSoldTo($soldTo);

**Comment by gabrielbull** [comment]
Your not setting a province or state for the shipper. Can you try doing that?

**Comment by parthustad** [comment]
where ?

i have added all XX variables in the files

**Comment by gabrielbull** [comment]
What do you mean by XX variable? The error provided by UPS states that you have no state or province code for the shipper, which you don't.  Adding it to the shipper part like this should fix your issue:

```php
// Set shipper
$shipper = $shipment->getShipper();
$shipper->setShipperNumber('123456');
$shipper->setName('Parth Shah');
$shipper->setAttentionName('Pappu Shah');
$shipperAddress = $shipper->getAddress();
$shipperAddress->setAddressLine1('3728 Thurston St');
$shipperAddress->setPostalCode('V5H0E6');
$shipperAddress->setCity('Burnaby');
$shipperAddress->setStateProvinceCode('BC');
$shipperAddress->setCountryCode('CA');
$shipper->setAddress($shipperAddress);
$shipper->setEmailAddress('parthforweb@gmail.com'); 
$shipper->setPhoneNumber('6046165794');
$shipment->setShipper($shipper);
```

**Comment by gabrielbull** [comment]
I'm closing the issue for now, let us know if it still does not work.

**Comment by parthustad** [comment]
i have set it
now its showing  invalid shipper number 

from where can i get shipper number?
shippier is the same as account number?

**Comment by parthustad** [comment]
Solved it
Thank you very much
