### ISSUE TITLE
using the rating api

### ISSUE THREAD

**Issue by tgoeminne** [gabrielbull/php-ups-api#131]
Hi,

I am trying to use the rate class, but when it have an error like a service is not available between origin and destination address, it will throw an error. How can I stop it from throwing fatal errors, and instead get an error response?

I am using this with cakephp.

**Comment by stefandoorn** [comment]
Hi @tgoeminne, you can catch the Exception we throw and handle it in a gentle way how you would like.

Something like this:

````
try {
    $result = $api->getRates(....);
} catch (\Exception $e) {
    echo 'Error occured: ' . $e->getMessage();
}
````

You will see that the code of $e->getCode() will be the error code UPS returns, so you can also use that to conditionally handle errors in a different way. We don't create unique exceptions for all their error messages, as it are quite a lot. Nice feature for later :)

**Comment by gabrielbull** [comment]
Fatal errors are not catchable. @tgoeminne Are you sure the library is throwing a fatal error and not just throwing a normal error? Can you copy paste the exact error here?

**Comment by tgoeminne** [comment]
`public function getUpsRate($data){
    	
    	require_once(ROOT .DS. "vendor" .DS. "gabrielbull" . DS  . "ups-api" . DS . "src" . DS . "Ups.php");
    	
    	$rate = new Ups\Rate($this->accessKey,$this->userId,$this->password);
    	
    	try{
    	$shipment = new \Ups\Entity\Shipment();
    	$shipperAddress = $shipment->getShipper()->getAddress();
    	$shipperAddress->setPostalCode('90210');
    	$shipperAddress->setCountryCode('US');
    	
    	$address = new \Ups\Entity\Address();
    	//$address->setAddressLine1($data['shipFromAddress']);
    	//$address->setCity($data['shipFromCity']);
    	$address->setPostalCode($data['shipFromPostalCode']);
    	$address->setCountryCode($data['shipFromCountryCode']);
    	
    	$shipFrom = new \Ups\Entity\ShipFrom();
    	$shipFrom->setAddress($address);
    	$shipment->setShipFrom($shipFrom);
    	$shipTo = $shipment->getShipTo();
    	$shipTo->setCompanyName('Test Ship To');
    	$shipToAddress = $shipTo->getAddress();
    	//$shipToAddress->setAddressLine1($data['shipToAddress']);
    	//$shipToAddress->setCity($data['shipToCity']);
    	$shipToAddress->setPostalCode($data['shipToPostalCode']);
    	$shipToAddress->setCountryCode($data['shipToCountryCode']);
    	
    	$package = new \Ups\Entity\Package();
    	$package->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
    	$package->getPackageWeight()->setWeight($data['weight']);
    	$unit = new \Ups\Entity\UnitOfMeasurement;
    	$unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_KGS);
    	$package->getPackageWeight()->setUnitofMeasurement($unit);
    	
    	$dimensions = new \Ups\Entity\Dimensions();
    	$dimensions->setHeight(10);
    	$dimensions->setWidth(10);
    	$dimensions->setLength(10);
    	
    	$unit = new \Ups\Entity\UnitOfMeasurement;
    	$unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_CM);
    	$dimensions->setUnitOfMeasurement($unit);
    	$package->setDimensions($dimensions);
    	$shipment->addPackage($package);
    	
    	$results = $rate->shopRates($shipment);
    	
    	foreach($results->RatedShipment as $rating){
    	
    		$ratings[] = ['shippingmethod_id' => '2', 'shipping_notes' => $rating->Service->getName(),'shipping_amount' => $rating->TotalCharges->MonetaryValue,'currency' => $rating->TotalCharges->CurrencyCode];
    	
    	}
    	
    	return $ratings;
    	
    	}catch(Exception $e){
    		
    		// do nothing, there are no rates
    		
    	}
    }`

Failure: No Services found for origin and destination addresses. (110007)
Ups\Exception\InvalidResponseException

**Comment by gabrielbull** [comment]
Yeah, that's not a fatal error, you can try/catch this to get the error, like @stefandoorn said.

**Comment by tgoeminne** [comment]
Seems like I forgot the '\' in front of Exception, now it works as expected.

Thanks
