### ISSUE TITLE
UPS tracking in sandbox mode

### ISSUE THREAD

**Issue by aniketsawal** [gabrielbull/php-ups-api#132]
Hi,
I want to know wheather ups tracking works in sandbox mode or not?
I have placed shipping succesfully and got shipping label and tracking no in response.
Now I just want to  track my shipment. following is my code for tracking

try {
        $shipment = $tracking->track($trackingNo);
        var_dump($shipment);
        return view('Frontend.pages.home.tracking', compact('activity'));
     } catch (Exception $e) {
        var_dump($e);
 }

following is the response i have recieved from above code.

 +"Activity": {#425 ▼
      +"ActivityLocation": {#426 ▼
        +"Address": {#427 ▼
          +"CountryCode": "US"
        }
      }
      +"Status": {#428 ▼
        +"StatusType": {#429 ▼
          +"Code": "M"
          +"Description": "BILLING INFORMATION RECEIVED"
        }
        +"StatusCode": {#430 ▼
          +"Code": "MP"
        }
      }

the status only says that "BILLING INFORMATION RECEIVED".  How do I find wheather shipment has been shipped or in transit?

**Comment by stefandoorn** [comment]
@aniketsawal, not really. Your own created shipments won't be visible in there. If you check the Tracking API documentation from UPS, you will find a list of tracking numbers that you can use for specific scenarios. I think that's the only way to test your implementation.
