### ISSUE TITLE
Address Verify for INTL addresses

### ISSUE THREAD

**Issue by DasWookie** [gabrielbull/php-ups-api#136]
I can't get either the Address Verify or Simple Address Verify FNs working for anything but US addresses.

I see others mentioning they are using these modules in Europe, and there's notes about the Simple variant being useful for countries where street level address verification isn't possible. So clearly this SHOULD be working. However, any time I try an International address I'm getting failures either from the country code being invalid or missing. In my cited example below I'm using a CA/Canadian address, but seems that wheneer I'm attempting to address verify an international address either the country or postal code kicks back as invalid.

Is there some trick to getting international address validation working that differs from US addresses?

The unit tests are all using US addresses, so those weren't any help to debug the problem, and I've been beating my head against this rock for 1.5 days now. Figured it was finally time to ask because clearly I'm missing something!

Here's the object/array dump from the call using the Address Verify fn (with my credentials ****'d out):
``
object(Ups\Exception\InvalidResponseException)#31 (7) { ["message":protected]=> string(53) "Failure: Country Code is invalid or missing. (264002)" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(97) "/www/html/tyga/admin/shipping/vendor/gabrielbull/ups-api/src.stable/Request.php" ["line":protected]=> int(144) ["trace":"Exception":private]=> array(2) { [0]=> array(6) { ["file"]=> string(107) "/www/html/tyga/admin/shipping/vendor/gabrielbull/ups-api/src.stable/AddressValidation.php" ["line"]=> int(127) ["function"]=> string(7) "request" ["class"]=> string(11) "Ups\Request" ["type"]=> string(2) "->" ["args"]=> array(3) { [0]=> string(198) "**************** **************** ****************" [1]=> string(594) " XAV 1 8 Barny Venstison 4006 ecklestin dr Ontario Toronto CA m4a1k5 " [2]=> string(43) "https://onlinetools.ups.com/ups.app/xml/XAV" } } [1]=> array(6) { ["file"]=> string(56) "/www/html/tyga/admin/shippingLabel.php" ["line"]=> int(87) ["function"]=> string(8) "validate" ["class"]=> string(21) "Ups\AddressValidation" ["type"]=> string(2) "->" ["args"]=> array(3) { [0]=> object(Ups\Entity\Address)#17 (47) { ["AddressLine1"]=> string(15) "50 eccleston dr" ["AddressLine2"]=> string(0) "" ["AddressLine3"]=> NULL ["City"]=> string(7) "Toronto" ["StateProvinceCode"]=> string(7) "Ontario" ["PostalCode"]=> string(6) "m4a1k5" ["CountryCode"]=> string(2) "CA" ["PoliticalDivision1"]=> NULL ["PoliticalDivision2"]=> NULL ["PoliticalDivision3"]=> NULL ["PostcodePrimaryLow"]=> NULL ["PostcodePrimaryHigh"]=> NULL ["PostcodeExtendedLow"]=> NULL ["ResidentialAddressIndicator"]=> NULL ["ConsigneeName"]=> NULL ["StreetNumberLow"]=> NULL ["StreetPrefix"]=> NULL ["PostcodeextendedLow"]=> NULL ["StreetName"]=> NULL ["StreetType"]=> NULL ["StreetSuffix"]=> NULL ["BuildingName"]=> string(0) "" ["AttentionName"]=> string(16) "Barny Venstison" ["AddressExtendedInformation"]=> array(0) { } ["addressLine1":"Ups\Entity\Address":private]=> string(17) "4006 ecklestin dr" ["addressLine2":"Ups\Entity\Address":private]=> string(0) "" ["addressLine3":"Ups\Entity\Address":private]=> NULL ["city":"Ups\Entity\Address":private]=> string(7) "Toronto" ["stateProvinceCode":"Ups\Entity\Address":private]=> string(7) "Ontario" ["postalCode":"Ups\Entity\Address":private]=> string(6) "m4a1k5" ["countryCode":"Ups\Entity\Address":private]=> string(2) "CA" ["politicalDivision1":"Ups\Entity\Address":private]=> NULL ["politicalDivision2":"Ups\Entity\Address":private]=> NULL ["politicalDivision3":"Ups\Entity\Address":private]=> NULL ["postcodePrimaryLow":"Ups\Entity\Address":private]=> NULL ["postcodePrimaryHigh":"Ups\Entity\Address":private]=> NULL ["postcodeExtendedLow":"Ups\Entity\Address":private]=> NULL ["residentialAddressIndicator":"Ups\Entity\Address":private]=> NULL ["consigneeName":"Ups\Entity\Address":private]=> NULL ["streetNumberLow":"Ups\Entity\Address":private]=> NULL ["streetPrefix":"Ups\Entity\Address":private]=> NULL ["streetName":"Ups\Entity\Address":private]=> NULL ["streetType":"Ups\Entity\Address":private]=> NULL ["streetSuffix":"Ups\Entity\Address":private]=> NULL ["buildingName":"Ups\Entity\Address":private]=> string(0) "" ["attentionName":"Ups\Entity\Address":private]=> string(15) "Barny Venstison" ["addressExtendedInformation":"Ups\Entity\Address":private]=> array(0) { } } [1]=> int(1) [2]=> int(8) } } } ["previous":"Exception":private]=> NULL }
``

As can be seen in the dump, the country code provided is "CA" which, near as I know, should be a valid ISO input for o'Canada.

...and an excerpt from the call to the Simple Address Verify fn:
``
object(Ups\Exception\InvalidResponseException)#31 (7) { ["message":protected]=> string(68) **_"Failure: The field, PostalCode, contains invalid data, M4A1K (20008)"_** ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(97) "/www/html/tyga/admin/shipping/vendor/gabrielbull/ups-api/src.stable/Request.php"
...
array(6) { ["file"]=> string(56) "/www/html/tyga/admin/shippingLabel.php" ["line"]=> int(166) ["function"]=> string(8) "validate" ["class"]=> string(27) "Ups\SimpleAddressValidation" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> object(Ups\Entity\Address)#17 (47) { ["AddressLine1"]=> NULL ["AddressLine2"]=> NULL ["AddressLine3"]=> NULL ["City"]=> string(7) "Toronto" ["StateProvinceCode"]=> bool(false) ["PostalCode"]=> string(6) "m4a1k5" ["CountryCode"]=> string(2) "CA"
``
which, notice it's truncated the last char from the postal code, but in the array dump excerpt you can also see that the postalcode provided is the full "m4a1k5" string. I've tried calling strtoupper on the zipcode as well, which has had no change in the outcome either. So I'm really at a loss here.

Both FNs which when called against US addresses, are working fine. For any other country, be in o'Canada, or Europe, Australia, Asia, etc... no joy. It is pretty much always kicking back an error that it either doesn't like the country code or the zipcode.

As I also know any post requesting help must contain code to demonstrate the issue, here's a section of my code for the simple address check:

``
>         case 'simpleAddressVerify':
>          $address = new \Ups\Entity\Address();
>           $country = countryToISO(strtoupper($order->delivery['country']));  // Fetch 2 letter Country ISO
>           $address->setCountryCode($country);
>           if ($country == "US") {
>                 $state = stateToISO(strtoupper($order->delivery['state']));  // Fetch 2 letter State ISO
>           } else {
>                 $state = $order->delivery['state'];
>           }
>           $address->setStateProvinceCode($state);
>           $address->setPostalCode($order->delivery['postcode']);
>           $address->setCity($order->delivery['city']);
>           $av = new \Ups\SimpleAddressValidation($accessKey, $userId, $password, $useIntegration);
>           try {
>             $response = $av->validate($address);
>             echo "Possible addresses:  <br>";
>             echo '<table class="shippingTable" border="2" width="60%" cellspacing="0" cellpadding="5"><tr>';
>             foreach($response as $address) {
>                 echo    '<td>' .
>                         $order->delivery['name'] . '<br>' .
>                         $order->delivery['company'] . '<br>' .
>                         $address->Rank . '<br>' .
>                         $address->Quality . '<br>' .
>                         $address->Address->City . '<br>' .
>                         $address->Address->StateProvinceCode . '<br>' .
>                         $address->PostalCodeLowEnd . '<br>' .
>                         $address->PostalCodeHighEnd . '<br>' .
>                         $address->Address->countryCode . '<br>' .
>                         '</td>';
>             }
>             echo '</tr></table><hr>';
>           } catch (Exception $e) {
>            var_dump($e);
>           }
>           break;
``

I could provide the code from my address verification call as well, but that code is far longer and the issue is the same, so think it's safe providing just the one example. If requested I'll provide that code as well tho.

**Comment by stefandoorn** [comment]
I can see from your calls that you are using the (Extended) Address Validation service from UPS. This one only works in US & Puerto Rico. The other service (Simple Address Validation) gives less accurate and extensive results, but works in more countries in the world, e.g. European countries. I walked into the same problem when developing them unfortunately. So indeed best to begin with the simple validation.

The error returned regarding the CA postal code is an UPS error, which I can't help you with unfortunately. I have no clue why they don't like that postal code, if it's a correct one. It doesn't return me a result on Google Maps, but I'm not knowledged of the Canadian postal system. 

The input and outputs are not so easy to read for me (formatting), so I'm not sure what's going wrong besides the postal code. Could you check the UPS documentation if they mention anything about the postal code format regarding CA in Address Validation? Does it need a state code e.g.?

**Comment by stevecordrey** [comment]
@stefandoorn According to UPS's "Address Validation Street XML Developer Guide" dated January 9, 2017, they expect you to use that API for both US/PR street-level validation and Canadian/INTL address classification. I'm not sure if this is a significant update from the prior API, but I've tried this approach with the latest master release and it's not working. (Side note: I'm Canadian and can guarantee 100% that the address being used is valid for address classification). 

I've included a quick code snippet below with the results as well: 

```
            $address = new \Ups\Entity\Address();
            $address->setAddressLine1($data['street_address']);
            $address->setStateProvinceCode($data['state']);
            $address->setCity($data['city']);
            $address->setCountryCode($countryCode);
            $address->setPostalCode($data['postal_code']);

            $xav = new \Ups\AddressValidation($accessKey, $userId, $password);
            $xav->activateReturnObjectOnValidate();
            try {
                if ($countryCode == 'US') {
                    $result = $xav->validate($address, $requestOption = \Ups\AddressValidation::REQUEST_OPTION_ADDRESS_VALIDATION, $maxSuggestion = 15);
                } else {
                    $result = $xav->validate($address, $requestOption = \Ups\AddressValidation::REQUEST_OPTION_ADDRESS_CLASSIFICATION, $maxSuggestion = 15);
                }
            } catch (Exception $e) {
                var_dump($e);
            }

            if (isset($result)) {

                Debugbar::info('RESULT: ', $result);

                /*
                if ($result->noCandidates()) {
                    return array("status" => "invalid", "candidateAddresses" => null);
                }
                if ($result->isAmbiguous()) {
                    $candidateAddresses = $result->getCandidateAddressList();
                    Debugbar::info('CANDIDATE ADDRESSES: ', $candidateAddresses);
                    return array("status" => "ambiguous", "candidateAddresses" => $candidateAddresses);
                }
                if ($result->isValid()) {
                    // Address is valid as-is
                    $validAddress = $result->getValidatedAddress();
                    // Debugbar::info('VALID ADDRESS: ', $validAddress);
                    return array("status" => "valid", "validAddress" => $validAddress);
                }
                */
            }
```

![image](https://cloud.githubusercontent.com/assets/9402189/23613032/b3a14412-024b-11e7-9598-1b21eb1c812d.png)

**Comment by stefandoorn** [comment]
Hm, I'm not aware of that so it might be new indeed. I haven't checked the documentation since I wrote the API wrapper and the implementation on my end is still functioning without errors. I haven't used the classification part though.

What I think I see is that the API itself doesn't return error, it just return you a kind of useless result. This might be an issue in the parsing of the result, as probably the focus while developing was on address validation, not on classification.

Could you dump both the request XML and the response XML? That might be helpful trying to understand what goes to UPS & what they return, and to compare that with the result object you are getting.

Could you also try without the 'activateReturnObjectOnValidate' activated?

**Comment by scottcwilson** [comment]
Closing due to age.

**Comment by scottcwilson** [comment]
Address verification is only available in the US and Puerto Rico.  Will update documentation.

**Comment by stefandoorn** [comment]
Not true. There are 2 services, one is for US / PR, the other one is international.

**Comment by scottcwilson** [comment]
I literally just read the documentation.  I can't give you a URL because of the screwy way they did their website, but if you look at https://www.ups.com/upsdeveloperkit?loc=en_US and then click the link "Address Validation - City, State, ZIP", at the bottom of the page you'll see:

Availability
(2 countries or territories) United States and Puerto Rico

They must have changed this if you had seen reference to International support before.

**Comment by scottcwilson** [comment]
Also, you can verify what I'm saying by writing a small program to call SimpleAddressValidation->validate() with a foreign address .  You will get a 20008 return code.  Here's a test with Canada: 

`Ups\Exception\InvalidResponseException: Failure: The field, Country, contains invalid data, CA (20008) in /Users/scott/Sites/ups_test/ups_library/php-ups-api/src/Request.php on line 145`

**Comment by stefandoorn** [comment]
Last time I worked with UPS was 2 years ago on a NL account, maybe that's the thing. It always used to work - actually I added that validator myself here.. could be they changed something in the meanwhile, then it doesn't make sense to keep that validator here indeed.
