### ISSUE TITLE
In Service.php : Why doesn't (array) $serviceNames contains all the services ?

### ISSUE THREAD

**Issue by tomsihap** [gabrielbull/php-ups-api#137]
Trying to set a service in a \Ups\Rate object to get a rate :

```
// Set service
$service = new \Ups\Entity\Service;
$service->setCode($UPSserviceCode);
$service->setDescription($service->getName());
$shipment->setService($service);
```

$UPSserviceCode being one of the service codes returned in a TimeInTransit request.

Because of `Service::getName()` (line 151) being looking into `(array) $serviceNames`, if the service code isn't one of the array, it won't work.

The array being : 

```
private static $serviceNames = [
        '01' => 'UPS Next Day Air',
        '02' => 'UPS Second Day Air',
        '03' => 'UPS Ground',
        '07' => 'UPS Worldwide Express',
        '08' => 'UPS Worldwide Expedited',
        '11' => 'UPS Standard',
        '12' => 'UPS Three-Day Select',
        '13' => 'Next Day Air Saver',
        '14' => 'UPS Next Day Air Early AM',
        '54' => 'UPS Worldwide Express Plus',
        '59' => 'UPS Second Day Air AM',
        '65' => 'UPS Saver',
        '70' => 'UPS Access Point Economy'
    ];
```

For example, TimeInTransit from France to France will return many services, one of them whom code is 23 and defined in the same file :  `const TT_S_EU_EXPRESSPLUS  = '23';  // UPS Express Plus`

Obviously, this :  `$service->setCode(23); ` will raise an error : 
```
ErrorException in Service.php line 153: Undefined offset: 23
```

Why isn't there all the service names into the array ? 

And more, if I don't `$service->setDescription($service->getName());` to passthrough it, it will raise:
```
InvalidResponseException in Request.php line 144:
Failure: Invalid Service Type (111209)
```

How to get a rate for a service which isn't into the array then ?

**Comment by tomsihap** [comment]
When I rate UPS Express Plus with serviceCode 54 ('54' => 'UPS Worldwide Express Plus'), I get the same results, and also my negociated results, as I have in the UPS website from France to France, which product probably is the 23. 

So for now the problem but I still have to bind "European Union Destination within the origin country" products code (the ones returned by TimeInTransit) with the ones in the array. Strange thing, serviceCode 54 (and likely the others binded) isn't defined into the UPS's PDF file "Time In Transit Web Service Developer Guide".

**Comment by stefandoorn** [comment]
Not sure if I understand the question fully, but UPS has some shared codes which mean different things based on location unfortunately. Code 54 can be something different in US than in Europe. The basis for this module was developed with US/CA in mind I believe. 

Extra weird is that the codes in Rating API and TimeInTransit API are not corresponding. I have had contact with UPS about it and nobody knows why. I made an internal mapping in my own code to rewrite them for my use case, might be something you also need to do. You can find the correct codes in both API documentations. 

The error should be fixed ofcourse (undefined index), would you be able to submit a PR that checks for the existence and only returns a value if found? Else you don't need to use `getName()`, you can also just set a description yourselves.

Does this help?

**Comment by tomsihap** [comment]
Thanks for your help !

Well I'm having a correspondance table for the moment. Now I know that it is not a crazy behaviour ! I was affraid with this correspondance that Rate would rate me an international product instead of a national one (because I have to ask for a 54 which is a Worldwide product... Fortunately rated as a 23, EU National product as I need).

I'll refactor my application soon, this time I'll submit a PR then.
