### ISSUE TITLE
Locator Class  Failure: Invalid Access License number

### ISSUE THREAD

**Issue by xujiajun** [gabrielbull/php-ups-api#140]
Hi! Thanks for this great lib! 

Unfortunately I am not able to get it running. I tried out the Locator Class example, but always getting:

>object(Ups\Exception\InvalidResponseException)#26 (7) {
  ["message":protected]=>
  string(47) "Failure: Invalid Access License number (250003)"

Do you have any idea what could be the issue?

Thanks!

**Comment by stefandoorn** [comment]
I think you are using a wrong key to access the API. I think talking to your account manager to get the right one will be the solution.
