### ISSUE TITLE
UPS API Update On January, 9th 2017

### ISSUE THREAD

**Issue by tomsihap** [gabrielbull/php-ups-api#143]
There was an update this Monday of the APIs and the ToS, any implications for php-ups-api ? 
For now, everything works well to me. I don't know if UPS updates its APIs frequently, maybe this was just an annual update relative to legal updates on 2017 throughout countries worldwide. 

Note that Pickup API is now Collection API.

**Comment by stefandoorn** [comment]
API updates are done every quarter. In my implementation I don't see any issues, but good to have this issue open. 

Do you notice any implications?

**Comment by tomsihap** [comment]
Nothing for the moment except this change in name from "Pickup" to "Collection"

**Comment by hellboy81** [comment]
Is this API implemented by PHP UPS libraray?

**Comment by stefandoorn** [comment]
Sure. It might be that they added extra nodes and changed some things, but I don't think it's changed a lot.
