### ISSUE TITLE
Add support for Shoptimeintransit & Ratetimeintransit

### ISSUE THREAD

**Issue by mazzarito** [gabrielbull/php-ups-api#144]
Is there any way to do this with the current version or has anyone worked on this? As far as I can see we'd roughly need to:

* Add new entity `Ups\Entity\DeliveryTimeInformation`
* Add new method to `Ups\Entity\Shipment`:
  * `setDeliveryTimeInformation(DeliveryTimeInformation $deliveryTimeInformation)`
  * `getDeliveryTimeInformation(DeliveryTimeInformation $deliveryTimeInformation)`
* Add new method to `Ups\Rate`
  * `shopTimeInTransit`
  * `getRateTimeInTransit`

Does this sound correct or is there a way to do this already? Thanks

**Comment by stefandoorn** [comment]
I don't think we support this yet. I haven't been looking into it, and my current project also does not need it unfortunately.

What does it roughly do? There is a TimeInTransit class, but this seems something different?

**Comment by mazzarito** [comment]
From the docs:

> **Ratetimeintransit** = The
server rates with transit
time information

> **Shoptimeintransit** = The
server validates the
shipment, and returns rates
and transit times for all
UPS products from the
ShipFrom to the ShipTo
addresses.

Basically the same as a Rate request, or a Shop request, but you also get the data from time in transit in one go.

I'd be happy to do the work as my current project would benefit just wanted to see if I was overlooking something.

**Comment by stefandoorn** [comment]
Alright, sounds promising for new users so they don't have to implement two methods and combine the data (which is terrible as the codes do not match).

I'm not aware of anyone working on this, so please submit a PR. Thanks a lot in advance!

**Comment by ryross** [comment]
This issue can be closed now :)
