### ISSUE TITLE
Shipment Cancellation

### ISSUE THREAD

**Issue by ryansh100** [gabrielbull/php-ups-api#147]
Are there any plans to implement a cancel shipment method?

**Comment by stefandoorn** [comment]
It's already included actually :) It's called 'void'.

**Comment by ryansh100** [comment]
Okay, I see it's in the Shipping class now. Would you like me to write up some documentation on it?

**Comment by stefandoorn** [comment]
Sure! Would be very much appreciated :)

**Comment by MichaZ70** [comment]
Hello! can anyone show me how to pass a ShipmentID and the TrackingNumbers to void them:

`$api = new Ups\Shipping($accessKey, $userId, $password, $useIntegration);
$confirm = $api->void($shipmentId);`

This is working for only one TrackingNumber.

Thank you in Advance

Michael
