### ISSUE TITLE
Failure: A shipment cannot have a KGS/IN or LBS/CM or OZS/CM as its unit of measurements (110548)

### ISSUE THREAD

**Issue by EricLow525** [gabrielbull/php-ups-api#150]
Error: Failure: A shipment cannot have a KGS/IN or LBS/CM or OZS/CM as its unit of measurements (110548)

**Comment by stefandoorn** [comment]
This is an error returned by the UPS API itself, not by the library. Depending on the area I think you need to set the appropriate unit of measurements.

**Comment by qterik** [comment]
Im getting the same error. Anyone knows what caused this?
