### ISSUE TITLE
Add support for multiple FormTypes in InternationalForms.php

### ISSUE THREAD

**Issue by thijsw** [gabrielbull/php-ups-api#152]
Hi,

According to the documentation you can add an unbounded (UNB) amount of FormType instances to the `<InternationalForms>` tag in a Shipment Confirm Request. However, it seems that the current implementation only accepts a single type. Calling the `Ups\Entity\InternationalForms->setType()` method more than once overwrites a previous set type.

<img width="799" alt="Documentation about International Forms" src="https://cloud.githubusercontent.com/assets/28638/23708209/77515b0c-0415-11e7-9e76-85df7392d766.png">

**Comment by stefandoorn** [comment]
I think they recently changed that, as I have the impression it was different when I was implementing this part quite a while ago. If you would be able to submit a PR, that would be great. 

It potentially introduces BC, but I think we could adjust the `$formType` to be an array, adjusting `setType` to accept either a string or an array. If a string, we just create an array out of it. And next to this, maybe an `addType` method. What do you think about this approach?

**Comment by thijsw** [comment]
> It potentially introduces BC, but I think we could adjust the $formType to be an array, adjusting setType to accept either a string or an array.

This would work for the setter, but I guess for the `getType()` method we cannot prevent introducing a backwards-compatibility breaking change. I'd propose a new method `getTypes()` which returns an array of types and drop the `getType()` method altogether.
