### ISSUE TITLE
DOMDocument::createElement() expects parameter 2 to be string, array given

### ISSUE THREAD

**Issue by wojcikm** [gabrielbull/php-ups-api#160]
Exception is thrown in that line: 
```$confirm = $api->confirm(\Ups\Shipping::REQ_VALIDATE, $shipment);```
Parameters:
```\Ups\Shipping::REQ_VALIDATE = 'validate'```
```$shipment = ``` https://paste.ofcode.org/66KK44LVj4S6H4fbccenWw
Whole method: https://paste.ofcode.org/kchnXB2q4y98divT8HyWB6

```Confirm``` method in ```Shipping``` class:
```/**
     * Create a Shipment Confirm request (generate a digest).
     *
     * @param string $validation A UPS_Shipping::REQ_* constant (or null)
     * @param Shipment $shipment Shipment data container.
     * @param ShipmentRequestLabelSpecification|null $labelSpec LabelSpecification data. Optional
     * @param ShipmentRequestReceiptSpecification|null $receiptSpec ShipmentRequestReceiptSpecification data. Optional
     *
     * @throws Exception
     *
     * @return stdClass
     */
    public function confirm(
        $validation,
        Shipment $shipment,
        ShipmentRequestLabelSpecification $labelSpec = null,
        ShipmentRequestReceiptSpecification $receiptSpec = null
    )
```

Injected class ```CreateourierRequest``` is the validation class from ```Laravel``` framework. I commented the sections with ```$return```, cause I don't know from where it comes to this metod, secondly - I just want to work orders properly before. I looked up for other instructions, but unfortunately none of them worked for me.

**Comment by stefandoorn** [comment]
And what is the Exception being thrown? Could you copy/paste the full stack trace?

**Comment by wojcikm** [comment]
https://paste.ofcode.org/V7LrETmPJXSfprQG2CtNYr

**Comment by stefandoorn** [comment]
I think you are supplying the credentials wrong. How do you create your Shipping object?

**Comment by wojcikm** [comment]
```            $api = new \Ups\Shipping(config('ups.access'));```
``` 
'access' => [
        'token'         => 'token',
        'user'          => 'user',
        'password'      => 'pass',
    ],
```

**Comment by stefandoorn** [comment]
Alright. It has to be like this:

```
$api = new Ups\Shipping($accessKey, $userId, $password); 
$confirm = $api->confirm(\Ups\Shipping::REQ_VALIDATE, $shipment);
```

**Comment by wojcikm** [comment]
I've tried it at first, should've mentioned it at first. There is another exception when I use ``` $api = new Ups\Shipping($accessKey, $userId, $password); ```

https://paste.ofcode.org/naLKJf7DCXDXyx9rYcNniy

**Comment by stefandoorn** [comment]
Alright, but that seems like a connectivity issue from your server, looking at the error.

**Comment by wojcikm** [comment]
Definitely. The other question is, that locally I get this error, but on the production server everything looks to be ok.

**Comment by stefandoorn** [comment]
Hm ok. I never experienced this, but it might be due to firewall settings, etc. E.g. try to connect to it from curl on the command line, with some debug info. Can you ping to it? Can you disable firewall and test again? These would be the things I would try.

**Comment by wojcikm** [comment]
Firewall is diabled.
``` ping onlinetools.ups.com
PING onlinetools.ups.com (153.2.224.76) 56(84) bytes of data. ```
... and nothing happens.
With curl what did you mean to run exactly? I'm not experienced with using it.

**Comment by stefandoorn** [comment]
It looks to me like your dev environment or network has a firewall preventing you from connecting to the UPS service. Not really I can help you with from this side unfortunately.

**Comment by wojcikm** [comment]
Thanks for help anyway. Cheers.

**Comment by stefandoorn** [comment]
Good luck!

**Comment by wojcikm** [comment]
One more thing. I've resolved the problem above, but eventually did not get what I wanted. It gives a request to get the shipment letter, but I want to request a pickup. There is some ``` processPickupCreation() ``` method in ``` API ``` which is provided by UPS, but its highly unreadable and they use SOAP, wsdl etc. which confuses me much more and after all-day-long-struggling I am still on a start line. Do this repository has any possibility of doing it? Sorry for offtopic, maybe I should start a new conversation?

**Comment by stefandoorn** [comment]
I'm not aware of an implementation for the Pickup API. I don't think anyone ever added it. We mainly use the XML Webservices. If they support that, it should be quite ok to extend this library with that feature (and you might be able to create a PR with it).
