### ISSUE TITLE
Support for second Package ReferenceNumber

### ISSUE THREAD

**Issue by benwilson** [gabrielbull/php-ups-api#161]
I see Ups\Entity\Shipment::referenceNumber2 and, unless I misread the API docs, packages also support a second reference number. 

I have the requirement of listing the shipper invoice and customer PO number on each printed label. Requests respond with errors when I assign reference numbers to a shipment, so I assign them to individual packages. I put both in the single reference number as a workaround, so my requirement is technically satisfied, but it would be nice to eventually be able to assign them individually.

**Comment by stefandoorn** [comment]
Would you be able to add this functionality to the Package entity? I don't have recent docs, so can't really check it currently.
