### ISSUE TITLE
InternationalForms  add to Shipment

### ISSUE THREAD

**Issue by buday** [gabrielbull/php-ups-api#164]
Hi All, 

I want to add InternationalForms  to shipment method. Do you have any example on that?

bellow xml to InternationalForms query.
 
Thank you. 
J
`
            <InternationalForms>
  <FormType>01</FormType>
                <Product>
                    <FromType>01</FromType>
                    <Description>Women Accessories</Description>
                    <Unit>
                        <Number>1</Number>
                        <UnitOfMeasurement>
                            <Code>PC</Code>
                            <Description>Women Accessories</Description>
                        </UnitOfMeasurement>
                        <Value>7.54</Value>
                    </Unit>
                    <CommodityCode>1335440486743</CommodityCode>
                    <PartNumber>PART1</PartNumber>
                    <OriginCountryCode>TR</OriginCountryCode>
                </Product>
                <Product>
                    <FromType>01</FromType>
                    <Description>Women Accessories</Description>
                    <Unit>
                        <Number>1</Number>
                        <UnitOfMeasurement>
                            <Code>PC</Code>
                            <Description>Women Accessories</Description>
                        </UnitOfMeasurement>
                        <Value>11.33</Value>
                    </Unit>
                    <CommodityCode>1090250350617</CommodityCode>
                    <PartNumber>PART1</PartNumber>
                    <OriginCountryCode>TR</OriginCountryCode>
                </Product>
                <Product>
                    <FromType>01</FromType>
                    <Description>Women Accessories</Description>
                    <Unit>
                        <Number>1</Number>
                        <UnitOfMeasurement>
                            <Code>PC</Code>
                            <Description>Women Accessories</Description>
                        </UnitOfMeasurement>
                        <Value>18.91</Value>
                    </Unit>
                    <CommodityCode>1200000443503</CommodityCode>
                    <PartNumber>PART1</PartNumber>
                    <OriginCountryCode>TR</OriginCountryCode>
                </Product>
                <Product>
                    <FromType>01</FromType>
                    <Description>Women Accessories</Description>
                    <Unit>
                        <Number>1</Number>
                        <UnitOfMeasurement>
                            <Code>PC</Code>
                            <Description>Women Accessories</Description>
                        </UnitOfMeasurement>
                        <Value>15.12</Value>
                    </Unit>
                    <CommodityCode>1362080442213</CommodityCode>
                    <PartNumber>PART1</PartNumber>
                    <OriginCountryCode>TR</OriginCountryCode>
                </Product>
                <InvoiceNumber>3155201</InvoiceNumber>
                <InvoiceDate>20151207</InvoiceDate>
                <PurchaseOrderNumber>3155201</PurchaseOrderNumber>
                <TermsOfShipment>DDU</TermsOfShipment>
                <ReasonForExport>SALE</ReasonForExport>
                <Comments/>
                <DeclarationStatement>I hereby certify that the information on this invoice is true and correct and the contents and value of this shipment is as stated above.</DeclarationStatement>
                <Discount>
                    <MonetaryValue>7.54</MonetaryValue>
                </Discount>
                <FreightCharges>
                    <MonetaryValue>9.90</MonetaryValue>
                </FreightCharges>
                <InsuranceCharges>
                    <MonetaryValue>0</MonetaryValue>
                </InsuranceCharges>
                <Othercharges>
                    <MonetaryValue>1</MonetaryValue>
                    <Description>Tax</Description>
                </Othercharges>
                <CurrencyCode>USD</CurrencyCode>
            </InternationalForms>
       `

**Comment by stefandoorn** [comment]
You can use the `ShipmentServiceOptions` class, on which you can add an `InternationalForms` object, with all info you need. The ShipmentServiceOptions will be added on the Shipment later on. Something like this:

```
$shipmentServiceOptions = new \Ups\Entity\ShipmentServiceOptions;

$internationalForm = new \Ups\Entity\InternationalForms;

.. do stuff in here on $internationalForm

$shipmentServiceOptions->setInternationalForms($internationalForms);

$shipment->setShipmentServiceOptions($shipmentServiceOptions);
```

**Comment by buday** [comment]
Hi Stefan,

Thank you for your answer when I do like this 

> 
      $shipmentServiceOptions = new \Ups\Entity\ShipmentServiceOptions;
	$_InternationalForms 	= new \Ups\Entity\InternationalForms;


	$_InternationalForms->setType(\Ups\Entity\InternationalForms::TYPE_INVOICE);
	$_InternationalForms->setDeclarationStatement("I hereby certify that the information on this invoice is true and correct and the contents and value of this shipment is as stated above.");
	$_InternationalForms->setTermsOfShipment("DDU");
	$_InternationalForms->setReasonForExport(\Ups\Entity\InternationalForms::RFE_GIFT);//Gift...
	$_InternationalForms->setInvoiceNumber("$InvoiceNumber");
	$_InternationalForms->setCurrencyCode('USD');



	$shipmentServiceOptions->setInternationalForms($_InternationalForms);
	$shipment->setShipmentServiceOptions($shipmentServiceOptions);


I get that error Failure: The XML document is well formed but the document is not valid (10002)

When I remove InternationalForms things its working : (

where am I wrong?

thanks,
Jem

**Comment by buday** [comment]
I thing I must add Packages.php as well

**Comment by buday** [comment]
I get that XML 
```
 <ShipmentConfirmRequest>
   <Request>
     <TransactionReference/>
     <RequestAction>ShipConfirm</RequestAction>
     <RequestOption>validate</RequestOption>
   </Request>
   <Shipment>
     <Description>Metal Parts</Description>
     <Shipper>
      <Name>Europe</Name>
       <AttentionName>Europe</AttentionName>
     <ShipperNumber> A983X6</ShipperNumber>
       <PhoneNumber>05553868590</PhoneNumber>
      <EMailAddress>info@europe.com</EMailAddress>
       <Address>
         <AddressLine1>Kucuk Sener</AddressLine1>
        <AddressLine2>Sener Sokak </AddressLine2>
         <City>BURSA</City>
         <PostalCode>16250</PostalCode>
         <CountryCode>TR</CountryCode>
       </Address>
     </Shipper>
    <ShipTo>
       <CompanyName>John Doe</CompanyName>
       <AttentionName>John Doe</AttentionName>
       <PhoneNumber>07425245599</PhoneNumber>
       <EMailAddress>john@doe.CO.UK</EMailAddress>
       <Address>
        <AddressLine1>Unit 3</AddressLine1>
         <City>London</City>
         <PostalCode>Se17 5mx</PostalCode>
         <CountryCode>GB</CountryCode>
      </Address>
     </ShipTo>
     <ShipFrom>
       <CompanyName>Europe</CompanyName>
       <AttentionName>Europe</AttentionName>
       <PhoneNumber>05553868590</PhoneNumber>
       <Address>
         <AddressLine1>Kucuk Sener</AddressLine1>
         <City>BURSA</City>
         <PostalCode>16250</PostalCode>
         <CountryCode>TR</CountryCode>
       </Address>
     </ShipFrom>
     <SoldTo>
       <CompanyName>John Doe</CompanyName>
       <AttentionName>John Doe</AttentionName>
       <PhoneNumber>07425245599</PhoneNumber>
       <Address>
         <AddressLine1>Unit 3</AddressLine1>
         <City>London</City>
         <PostalCode>Se17 5mx</PostalCode>
         <CountryCode>GB</CountryCode>
       </Address>
     </SoldTo>
     <PaymentInformation>
       <Prepaid>
         <BillShipper>
           <AccountNumber>A983X6</AccountNumber>
         </BillShipper>
       </Prepaid>
     </PaymentInformation>
     <Service>
       <Code>65</Code>
       <Description>UPS Saver</Description>
     </Service>
     <InvoiceLineTotal>
       <CurrencyCode>USD</CurrencyCode>
       <MonetaryValue>100</MonetaryValue>
     </InvoiceLineTotal>
     <NumOfPiecesInShipment>1</NumOfPiecesInShipment>
     <Package>
       <Description>Metal Parts</Description>
       <PackagingType>
         <Code>02</Code>
         <Description/>
       </PackagingType>
       <PackageWeight>
         <Weight>1</Weight>
         <UnitOfMeasurement>
           <Code>KGS</Code>
           <Description>Metal Parts</Description>
         </UnitOfMeasurement>
       </PackageWeight>
       <Dimensions>
         <Length>30</Length>
         <Height>30</Height>
         <Width>30</Width>
         <UnitOfMeasurement>
           <Code>CM</Code>
           <Description/>
         </UnitOfMeasurement>
       </Dimensions>
       <PackageServiceOptions/>
     </Package>
     <ShipmentServiceOptions>
       <InternationalForms>
         <FormType>01</FormType>
         <InvoiceNumber>1000001</InvoiceNumber>
         <TermsOfShipment>DDU</TermsOfShipment>
         <ReasonForExport>GIFT</ReasonForExport>
         <DeclarationStatement>I hereby certify that the information on this invoice is true and correct and the contents and value of this shipment is as stated above.</DeclarationStatement>
         <CurrencyCode>USD</CurrencyCode>
         <Product>
           <Description>Metal Parts</Description>
           <CommodityCode>1335440486743</CommodityCode>
           <PartNumber>1000</PartNumber>
           <OriginCountryCode>TR</OriginCountryCode>
         </Product>
       </InternationalForms>
     </ShipmentServiceOptions>
     <ReferenceNumber>
       <Code>IK</Code>
       <Value/>
     </ReferenceNumber>
   </Shipment>
 </ShipmentConfirmRequest>
```

**Comment by stefandoorn** [comment]
Looks good to me, but the error you got most often means missing data. The error is coming from UPS itself, not from the package. I have no clue what is the reason in this particular case, but API support can help well with this always (in my experience). Or try to dig through the documentation which fields are required in your case.

**Comment by buday** [comment]
Hi Stefan,

ho do I add unit on product section this one 

`<UnitOfMeasurement>
                            <Code>PC</Code>
                            <Description>Women Accessories</Description>
                        </UnitOfMeasurement>`

> Product = new \Ups\Entity\Product;
> 
> $Product->setCommodityCode(1362080442213);///ask ?
> $Product->setOriginCountryCode("TR");
> $Product->setDescription1($ShipmentDescription);
> 
> $_InternationalForms->addProduct($Product);

**Comment by buday** [comment]
I try like this 

```
$_Unit = new \Ups\Entity\UnitOfMeasurement;
$_Unit->setCode(\Ups\Entity\UnitOfMeasurement::PROD_PIECE);
$_Unit->setDescription($ShipmentDescription);

$Product->setUnit($_Unit);
$_InternationalForms->addProduct($Product);
```

**Comment by buday** [comment]
I found the problem its invoice date missing. 

this is International forms if any one needs.

> `$shipment->setNumOfPiecesInShipment(1);//How Many items

	// InvoiceLines
    $invoiceLineTotal = new \Ups\Entity\InvoiceLineTotal;
    $invoiceLineTotal->setMonetaryValue("10");//Invoice Item Price
    $invoiceLineTotal->setCurrencyCode('USD');
	$shipment->setInvoiceLineTotal('10');//Invoice Total Value
	#
	#
	//InternationalForms
	$shipmentServiceOptions = new \Ups\Entity\ShipmentServiceOptions;
	$InternationalForms 	= new \Ups\Entity\InternationalForms;


	$InternationalForms->setType(\Ups\Entity\InternationalForms::TYPE_INVOICE);
	$InternationalForms->setDeclarationStatement("I hereby certify that the information on this invoice is true and correct and the contents and value of this shipment is as stated above.");
	$InternationalForms->setTermsOfShipment("DDU");
	$InternationalForms->setReasonForExport(\Ups\Entity\InternationalForms::RFE_GIFT);
	$InternationalForms->setInvoiceNumber('10001');//Invoice Number
	$InternationalForms->setCurrencyCode('USD');
	

	$InvoiceDate 		= new \DateTime('2017/01/01');
	$InternationalForms->setInvoiceDate($InvoiceDate);
	#
	#
	$Product = new \Ups\Entity\Product;
	$Product->setCommodityCode($ProductCommodityCode);
	$Product->setOriginCountryCode("TR");
	$Product->setDescription1('Metal Parts');
	$Product->setPartNumber('Product Code');
	#
	#
	$UnitOfMeasurement = new \Ups\Entity\UnitOfMeasurement;
    $UnitOfMeasurement->setCode(\Ups\Entity\UnitOfMeasurement::PROD_PIECE);
 	$UnitOfMeasurement->setDescription('Description');
	#
	#
	$Unit= new \Ups\Entity\Unit;
	$Unit->setNumber(1);
	$Unit->setValue('10');//Total Invoice Amount
	$Unit->setUnitOfMeasurement('PCS');
	#
	#
	#
	#
	$Product->setUnit($Unit);
 	$InternationalForms->addProduct($Product);
	$shipmentServiceOptions->setInternationalForms($InternationalForms);
	$shipment->setShipmentServiceOptions($shipmentServiceOptions);`
