### ISSUE TITLE
Adult Signature Required

### ISSUE THREAD

**Issue by shmaliy** [gabrielbull/php-ups-api#169]
How i can set Adult Signature Required option?

**Comment by conrad10781** [comment]
This is something we would need to know as well. Please advise.

**Comment by stefandoorn** [comment]
Looking at the code `src/Entity/DeliveryConfirmation` might be able to handle this. Also refer to the UPS documentation to help you find out what to send to UPS to enable this feature. This library helps you formatting the proper XML request. 

As far as I see now, creating an `DeliveryConfirmation` entity, setting the right code and injecting it into a `ShipmentServiceOptions` entity, which goes into the `Shipment` entity in the end.

Let me know if this worked. Else I'm happy to see some code examples. Haven't been working with the API myself lately.

**Comment by conrad10781** [comment]
@stefandoorn , that code doesn't seem to be in the version composer pulls. Is there any way to get that updated so we're not manually piecing together commits?

**Comment by stefandoorn** [comment]
Hm I searched on dev-master and ran into this. Is it not included in a release maybe yet? Can you try with dev-master for now to see if it works? I can release later if that's the issue.

**Comment by conrad10781** [comment]
@stefandoorn , sorry I updated my previous comment before you had a chance to respond. We can access it in dev-master , but don't want to use that long-term.

**Comment by stefandoorn** [comment]
Ah I see. I'll file a release tomorrow.

**Comment by conrad10781** [comment]
@stefandoorn , thanks. In the meantime, working from dev-master locally, adding the following to a shipment 

```
        $deliveryConfirmation = new \Ups\Entity\DeliveryConfirmation;
        $deliveryConfirmation->setDcisType(2);
        
        $shipmentServiceOptions = new \Ups\Entity\ShipmentServiceOptions();
        $shipmentServiceOptions->setDeliveryConfirmation($deliveryConfirmation);
        
        $shipment->setShipmentServiceOptions($shipmentServiceOptions);
```

results in:

```Failure: The requested accessory option is unavailable between the selected locations. (121211)```

I've tried multiple different valid address combinations, all return the same thing.

What's the best way to access the raw request being sent? Don't see any options off of ->getRequest()

**Comment by stefandoorn** [comment]
The Shipping class allows you to inject a PSR compatible logger, e.g. Monolog. If you inject one that logs to a file, you can easily see request xml and also the response xml. Else you can also just dump it in the Request class, but I prefer logging for continuous debugging.

**Comment by stefandoorn** [comment]
Released new version.

**Comment by conrad10781** [comment]
@stefandoorn , thanks for the release. The snippet I provided above works as intended for anyone else who needs the service.

The logger implementation was easy as we already use Monolog so it was just a matter of ->setLogger($logger) on the Shipping class like you mentioned. 

Regarding the issue outlined above, apparently, there are some issues with our address not being flagged properly for a delivery confirmation service at some point even though we're receiving packages daily that require signature. Separate issue, but in case someone encounters the same error.

**Comment by stefandoorn** [comment]
Thanks for letting me know @conrad10781. Hopefully you get the account issue solved soon :)

**Comment by conrad10781** [comment]
@stefandoorn , I've added the following PR ( https://github.com/gabrielbull/php-ups-api/pull/190 ) to resolve this issue (essentially copying the items from the ShipmentServiceOptions class to PackageServiceOptions ) . The current implementation of the DeliveryConfirmation only works on international shipments, and I'm shipping domestically.

UPS support provided the following with the implementation that is in the current master/release. The PR has an example of how to use the new code, which I verified resolves the problem, and unit tests all pass.

> Please try to request a Adult Signature under PackageServiceOptions and not ShipmentServiceOptions. Usually, ShipmentServiceOptions is for International packages.

**Comment by stefandoorn** [comment]
I assume you are in US then indeed. ShipmentServiceOptions is mainly used from EU (where I am). If you spot more of these things, please PR them :) Thanks!

**Comment by conrad10781** [comment]
@stefandoorn , I am in the US. I will definitely PR any other issues I run into. Thank you for this library. It has saved me and others countless amounts of time from development!

**Comment by conrad10781** [comment]
@stefandoorn , sorry one last question. Do you know when you might have a release for composer that includes this, so we can accommodate on our end?

**Comment by stefandoorn** [comment]
I already included it in a release yesterday :-)
