### ISSUE TITLE
how do you set the service type?

### ISSUE THREAD

**Issue by magna25** [gabrielbull/php-ups-api#17]
I am trying to get a rate and would like to set different service type. I think the current service type is set to ground and I am not able to change it even though I tried doing the below
    $obj-> \Ups\Entity\Service();
    $obj->setCode(14);

I don't see any changes in the price.. any thoughts? 

Also another issue...is there any way to get the overall summary of the package status while tracking? I mean like it gives you an array of every activity but there is no one object or class which shows the overall status of the package, I am using activity array[0] but not getting what I want.

**Comment by stefandoorn** [comment]
Hi @magna25,

Nearly:

        // Set service
        $service = new \Ups\Entity\Service;
        $service->setCode(\Ups\Entity\Service::S_STANDARD);
        $service->setDescription($service->getName()); // Optional
        $shipment->setService($service);

After setting the properties, make sure to set it to your main shipment object.

Regarding Tracking API, maybe @gabrielbull has a suggestion.
