### ISSUE TITLE
Ups\Exception\InvalidResponseException: Failure: Missing/Illegal Package/PackageWeight/Weight

### ISSUE THREAD

**Issue by mattwebdev** [gabrielbull/php-ups-api#173]
hey everyone (me again)! you will probably be hearing from me quite abit as i try to create this shipping module for drupal..... 

> Ups\Exception\InvalidResponseException: Failure: Missing/Illegal Package/PackageWeight/Weight (110601) in Ups\Request->request() (line 149 of modules/custom/commerce_ups/vendor/gabrielbull/ups-api/src/Request.php).

i have PackageWeight and Package defined and they are being used. so im not sure what this error is?

**Comment by mattwebdev** [comment]
for reference this is the project: https://github.com/mattwebdev/commerce_ups
this is the file - commerce_ups/src/Plugin/Commerce/ShippingMethod/CommerceUPS.php
the main concern is the functions around : BuildPackage

**Comment by stefandoorn** [comment]
Got it working @mattwebdev?

**Comment by mattwebdev** [comment]
i did! it took me actually looking at it rather then just opening a ticket... (>.<)
