### ISSUE TITLE
Error: Class 'Ups\Response' not found.

### ISSUE THREAD

**Issue by mattwebdev** [gabrielbull/php-ups-api#174]
hi! 
im getting an error after a standard composer install: 

> Error: Class 'Ups\Response' not found in Ups\Request->request() (line 140 of /ups-api/src/Request.php)

any thoughts?

**Comment by stefandoorn** [comment]
Not sure, never experienced this. Do you load the Composer supplied autoloader?

**Comment by mattwebdev** [comment]
my own stupidity, i was not using the autoload
