### ISSUE TITLE
Negotiated Rates?

### ISSUE THREAD

**Issue by mattwebdev** [gabrielbull/php-ups-api#183]
hi! im having an issue where i only see default rates and not negotiated rates, is there a way that i can choose to use those rates and not the default rates?

**Comment by stefandoorn** [comment]
You have to enable it (and from UPS side it has to be enabled on your account also - also check that with them):

```
// Ask for negotiated rates (optional)
$rateInformation = new \Ups\Entity\RateInformation;
$rateInformation->setNegotiatedRatesIndicator(1);
```

In the result the normal rates & negotiated rates are returned in separate nodes. So it's not that negotiated rates replace the default rates.

**Comment by mattwebdev** [comment]
so am i not able to shop rates for negotiated rates? 
i need the rate request to be the discounted rate.

**Comment by stefandoorn** [comment]
Yes, you are. Just activate the indicator and check with UPS that they also have it enabled on their side. Then you will get it as part of the XML response. You can only get negotiated rates if they are enabled for your account of course.

**Comment by mattwebdev** [comment]
thanks ill try that!
