### ISSUE TITLE
PDF Label

### ISSUE THREAD

**Issue by kev-landry** [gabrielbull/php-ups-api#184]
Great package.

As i am reading the ups doc api i understand there is a way to ask ups to send us the graphic label image as a pdf format : 
"/LabelRecoveryRequest/LabelSpecification/LabelImageFormat/Code"

Digging into your package there is a class Shipping with 2 functions  "recoverLabel" and "createRecoverLabelRequest".

But i can't find a way to make them work, i only can get the label with the gif format.

` try {
        $shipment = new Shipment();

        $shipper = $shipment->getShipper();
        $shipper->setShipperNumber($shipperNumber);
        $shipper->setName('COMPANY_NAME');
        $shipper->setAttentionName('COMPANY_NAME');
        $shipper->setPhoneNumber('0123456789');
        $shipperAddress = $shipment->getShipper()->getAddress();
        $shipperAddress->setPostalCode('10000');
        $shipperAddress->setAddressLine1('3552 Davis Drive');
        $shipperAddress->setCity('Morrisville');
        $shipperAddress->setStateProvinceCode('NC');
        $shipperAddress->setCountryCode('US');

        $address = new Address();
        $address->setPostalCode('27613');
        $address->setAddressLine1('12341 Strickland RdSte 106');
        //$address->setAddressLine2('BUSINESS ADDRESS 2');
        $address->setCity('Raleigh');
        $address->setCountryCode('US');
        $shipFrom = new ShipFrom();
        $shipFrom->setAddress($address);
        $shipFrom->setCompanyName('COMPANY_NAME');
        $shipment->setShipFrom($shipFrom);
        $ship = $shipment->getShipFrom();
        $ship->CompanyName = 'COMPANY_NAME';

        $shipTo = $shipment->getShipTo();
        $shipTo->setAttentionName('FIRSTNAME LASTNAME');
        $shipTo->setReceivingAddressName('FIRSTNAME LASTNAME');
        $shipTo->setPhoneNumber('999999999');
        $shipTo->setEmailAddress('EMAIL@DOMAIM.COM');
        $shipTo->setCompanyName('COMPANY_NAME');
        $shipToAddress = $shipTo->getAddress();
        $shipToAddress->setPostalCode('08817');
        $shipToAddress->setAddressLine1('100 Plainfield Ave Suite B3 Edison NJ 08817');
        //$shipToAddress->setAddressLine2('ADDRESS 2');
        $shipToAddress->setCity('Edison');
        $shipToAddress->setCountryCode('US');
        $shipment->setShipTo($shipTo);

        //Add package

        $unitofweight = new UnitOfMeasurement;
        $unitofweight->setCode(UnitOfMeasurement::UOM_KGS);

        $package = new Package();
        $package->getPackagingType()->setCode(PackagingType::PT_PACKAGE);
        $package->getPackageWeight()->setWeight('10');
        $package->getPackageWeight()->setUnitOfMeasurement($unitofweight);

        $dimensions = new Dimensions();
        $dimensions->setHeight(20);
        $dimensions->setWidth(21);
        $dimensions->setLength(33);

        $unit = new UnitOfMeasurement;
        $unit->setCode(UnitOfMeasurement::UOM_CM);

        $dimensions->setUnitOfMeasurement($unit);
        $package->setDimensions($dimensions);
        $shipment->addPackage($package);

        $referencenumber=new ReferenceNumber;
        //$referencenumber->setCode('RZ');
        $referencenumber->setValue('MYREFNUMBER_1');
        $shipment->setReferenceNumber($referencenumber);

        $service= new Service();
        $service->setCode("03");
        $shipment->setService($service);

        /*$returnservice = new ReturnService;
        $returnservice->setCode(ReturnService::PRINT_RETURN_LABEL_PRL);
        $shipment->setReturnService($returnservice);*/

        $billshipper= new BillShipper();
        $billshipper->setAccountNumber($userid);
        $prepaid=new Prepaid();
        $prepaid->setBillShipper($billshipper);

        $paymentInformation = new PaymentInformation;
        $paymentInformation->setPrepaid($prepaid);

        $shipment->setPaymentInformation($paymentInformation);

        //This will create UPS shipment
        $result = $shipping->confirm('nonvalidate', $shipment);

        $shipment_charges = $result->ShipmentCharges->TotalCharges->MonetaryValue;
        $shipment_weight = $result->BillingWeight->Weight." ".$result->BillingWeight->UnitOfMeasurement->Code;
        $tracking_number = $result->ShipmentIdentificationNumber;
        $shipment_digest = $result->ShipmentDigest; //can be used to print labels

        $accept = $shipping->accept($shipment_digest);

        $tracking_number = $accept->PackageResults->TrackingNumber;
        $imageformat = $accept->PackageResults->LabelImage->LabelImageFormat->Code;

        $base64image = $accept->PackageResults->LabelImage->GraphicImage;

        $image = base64_decode($base64image);

        $response = Response::make($image,200);

        // Set the mime type for the response.
        // We now use the Image class for this also.
        $response->header('content-type', 'image/gif');

        echo "<pre>"; 
        print_r($response);
        echo "</pre>";

    } catch (Exception $e) {
        echo "<pre>";
        print_r($e);
        $error = $e->getMessage();
        echo "</pre>";
    }``

The 2 methods in Shipping class :

```
public function recoverLabel($trackingData, $labelSpecification = null, $labelDelivery = null, $translate = null)
    {
        if (is_array($trackingData)) {
            if (!isset($trackingData['value'])) {
                throw new InvalidArgumentException('$trackingData parameter is required to contain `value`.');
            }

            if (!isset($trackingData['shipperNumber'])) {
                throw new InvalidArgumentException('$trackingData parameter is required to contain `shipperNumber`.');
            }
        }

        if (!empty($translate)) {
            if (!isset($translateOpts['language'])) {
                $translateOpts['language'] = 'fra';
            }

            if (!isset($translateOpts['dialect'])) {
                $translateOpts['dialect'] = 'FR';
            }
        }

        $request = $this->createRecoverLabelRequest($trackingData, $labelSpecification, $labelDelivery, $translate);
        $response = $this->request($this->createAccess(), $request, $this->compileEndpointUrl($this->recoverLabelEndpoint));

        if ($response->Response->ResponseStatusCode == 0) {
            throw new Exception(
                "Failure ({$response->Response->Error->ErrorSeverity}): {$response->Response->Error->ErrorDescription}",
                (int)$response->Response->Error->ErrorCode
            );
        } else {
            unset($response->Response);

            return $this->formatResponse($response);
        }
    }

    /**
     * Creates a label recovery request.
     *
     * @param string|array $trackingData
     * @param array|null $labelSpecificationOpts
     * @param array|null $labelDeliveryOpts
     * @param array|null $translateOpts
     *
     * @return string
     */
    private function createRecoverLabelRequest($trackingData, $labelSpecificationOpts = null, $labelDeliveryOpts = null, $translateOpts = null)
    {
        $xml = new DOMDocument();
        $xml->formatOutput = true;

        $container = $xml->appendChild($xml->createElement('LabelRecoveryRequest'));
        $request = $container->appendChild($xml->createElement('Request'));

        $node = $xml->importNode($this->createTransactionNode(), true);
        $request->appendChild($node);

        $request->appendChild($xml->createElement('RequestAction', 'LabelRecovery'));

        if (!empty($labelSpecificationOpts)) {
            $labelSpec = $request->appendChild($xml->createElement('LabelSpecification'));

            if (isset($labelSpecificationOpts['userAgent'])) {
                $labelSpec->appendChild($xml->createElement('HTTPUserAgent', $labelSpecificationOpts['userAgent']));
            }

            if (isset($labelSpecificationOpts['imageFormat'])) {
                $format = $labelSpec->appendChild($xml->createElement('LabelImageFormat'));
                $format->appendChild($xml->createElement('Code', $labelSpecificationOpts['imageFormat']));
            }
        }

        if (!empty($labelDeliveryOpts)) {
            $labelDelivery = $request->appendChild($xml->createElement('LabelDelivery'));
            $labelDelivery->appendChild($xml->createElement('LabelLinkIndicator', $labelDeliveryOpts['link']));
        }

        if (!empty($translateOpts)) {
            $translate = $request->appendChild($xml->createElement('Translate'));
            $translate->appendChild($xml->createElement('LanguageCode', $translateOpts['language']));
            $translate->appendChild($xml->createElement('DialectCode', $translateOpts['dialect']));
            $translate->appendChild($xml->createElement('Code', '01'));
        }

        return $xml->saveXML();
    }
```

**Comment by stefandoorn** [comment]
What I know from it, `returnService` is for return shipments, not normal shipments. I've never managed to get a PDF myself, I always used GIF. The default method to register a shipping should be enough to use. Unfortunately I'm not 100% sure how to transform the output into PDF, I did it using imagemagick myself on the server.

**Comment by kev-landry** [comment]
Well i tried evrything to get a PDF from the UPS API but it only return me a gif or html image.
This is unbelievable that a company like UPS can't do such thing, every others carriers companies api i work with return a PDF (chronopost DG Colissimo etc).

Anyway i managed to solve the problem using imagemagick as you did @stefandoorn.

`      
            $gif_content = base64_decode($accept->PackageResults->LabelImage->GraphicImage);


            $imagick = new Imagick();
            $imagick->readImageBlob($gif_content);
            $imagick->rotateImage(new ImagickPixel(), 90);
            $imagick->setFormat("pdf");
            $imagick->writeImage("gif_into_pdf.pdf");`

**Comment by stefandoorn** [comment]
Thanks for sharing :) Have you been in contact with UPS API support also about this matter? I didn't have the time back then to wait for an answer, so I took this approach. I have the impression the docs describe PDF support - but not sure how it works.
