### ISSUE TITLE
What should I add in app.config in my laravel project

### ISSUE THREAD

**Issue by devil19891025** [gabrielbull/php-ups-api#185]
I use compose to install this package in my laravel project.
I can't use any ups class in contoller.
What should I add in config/app.config
I can't fine any information about this problem.

**Comment by stefandoorn** [comment]
Hi @devil19891025. You might want to use this library as intermediate between Laravel and this library: https://github.com/ptondereau/Laravel-UPS-Api.

**Comment by devil19891025** [comment]
Hi @stefandoorn. It works, thank for your help :)
