### ISSUE TITLE
Negotiated rates cannot be returned without a valid account number.

### ISSUE THREAD

**Issue by mattwebdev** [gabrielbull/php-ups-api#186]
im not able to get negotiated rates from a request with proper auth token / user / password (works in other applications) im wondering what i could be missing. 

my XML auth request looks malformed when i log: $request->getRequest()->getAccess()... but its output as a string...so i dont expect it to be valid XML... 

i really need to get Negotiated Rates - here is my base Rate Request XML https://gist.github.com/mattwebdev/4c26876322d605b2d4019d783cf9cfcd

**Comment by stefandoorn** [comment]
It might be best to contact UPS support for this. To me the XML looks correct (so the library does its work), but no clue why UPS doesn't return them in that case.

**Comment by ryross** [comment]
I worked with @mattwebdev on this project and we're not having this issue anymore. Not sure how he got past it though.

**Comment by stefandoorn** [comment]
There is nothing in the library that enables this. It's something on UPS side :-) So probably they changed something.
