### ISSUE TITLE
Street Verification : Error Code 264030 The state is not supported in the Customer Integration Environment.

### ISSUE THREAD

**Issue by mattwebdev** [gabrielbull/php-ups-api#188]
i am getting this error when using certain states, and id like to know why. 
the UPS developer docs dont have a "condition" listed for this error which i find odd. 

the request and response logs: 

Request: <?xml version="1.0"?> XAV 1 1 292 Hastings IL Highland Park US 60035

Response: <?xml version="1.0"?>0FailureHard264030The state is not supported in the Customer Integration Environment.

not sure what the issue is....

**Comment by stefandoorn** [comment]
Hi @mattwebdev. Actually the error itself reveals it: **The state is not supported in the Customer Integration Environment.**. According to UPS docs only certain data is available in their test environment :) I also didn't get this in the beginning, but it's mentioned somewhere in their docs as far as I recall.

**Comment by NeerajDaffodil** [comment]
Hi Stefandoorn,
Can you please provide me List OR link where we can find allowed testing states?

Thanks in avance

**Comment by stefandoorn** [comment]
It used to be in the UPS docs, which can be downloaded via their website if you have a valid API account. Due to changing jobs, I don't have access anymore.

**Comment by naxo8628** [comment]
NOTE: In the Customer Integration Environment, Locator will only work in the following locales:
Country or Territory City
United States -> Atlanta
Canada -> Toronto
Germany -> Neuss
Mexico -> Mexico City

**Comment by abbasalshalchi** [comment]
the states are not mentioned anywhere and in the documentation for this error it has the description field empty, dispicable.
