### ISSUE TITLE
QuantumView ResidentialAddressIndicator null

### ISSUE THREAD

**Issue by tantuohy** [gabrielbull/php-ups-api#191]
I'm using the QuantumView class to get Quantum View Data subscription and I don't understand why **ResidentialAddressIndicator** object has no value (when documentation says it should have value of 0 = Unavailable, 1 = Commercial, 2 = Residential):

```
      ["DeliveryLocation"]=>
      object(stdClass)#67 (3) {
        ["AddressArtifactFormat"]=>
        object(stdClass)#65 (9) {
          ["StreetNumberLow"]=>
          string(4) "6914"
          ["StreetName"]=>
          string(3) "247"
          ["StreetType"]=>
          string(3) "HWY"
          ["StreetSuffix"]=>
          string(2) "NE"
          ["PoliticalDivision2"]=>
          string(5) "ELGIN"
          ["PoliticalDivision1"]=>
          string(2) "MN"
          ["CountryCode"]=>
          string(2) "US"
          ["PostcodePrimaryLow"]=>
          string(5) "55932"
          ["ResidentialAddressIndicator"]=>
          object(stdClass)#66 (0) {
          }
        }
```

Is this a bug with the php library?

**Comment by stefandoorn** [comment]
Not sure either, but I think the fact that it's returned says that it's enabled (haven't used it myself in a while). I'm not 100% sure, but it should be described in the UPS documentation. If you add a logger to your QuantumView object, you can easily capture the raw XML's being sent around to examine better.

**Comment by sentiasa** [comment]
Hi @tantuohy - I see you've achieved making the QVD events work. I'd be grateful if you can read and shed some light to me - https://github.com/gabrielbull/php-ups-api/issues/242.
