### ISSUE TITLE
Is Entity/PaymentInformation.php missing SplitDutyVATIndicator? 

### ISSUE THREAD

**Issue by scottcwilson** [gabrielbull/php-ups-api#200]
The schema ./PACKAGEWebServices/SCHEMA-WSDLs/ShipWebServiceSchema.xsd has

```
  <xsd:complexType name="PaymentInfoType">
    <xsd:sequence>
      <xsd:element name="ShipmentCharge" type="ship:ShipmentChargeType" maxOccurs="2"/>
      <xsd:element name="SplitDutyVATIndicator" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
```

and I'm trying to get the Billing: line on the label to say "F/D" instead of "P/P".

**Comment by scottcwilson** [comment]
... or it may be that the API is missing the ItemizedPaymentInformation element.

**Comment by stefandoorn** [comment]
@scottcwilson It could be that this has never been implemented on the library side. As I see it, it's one of the SOAP API's. Which one are you specific using? Don't we have the XML version of it implemented maybe?

**Comment by scottcwilson** [comment]
I am using the Shipping API.  I don't see how I could use it with what is there now, unless I am missing something.

**Comment by stefandoorn** [comment]
If you are using the Shipping API, could you check how it's defined in the Shipping API XML documentation from UPS? I'm not using UPS actively right now, so I don't have access to updated documentation. The copy pasted part in your initial message is from SOAP API documentation, which might be different.

**Comment by scottcwilson** [comment]
Attached are pages 55-63 of the Shipping Package XML Developer's Guide. 

[ItemizedPaymentInformation.pdf](https://github.com/gabrielbull/php-ups-api/files/1693265/ItemizedPaymentInformation.pdf)


The field of interest is the last field in the ItemizedPaymentInformation element: 

/ShipmentConfirmRequest/Shipment/ItemizedPaymentInformation/SplitDutyVATIndicator
SplitDutyVATIndicator
 
Required: No Type: String Max Allowed: 1 Length: 0
 Split Duty VAT Indicator. The presence indicates the payer specified for Transportation Charges will pay transportation charges and any duties that apply to the shipment. The payer specified for Duties and Taxes will pay the VAT (Value-Added Tax) only.
The payment method for Transportation charges must be UPS account. The UPS account must be a daily pickup account or an occasional account.

**Comment by stefandoorn** [comment]
Looking at the code (https://github.com/gabrielbull/php-ups-api/blob/ddf4bae66affdf4c0f4c499077057840a37eca65/src/Shipping.php#L308) it's not yet implemented. Would you be able to submit a PR to implement this functionality?

**Comment by scottcwilson** [comment]
<gulp!> This is a mighty big element for a first PR.

**Comment by scottcwilson** [comment]
hmm.... I might be able to do at least part of this.   Let me see.

**Comment by stefandoorn** [comment]
Great! :)

**Comment by scottcwilson** [comment]
OK PR submitted.  I will need some coaching on how to pass your style checker - I thought it fit with the existing style but I guess not.

**Comment by scottcwilson** [comment]
Issue fixed by https://github.com/gabrielbull/php-ups-api/pull/202/
