### ISSUE TITLE
Rates differ from UPS website

### ISSUE THREAD

**Issue by adamgravita** [gabrielbull/php-ups-api#201]
Hi there, thanks for all the great work! I'm having a little trouble getting correct prices for packages through the rate class. I am cross-referencing the information with the UPS website and the prices seem quite different. 

Just to note for the test, the package size's, weight and measurements were the same 

Here's my response :- 

<pre>
Array ( 
[0] => Array (
      [shippingmethod_id] => 1
      [shipping_notes] => UPS Standard 
      [shipping_amount] => 28.96 
      [currency] => GBP 
) 
[1] => Array ( 
      [shippingmethod_id] => 2
      [shipping_notes] => UPS Saver 
      [shipping_amount] => 54.17 
      [currency] => GBP 
) 
[2] => Array ( 
      [shippingmethod_id] => 3 
      [shipping_notes] => UPS Worldwide Express Plus 
      [shipping_amount] => 97.11 
      [currency] => GBP 
) 
[3] => Array (
      [shippingmethod_id] => 2 
      [shipping_notes] => UPS Worldwide Express 
      [shipping_amount] => 56.58 
      [currency] => GBP
 ) 
)
</pre>

Here's the data from the UPS website 

![image](https://user-images.githubusercontent.com/19911150/35796472-9c615780-0a54-11e8-984a-f7fb6bcf5ded.png)

Here's some code :- 

```
  $rate = new Ups\Rate(
        $accessKey,
        $userId,
        $password
    );

      try{
            $shipment = new \Ups\Entity\Shipment();
            $shipperAddress = $shipment->getShipper()->getAddress();
            $shipperAddress->setPostalCode('WF20XG');
            $shipperAddress->setCountryCode('GB');

            $address = new \Ups\Entity\Address();
            $address->setPostalCode('WF20XG');
            $address->setCountryCode('GB');

            $shipFrom = new \Ups\Entity\ShipFrom();
            $shipFrom->setAddress($address);
            $shipment->setShipFrom($shipFrom);
            $shipTo = $shipment->getShipTo();

            $shipTo->setCompanyName('Test Ship To');
            $shipToAddress = $shipTo->getAddress();

            $shipToAddress->setPostalCode('wf12fh');
            $shipToAddress->setCountryCode('GB');

            $package = new \Ups\Entity\Package();
            $package->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
            $package->getPackageWeight()->setWeight(0.5);
            $unit = new \Ups\Entity\UnitOfMeasurement;
            $unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_KGS);
            $package->getPackageWeight()->setUnitofMeasurement($unit);

            $dimensions = new \Ups\Entity\Dimensions();
            $dimensions->setHeight(4);
            $dimensions->setWidth(4);
            $dimensions->setLength(4);

            $unit = new \Ups\Entity\UnitOfMeasurement;
            $unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_CM);
            $dimensions->setUnitOfMeasurement($unit);
            $package->setDimensions($dimensions);

            $shipment->addPackage($package);

            $results = $rate->shopRates($shipment);

            foreach($results->RatedShipment as $key => $rating){
                $ratings[] = ['shippingmethod_id' => $key, 'shipping_notes' => $rating->Service->getName(),'shipping_amount' => $rating->TotalCharges->MonetaryValue,'currency' => $rating->TotalCharges->CurrencyCode];
            }

            print_r($ratings);

    } catch(Exception $e){

        print_r($e);
    }
```

**Comment by stefandoorn** [comment]
My assumption is that you have other negotiated rates under your account, which you need to tell the API to return, see this example: https://github.com/gabrielbull/php-ups-api#example-8. In the output the negotiated rates are returned next to the rates you already got, for comparison reasons. Could you have a look whether this solves your issue?

**Comment by stefandoorn** [comment]
In the example look for: `// Ask for negotiated rates (optional)`

**Comment by adamgravita** [comment]
hi @stefandoorn, much appreciated for your reply. I have tried adding the negotiated rate piece of information in the code and have this error message.

`Negotiated rates cannot be returned without a valid account number.`

I presume this is because I need to set up a payment card within the UPS website. But I'm not entirely sure.

![image](https://user-images.githubusercontent.com/19911150/35850922-461342c4-0b1e-11e8-92a6-04ef5dfc3bc7.png)

I don't suppose you have any more suggestions regarding this process?

**Comment by Fishy49** [comment]
This took me forever to work out but I got it working.
I had to do the following:
```
$shipper = $shipment->getShipper();`
$shipper->setShipperNumber('UPS ACCOUNT NUMBER');
...
$shipment->setShipper($shipper);

$shipment->setPaymentInformation(new \Ups\Entity\PaymentInformation('prepaid', (object)array('AccountNumber' => 'UPS ACCOUNT NUMBER')));
```

After that I was able to get Negotiated rates. Also make sure you put in as much address infor as possible into your shipper address object.

**Comment by adamgravita** [comment]
@Fishy49 thanks so much for your reply. I am feeling better about this! Although, I cannot figure out how to find out my UPS Account Number. The website is pretty terrible for this kind of information!

**Comment by Fishy49** [comment]
@adamgravita I agree, their website is a mess. I can't help you on finding the account number, unfortunately. That was provided to me by my client.
He did say it was was on his invoices from UPS, though...

**Comment by quentingosset** [comment]
@Fishy49  can you show me your total code ? because when i add your code, i have already the old price :/
