### ISSUE TITLE
Order Number when using SurePost

### ISSUE THREAD

**Issue by scottcwilson** [gabrielbull/php-ups-api#205]
For regular UPS services like ground or next day air, you can do 

`$shipment->setDescription('Order #' . $order_id);
`
and it will show the order number on the label.  But for SurePost, it doesn't show up on the label.  Any ideas on what to do instead?

**Comment by stefandoorn** [comment]
@scottcwilson I think that's something for UPS API support or the PDF documentation. I haven't used SurePost actually, so I think it's something specific to that service that you need to set/do which hopefully is covered by their documentation or support.

**Comment by scottcwilson** [comment]
I don't believe they support this.
