### ISSUE TITLE
Next Day Air Saver

### ISSUE THREAD

**Issue by dattocknight** [gabrielbull/php-ups-api#208]
Morning.

I've been tracking down a bug between one of our services, and another integration. When we send the shipping method to that third party service, it does not recognise it. This is because the third party service is looking for 'UPS Next Day Air Saver' but this component does that for all services, except Next Day Air Saver

https://github.com/gabrielbull/php-ups-api/blob/930028925774868bc8fae7e35238742cf201ee50/src/Entity/Service.php#L87

I've checked UPS directly, and it appears that UPS Next Day Air Saver is the correct name. Is this intended?

**Comment by stefandoorn** [comment]
Not sure @dattocknight. These names are what I've understood until now highly volatile on UPS side. In EU I often saw different names / numbers than in US. Anyway, the name is something we mainly use internal and can be adjusted yourselves. But, I don't think it harms to add 'UPS' in front of the name to make it consistent, especially if that's how UPS is doing themselves also.

Would you be able to submit a PR to correct this line?

**Comment by dattocknight** [comment]
I can indeed, just wanted to confirm that it wasn't an intentional design consideration. Thanks
