### ISSUE TITLE
A little help with International Shipments?

### ISSUE THREAD

**Issue by usafkirkland** [gabrielbull/php-ups-api#210]
Hi, I'm extremely grateful for this class.  I am easily able to find domestic shipping rates. But, I am stuck on how to get an international shipment rate.  I assumed it would be nothing more than changing the country, but that didn't seem to work.  Could you by chance help put me on the right track here?
 
I tried modifying:
$shipToAddress->setPostalCode($CustomerAddress['Zip']);
$shipToAddress->setPostcodePrimaryLow($candidateAddresses['Zip']);
$shipToAddress->setCountryCode($CustomerAddress['shippingcountry']);

**Comment by stefandoorn** [comment]
Hi @usafkirkland. Can you extend your code sample a bit? Not sure which API endpoint you are using for example and what settings you are furthermore setting :)

**Comment by usafkirkland** [comment]
I think that is my issue.  I am not sure which endpoint to use.  I am trying to capture the info via a function.  It is a rudimentary function based solely on the example provided until I can get a grasp on the class structure and capability.  This works great for domestic shipments, but I am clueless as to how to get an international rate.  Ideally I'd like to capture it in the same function, but if I need to parse the request and separate functions based on country that's ok too.  Thank you for the help!


	public function GetShippingRate($CustomerAddress, $SDPackage){
		


			$rate = new Ups\Rate($this->accessKey, $this->userId, $this->password);
			
			try {
			    $shipment = new \Ups\Entity\Shipment();
			
			    $shipperAddress = $shipment->getShipper()->getAddress();
			    $shipperAddress->setPostalCode($this->ScentfulDelights['Postal']);
			
			    $address = new \Ups\Entity\Address();
			    $address->setPostalCode($this->ScentfulDelights['Postal']);
			    $shipFrom = new \Ups\Entity\ShipFrom();
			    $shipFrom->setAddress($address);
			
			    $shipment->setShipFrom($shipFrom);
			
			    $shipTo = $shipment->getShipTo();
			    $shipTo->setCompanyName('Customer');
			    $shipToAddress = $shipTo->getAddress();
			    $shipToAddress->setPostalCode($CustomerAddress['Zip']);
			    $shipToAddress->setPostcodePrimaryLow($candidateAddresses['Zip']);
			   
			    $shipToAddress->setCountryCode($CustomerAddress['shippingcountry']);
			
			    $package = new \Ups\Entity\Package();
			    $package->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
			    $package->getPackageWeight()->setWeight($SDPackage['Weight']);
			    
			    // if you need this (depends of the shipper country)
			    $weightUnit = new \Ups\Entity\UnitOfMeasurement;
			    $weightUnit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_LBS);
			    $package->getPackageWeight()->setUnitOfMeasurement($weightUnit);
			
			    $dimensions = new \Ups\Entity\Dimensions();
			    $dimensions->setHeight($SDPackage['Height']);
			    $dimensions->setWidth($SDPackage['Width']);
			    $dimensions->setLength($SDPackage['Length']);
			
			    $unit = new \Ups\Entity\UnitOfMeasurement;
			    $unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_IN);
			
			    $dimensions->setUnitOfMeasurement($unit);
			    $package->setDimensions($dimensions);
			
			    $shipment->addPackage($package);
			
			    return $rate->getRate($shipment);
			} catch (Exception $e) {
			    return $e;
			}
			
		
		
		
		}//end GetShippingRate

**Comment by stefandoorn** [comment]
Have you tried setting a country (and more address info) on the ShipFrom object? Else I don't see anything weird..

**Comment by scottcwilson** [comment]
Closing due to age.
