### ISSUE TITLE
Country code 

### ISSUE THREAD

**Issue by namik-mesic** [gabrielbull/php-ups-api#212]
Hi,

I've been experimenting with the library.
No other code except US is accepted in both simple and full address validation.

Does this lib not support anything besides US or does UPS not generally accept anything else?

**Comment by stefandoorn** [comment]
I managed previously to do NL addresses with this one: https://github.com/gabrielbull/php-ups-api#simple-address-validation-class. Have you tried this one also?

**Comment by scottcwilson** [comment]
Closing due to lack of follow up.
