### ISSUE TITLE
setResidentialAddressIndicator not adjusting negotiated rates for shopRatesTimeInTransit

### ISSUE THREAD

**Issue by upstatebreaker** [gabrielbull/php-ups-api#217]
It seems that setResidentialAddressIndicator() is not adjusting the rates.

$shipToAddress = new \Ups\Entity\Address();
$shipToAddress->setResidentialAddressIndicator('');

$shipTo = new \Ups\Entity\ShipTo(); 
$shipTo->setAddress($shipToAddress);
$shipment->setShipTo($shipTo);

I have tried passing every argument I can think of...'', 'TRUE', 1, '1', and nothing seems to work. I can see the it being generated in the response, but the rate does not adjust when using.

$results = $rate->shopRatesTimeInTransit($shipment);

$results->RatedShipment->NegotiatedRates->NetSummaryCharges->GrandTotal->MonetaryValue

..I have everything else working, as far as negotiated rates, saturday delivery etc etc. This is the only thing giving me any trouble. I'm not sure if it's in the request, or in the way I am handling the response.

From what I can see in the docs, the API is expecting no value, and just expecting empty tags for:

`<ResidentialAddressIndicator></ResidentialAddressIndicator>`

with nothing in between the tags. Any ideas? Thank you in advance!

**Comment by DominiqueFERET** [comment]
I have same problems...

**Comment by DominiqueFERET** [comment]
Hello,

I have same problem...
