### ISSUE TITLE
Puerto Rico returns "Failure: Invalid Rate. (111546)" using RateTimeInTransit

### ISSUE THREAD

**Issue by summersab** [gabrielbull/php-ups-api#219]
I'm trying to perform a RateTimeInTransit call to a Puerto Rico address, but it returns "Failure: Invalid Rate. (111546)." I tried to pass PR as the country without a state as well as passing US as the country with PR as the state (both are technically valid), but they both return the same. I also tried changing the units to metric even though Puerto Rico uses Imperial measurements, and that returned the error that the units were invalid for the location (as expected). I'm using the example code from your README, and it works just fine for any other US address. I can give you a link to my development environment for my shopping cart if you'd like to test it out.

Thank you!

**Comment by stefandoorn** [comment]
Hi @summersab I'm afraid we cannot really help with this. As you mentioned, some calls work properly, some not. I suspect this to be with the data being inserted, and that's something UPS API Support best helps you with. We only know about the library, not the UPS specifics like this unfortunately (there are so many variables).

I'm closing this issue, but let us know if UPS API Support points you to an error with this library.

**Comment by summersab** [comment]
Huzzah! I FINALLY managed to get through to someone at UPS that could help, and I got it figured out. Here's what's required:
- InvoiceLineTotal must be set
- PackageWeight AND ShipmentTotalWeight must be set
- For PR, the CountryCode must be set to PR instead of US, and the StateProvinceCode must not be set.

To do that, this needs to be added to the example code found in the [README](https://github.com/gabrielbull/php-ups-api#ratetimeintransit-class):
```
// The first three lines are already in the README
$weightUnit = new \Ups\Entity\UnitOfMeasurement;
$weightUnit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_LBS);
$package->getPackageWeight()->setUnitOfMeasurement($weightUnit);

$shipmentTotalWeight = new \Ups\Entity\ShipmentTotalWeight;
$shipmentTotalWeight->setUnitOfMeasurement($weightUnit);
$shipmentTotalWeight->setWeight(1.00); // Use the actual decimal value of the shipment weight
$shipment->setShipmentTotalWeight($shipmentTotalWeight);

$invoiceLineTotal = new \Ups\Entity\InvoiceLineTotal;
$invoiceLineTotal->setMonetaryValue(1.00); // You can use $1.00 since this is just a rate/transit lookup.
$invoiceLineTotal->setCurrencyCode('USD');
$shipment->setInvoiceLineTotal($invoiceLineTotal);
```

I'll note that you MUST use the dev-master branch (instead of 0.8.0 which is currently provided by default by composer) because ShipmentTotalWeight and InvoiceLineTotal weren't added to Rate.php until April. With those changes, PR requests (and I bet Guam and others) work just fine.
