### ISSUE TITLE
Charges class gives a Notice on some cases

### ISSUE THREAD

**Issue by entrifis** [gabrielbull/php-ups-api#22]
Charges class gives the following Notice:

**Notice: Object of class stdClass could not be converted to double in Ups/Entity/Charges.php on line 19**

This happens because it receives $response->MonetaryValue equal to null or empty array, while String is expected

**Stack calls that cause the notice:**
Ups\Rate->shopRates
Ups\Rate->sendRequest
Ups\Rate->formatResponse
Ups\Entity\RateResponse->__construct
Ups\Entity\RatedShipment->__construct
Ups\Entity\RatedPackage->__construct
Ups\Entity\Charges->__construct( $response = class stdClass { public $CurrencyCode = class stdClass { }; public $MonetaryValue = class stdClass { } } )

**Temporary fix, replace line 19 with line:** if (isset($response->MonetaryValue) && $response->MonetaryValue instanceof String) {

**Proper fix should** investigate the sources of Class initilaization with null and empty array values passes

**Comment by gabrielbull** [comment]
Thanks for this. If you have time, I'd love to merge a Pull Request for this!

**Comment by stefandoorn** [comment]
Fixed a while ago in 75085ed75977624bbd8ea3e93295bfa92f44747d
