### ISSUE TITLE
Library doesn't escape special characters

### ISSUE THREAD

**Issue by summersab** [gabrielbull/php-ups-api#220]
I discovered a little edge-case that isn't handled with the library. I had an address that contained "Town & Country," and I wasn't able to create a label. Upon further digging, I realized that this is because the ampersand needs to be escaped in XML. I was able to fix this by wrapping my address fields in the following:
`htmlspecialchars([field_name], ENT_XML1, 'UTF-8')`

One COULD argue that this should be handled by the user. In that case, I think it should be noted in the documentation somewhere. However, I would submit that this should be handled by the library since this API abstracts out the details of building the UPS XML documents. In the most pure sense, users should be able to use the library without even being aware that XML is being generated in the background. As such, it shouldn't be the responsibility of the user to ensure that their code properly escapes characters for the creation of XML.

However, I'm FAR from a purist, I'm happy to keep on escaping the characters manually, and I think this is a fantastic API. I just thought I'd pitch this your way in the hopes of helping to improve the project.

Thanks!

**Comment by scottcwilson** [comment]
Would you please submit a PR to note this fact in the documentation?  Thanks.

**Comment by summersab** [comment]
I'm having trouble finding this mentioned in the newest API guides from UPS, but their 2012 guide (linked below) mentions the need to escape these characters at the bottom of page 22:
http://az480170.vo.msecnd.net/faf1c937-8b60-4754-a35a-02d031291a0f/docs/8588c6df-1498-4ae1-83e7-84ec4a960504/address-validation-street-level-xml-developers-guide.pdf

While this is the guide for Address Validation - Street Level, having an ampersand was preventing me from generating shipping labels. I imagine that this applies to the entire XML API since an ampersand is a reserved character in XML:
https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML

To be safe, it might be best to wrap all address fields in the htmlspecialchars() function since those are the fields that allow for free-form text from users/customers.

Let me know if that helps!
