### ISSUE TITLE
How do you validate shipping

### ISSUE THREAD

**Issue by ericmuigai** [gabrielbull/php-ups-api#227]
I am finding that I can get rates but on confirm shipping it throws errors such Failure: Missing/Invalid ShipTo PostalCode. Postal Code length must be 6. (120207).
How can I validate it before getting to the confirm.

**Comment by scottcwilson** [comment]
Just before the confirm, do 

`var_dump($shipment); `

where `$shipment` is the second parameter to `confirm()`.
