### ISSUE TITLE
Which API is for scheduling a collection?

### ISSUE THREAD

**Issue by trashbat** [gabrielbull/php-ups-api#228]
I need users to be able to print their label at home and schedule a collection date and time. I've used the Shipment class to generate the label, but I can't figure out how to schedule the collection. From reading the docs it sounds like I either need the Collect API or the Pickup API (which I'm struggling to tell the difference between), are these implemented yet?

**Comment by trashbat** [comment]
Never mind, I'm implementing the JSON Pickup API myself. Will submit a PR in the next few days.

**Comment by kgmayani** [comment]
Did you submit thin new api ?

**Comment by trashbat** [comment]
@kgmayani Sorry no, I didn't want to submit my partial implementation which has zero tests!

FWIW it has been working in production _on a low traffic site_ since last year without any issues, or at least my client never reported any! I am referencing my dev branch directly in the composer.json of the project, like so:

```
{
  [...]
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/trashbat/php-ups-api"
    }
  ],
  "require": {
    [...]
    "gabrielbull/ups-api": "dev-add-pickup-api",
    [...]
  }
}
```

**Comment by kgmayani** [comment]
thanks,
can you provide me example ?
