### ISSUE TITLE
Add InternationalForms example to README?

### ISSUE THREAD

**Issue by summersab** [gabrielbull/php-ups-api#236]
This isn't exactly an "issue," but this is the best place I could think to post this. Is it possible that someone could create some example code for how to use the InternationalForms API calls? UPS' organizational structure is more than a little daunting, and I'm having trouble figuring out where to begin. Here's what I'm trying to do:

- Create a shipment (already have this working)
- Generate commercial invoice/customs forms based on products being shipped
- Submit the forms from the previous step using Paperless Invoicing
- Print a label (already have this working)

I just need to add the form creation and submission to my flow, and I'll be good to go, but boy, knowing which objects are required, how they all relate to one another, etc. makes my eyes cross. Any help is very much appreciated!

**Comment by bmaggot** [comment]
It's similar to this:

`	$shipmentServiceOptions = new \Ups\Entity\ShipmentServiceOptions();
	//international forms
	if ($IF_needed) {
		$shipment->setNumOfPiecesInShipment($itemCount);//How Many items

		/// InvoiceLines
		$invoiceLineTotal = new \Ups\Entity\InvoiceLineTotal();
		$invoiceLineTotal->setMonetaryValue($order_data->get_total()); //Invoice Item Price
		$invoiceLineTotal->setCurrencyCode('EUR');
		$shipment->setInvoiceLineTotal($invoiceLineTotal); //Invoice Total Value
		#
		#
		//InternationalForms	
		$InternationalForms 	= new \Ups\Entity\InternationalForms();

		$InternationalForms->setType(\Ups\Entity\InternationalForms::TYPE_INVOICE);
		$InternationalForms->setDeclarationStatement("I hereby certify that the information on this invoice is true and correct and the contents and value of this shipment is as stated above.");
		$InternationalForms->setTermsOfShipment("DDU"); //choose yours
		$InternationalForms->setReasonForExport(\Ups\Entity\InternationalForms::RFE_SALE);  //choose yours
		$InternationalForms->setInvoiceNumber($order_id); //Invoice Number
		$InternationalForms->setCurrencyCode('EUR');  //choose yours


		$InvoiceDate 		= new \DateTime($order_data->order_date);
		$InternationalForms->setInvoiceDate($InvoiceDate);
		#
		#
		
 		foreach( $order_data->get_items() as $item_id => $product_item ){
			$quantity = $product_item->get_quantity(); // get quantity
			$product = $product_item->get_product(); // get the WC_Product object
				
			$Productx = new \Ups\Entity\Product();
			$Productx->setOriginCountryCode("US");  //choose yours
			
			$sku = $product->get_sku();
			if (empty($sku))
				$sku = get_post_meta( $item_value['variation_id'], '_sku', true );
			
			$Productx->setDescription1($product->get_title());
			$Productx->setPartNumber($sku);
			
			$Unit= new \Ups\Entity\Unit();
			$Unit->setValue(bcdiv($product_item->get_total(), $quantity, 2));
			$Unit->setNumber($quantity);
			$unitx = new \Ups\Entity\UnitOfMeasurement();
			$unitx->setCode(\Ups\Entity\UnitOfMeasurement::PROD_PIECES);
			$Unit->setUnitOfMeasurement($unitx);
			$Productx->setUnit($Unit);
			
			$InternationalForms->addProduct($Productx);
		} 
		
		$shipmentServiceOptions->setInternationalForms($InternationalForms);
	}`

The Unit gave me most headache.

**Comment by summersab** [comment]
Thank you, @bmaggot ! I really appreciate the response. I'm gonna give this a whirl over the weekend and see how it goes . . .

**Comment by summersab** [comment]
Sweetness! I got it to work. A few additional notes for posterity sake. The following additional fields/properties are required for international shipments but may not be necessary for domestic (I imagine that depends upon your country):
- /Shipment/Description
- /Shipment/SoldTo (the entire object is normally not required; company, attention name, and phone must be set along with the rest of the address)
- /Shipment/ShipTo (company, attention name, and phone must all be set)
- /Shipper/AttentionName
- /Shipper/PhoneNumber

I tend to not set some of those fields because it prints information on the label that I generally don't want to make accessible (like my name and phone number). So I am only setting them for int'l shipments.

Thanks again, @bmaggot !
