### ISSUE TITLE
Quantum View Data subscriptions says 'no files' even though there are

### ISSUE THREAD

**Issue by sentiasa** [gabrielbull/php-ups-api#242]
_I know this is not the place to ask and most probably this is not a repo-specific issue, but I am very confused on this topic. I'd be grateful for any help on what I may be possibly doing wrong or any direction at all. Thanks in advance._

-----

I have been trying to get the Quantum View Data subscriptions work but I couldn't with the api. I have created my subscription channel and I can confirm that there are files in the web interface.

However, whatever I tried, I couldn't make the api work to get the events of this channel.

```
$events = $quantumView->getSubscription("OutboundAPI", (time() - (3600 *5)) );
$events = $quantumView->getSubscription("OutboundAPI", (time() - (3600 *25)), (time() - (3600 *125)) );
$events = $quantumView->getSubscription("OutboundAPI", null, null, '190201_003017001');
```
I literally tried every single combination, even giving the fileName but it keeps insisting:

> "Failure: There are no files for the given Request"

When I try a non-existent subscription name, it gives me the right error: _"Failure: The following Subscription Names do not exist for the SubscriberID: NonExistent"_

```
$request: """
          <?xml version="1.0"?>\n
          <QuantumViewRequest xml:lang="en-US">\n
            <SubscriptionRequest>\n
              <Name>OutboundAPI</Name>\n
              <FileName>190201_003017001</FileName>\n
            </SubscriptionRequest>\n
            <Request>\n
              <TransactionReference/>\n
              <RequestAction>QVEvents</RequestAction>\n
            </Request>\n
          </QuantumViewRequest>\n
          """

        $endpointurl: "https://onlinetools.ups.com/ups.app/xml/QVEvents

// or for DateRange
         <DateTimeRange>\n
            <BeginDateTime>20190130060948</BeginDateTime>\n
            <EndDateTime>20190201060948</EndDateTime>\n
         </DateTimeRange>
```

![screen shot 2019-02-01 at 07 52 04](https://user-images.githubusercontent.com/9021386/52105180-5d5bf180-25f6-11e9-8794-22fac94ba370.png)
-------

I can confirm that the api credentials I use are the Administrator account and the QV Subscription is set to UPS Developer Kit.

![screen shot 2019-02-01 at 07 58 10](https://user-images.githubusercontent.com/9021386/52105416-58e40880-25f7-11e9-981a-e9bcf46a17c3.png)
![screen shot 2019-02-01 at 07 58 32](https://user-images.githubusercontent.com/9021386/52105417-58e40880-25f7-11e9-9330-eec440f668ad.png)

**Comment by nsaripalli** [comment]
Hi @sentiasa I'm having the same issue. By any chance were you able to get this to work?

**Comment by sentiasa** [comment]
@nsaripalli No I couldn't but I read - _Quantum View Data is not same with Quantum View Events_
