### ISSUE TITLE
Invalid UserId/Password. 25002

### ISSUE THREAD

**Issue by arwvisions** [gabrielbull/php-ups-api#243]
I can check rates just fine but when I try to use the shipment class I get "Failure: Invalid Authentication Information. (250002)"

Is this because I don't have access to the shipping API. I have double checked the credentials.

**Comment by sentiasa** [comment]
In [UPS Developer Kit > Manager Access Keys](https://www.ups.com/upsdeveloperkit/manageaccesskeys) - do you have Shipping API approved?

**Comment by arwvisions** [comment]
We will investigate this on Monday. Thx

**Comment by arwvisions** [comment]
All APIs are ether in production or test. I'll just start troubleshooting.

**Comment by jonathangreco** [comment]
@sentiasa @arwvisions I just encounter the same issue, my API acces are all "production"

![Capture d’écran 2019-04-24 à 10 57 21](https://user-images.githubusercontent.com/1587180/56646434-d90e8d00-667f-11e9-89d6-1182f0f35b13.png)

**Comment by jonathangreco** [comment]
Ok I manage to fix this.

It was a password issue.
If your password have special character like `&` it turns to `&amp;' which is bad I guess.

In order to make it work avoid using some of those special characters.
Changing my password for a more simpler one fixed it.

**Comment by AnnoyingTechnology** [comment]
> If your password have special character like `&` it turns to `&amp;` which is bad I guess.
Wow, that'd be a major overlook in this API's design process. 

I too have this issue and will be trying this out, thanks for posting your fix.
