### ISSUE TITLE
Rating api not work with LTL service

### ISSUE THREAD

**Issue by Gurtek13** [gabrielbull/php-ups-api#245]
If i tried to get rate with more than 108 inch length product then rating api give me error. But in the ups website there is option to pass more than 108 inch length product in rating api with LTL service. I check the service class file where available service code are written like shown below 
 private static $serviceNames = [
        '01' => 'UPS Next Day Air',
        '02' => 'UPS Second Day Air',
        '03' => 'UPS Ground',
        '07' => 'UPS Worldwide Express',
        '08' => 'UPS Worldwide Expedited',
        '11' => 'UPS Standard',
        '12' => 'UPS Three-Day Select',
        '13' => 'Next Day Air Saver',
        '14' => 'UPS Next Day Air Early AM',
        '54' => 'UPS Worldwide Express Plus',
        '59' => 'UPS Second Day Air AM',
        '65' => 'UPS Saver',
        '70' => 'UPS Access Point Economy',
        '93' => 'UPS Sure Post',
    ];
But there is no code LTL service.

I also tried to pass LTL service code manually but api return invalid service type. Here is the link of url from where i get the code for LTL service.

https://www.ups.com/worldshiphelp/WS19/ENU/AppHelp/Codes/UPS_Service_Codes_for_UPS_Freight.htm

**Comment by gabrielbull** [comment]
@Gurtek13 This library has no maintainer and is looking for one.
