### ISSUE TITLE
Error: Class 'Ups\Entity\Shipment' not found 

### ISSUE THREAD

**Issue by emanuelebord87** [gabrielbull/php-ups-api#246]
Hello,

I've install the package with composer and all requirements are satisfied but when i try to make a Shipment request I get this error:

Fatal error: Uncaught Error: Class 'Ups\Entity\Shipment' not found in ....

Where am I wrong?
Thanks

**Comment by robert-antczak** [comment]
Hi.
I had the same problem today. Try to insert backslash at the beginning of the path: \Ups\Entity\Shipment

**Comment by peter279k** [comment]
I don't have this issue and it's fine to load the `Ups\Entity\Shipment` class.

My installation steps are as follows:

```
php ~/composer.phar require gabrielbull/ups-api                394ms
Using version ^0.8.0 for gabrielbull/ups-api
```

The sample code snippets I execute:

```php
require __DIR__ . '/vendor/autoload.php'
use Ups\Entity\Shipment;
new Shipment();
echo Shipment::class; // "Ups\Entity\Shipmen"
```

**Comment by harshal17** [comment]
I am getting the same error today (10/23/2019)

Fatal error: Uncaught Error: Class 'Ups\Entity\Shipment' not found in

I tried adding the backslash before Ups as robert suggested but still get the same error. Anyone able to help?

**Comment by robert-antczak** [comment]
You can try to debug how the class is loaded. Check how looks file path in `findFile` and `findFileWithExtension` functions in `vendor/composer/ClassLoader.php` when autoloder tries load `'Ups\Entity\Shipment`.

**Comment by gabrielbull** [comment]
@emanuelebord87 This library has no maintainer and is looking for one.
