### ISSUE TITLE
"Call to undefined method Ups\Rate::shopRatesTimeInTransit()"

### ISSUE THREAD

**Issue by impactcolor** [gabrielbull/php-ups-api#248]
When running the sample code for rates time in transit I get the following error.
Any ideas?

**Comment by franklininnocent** [comment]
Hope this may help you

$rate = new RateTimeInTransit('AccessKey','UserId','Password');
......
......
$rate->shopRatesTimeInTransit($shipment);

Please look into this "RateTimeInTransit Class"

**Comment by gabrielbull** [comment]
@impactcolor This library has no maintainer and is looking for one.
