### ISSUE TITLE
Failure: Invalid Weight. (111546) using RateTimeInTransit

### ISSUE THREAD

**Issue by damisadam** [gabrielbull/php-ups-api#249]
Shipper address is:-
 
'postal_code'=>'03079',
'city'=>'Salem',
'state_code'=>'NH',
'country_code'=>'US',

And ship to address is :
country_code="SG"  (Singapore)
PostalCode="518463"
City="Tampines" 

All is working fine when I change the ship to address to US, But give "invalid Weight. (111546)"
error when I set the ship to address other then the US. 
Please check and let me know what is missing.

**Comment by damisadam** [comment]
My Request XML is:-
<?xml version="1.0"?>
<RatingServiceSelectionRequest xml:lang="en-US">
  <Request>
    <TransactionReference/>
    <RequestAction>Rate</RequestAction>
    <RequestOption>Shoptimeintransit</RequestOption>
  </Request>
  <PickupType>
    <Code>01</Code>
    <Description/>
  </PickupType>
  <Shipment>
    <Service>
      <Code>03</Code>
      <Description/>
    </Service>
    <Shipper>
      <Address>
        <AddressLine1>8 Industrial Way</AddressLine1>
        <City>Salem</City>
        <StateProvinceCode>NH</StateProvinceCode>
        <PostalCode>03079</PostalCode>
        <CountryCode>US</CountryCode>
      </Address>
    </Shipper>
    <ShipTo>
      <CompanyName/>
      <AttentionName/>
      <Address>
        <City>Tampines</City>
        <PostalCode>518463</PostalCode>
        <CountryCode>SG</CountryCode>
      </Address>
    </ShipTo>
    <ShipmentWeight>
      <Weight/>
      <UnitOfMeasurement>
        <Code>LBS</Code>
        <Description/>
      </UnitOfMeasurement>
    </ShipmentWeight>
    <Package>
      <PackagingType>
        <Code>02</Code>
        <Description/>
      </PackagingType>
      <PackageWeight>
        <Weight>70.032</Weight>
        <UnitOfMeasurement>
          <Code>LBS</Code>
          <Description/>
        </UnitOfMeasurement>
      </PackageWeight>
      <Dimensions>
        <Length>14</Length>
        <Height>23</Height>
        <Width>16</Width>
        <UnitOfMeasurement>
          <Code>IN</Code>
          <Description/>
        </UnitOfMeasurement>
      </Dimensions>
      <PackageServiceOptions/>
    </Package>
    <Package>
      <PackagingType>
        <Code>02</Code>
        <Description/>
      </PackagingType>
      <PackageWeight>
        <Weight>7.878</Weight>
        <UnitOfMeasurement>
          <Code>LBS</Code>
          <Description/>
        </UnitOfMeasurement>
      </PackageWeight>
      <Dimensions>
        <Length>5</Length>
        <Height>18</Height>
        <Width>12</Width>
        <UnitOfMeasurement>
          <Code>IN</Code>
          <Description/>
        </UnitOfMeasurement>
      </Dimensions>
      <PackageServiceOptions/>
    </Package>
    <ShipmentServiceOptions/>
    <DeliveryTimeInformation>
      <PackageBillType>03</PackageBillType>
    </DeliveryTimeInformation>
  </Shipment>
</RatingServiceSelectionRequest>

**Comment by arjendejong12** [comment]
Did you find out why it is not working?

**Comment by bputtick** [comment]
I have the same issue

**Comment by bputtick** [comment]
```
<?xml version="1.0"?>
<RatingServiceSelectionRequest xml:lang="en-US">
  <Request>
    <TransactionReference/>
    <RequestAction>Rate</RequestAction>
    <RequestOption>Shoptimeintransit</RequestOption>
  </Request>
  <PickupType>
    <Code>01</Code>
    <Description/>
  </PickupType>
  <Shipment>
    <Service>
      <Code>03</Code>
      <Description/>
    </Service>
    <Shipper>
      <Address>
        <PostalCode>RH17 XXX</PostalCode>
        <CountryCode>GB</CountryCode>
      </Address>
    </Shipper>
    <ShipFrom>
      <Address>
        <PostalCode>RH17 XXX</PostalCode>
        <CountryCode>GB</CountryCode>
      </Address>
    </ShipFrom>
    <ShipTo>
      <CompanyName>Test Ship To</CompanyName>
      <AttentionName/>
      <Address>
        <PostalCode>RH16 XXX</PostalCode>
        <CountryCode>GB</CountryCode>
      </Address>
    </ShipTo>
    <Package>
      <PackagingType>
        <Code>02</Code>
        <Description/>
      </PackagingType>
      <PackageWeight>
        <Weight>1</Weight>
        <UnitOfMeasurement>
          <Code>KGS</Code>
          <Description/>
        </UnitOfMeasurement>
      </PackageWeight>
      <Dimensions>
        <Length>30</Length>
        <Height>50</Height>
        <Width>40</Width>
        <UnitOfMeasurement>
          <Code>CM</Code>
          <Description/>
        </UnitOfMeasurement>
      </Dimensions>
      <PackageServiceOptions/>
    </Package>
    <ShipmentServiceOptions/>
    <DeliveryTimeInformation>
      <PackageBillType>03</PackageBillType>
      <Pickup>
        <Date>20190829</Date>
        <Time>210838</Time>
      </Pickup>
    </DeliveryTimeInformation>
  </Shipment>
</RatingServiceSelectionRequest>
```

**Comment by bputtick** [comment]
```
<?xml version="1.0"?>
<RatingServiceSelectionResponse>
  <Response>
    <ResponseStatusCode>0</ResponseStatusCode>
    <ResponseStatusDescription>Failure</ResponseStatusDescription>
    <Error>
      <ErrorSeverity>Hard</ErrorSeverity>
      <ErrorCode>111546</ErrorCode>
      <ErrorDescription>Invalid Weight.</ErrorDescription>
    </Error>
  </Response>
</RatingServiceSelectionResponse>
```

**Comment by bputtick** [comment]
Got it working.

/Shipment/ShipmentTotalWeight - required for all international shipments when retrieving time in transit information including letters and document shipments.

If you're using the master branch then just add:

```
$shipmentTotalWeight = new \Ups\Entity\ShipmentTotalWeight();
$shipmentTotalWeight->setWeight(1);
$shipmentTotalWeight->setUnitOfMeasurement($weightUnit);
$shipment->setShipmentTotalWeight($shipmentTotalWeight);
```

**Comment by gabrielbull** [comment]
@damisadam This library has no maintainer and is looking for one.
