### ISSUE TITLE
Mail Innovations Tracking Number not recognized as such

### ISSUE THREAD

**Issue by brianherbert** [gabrielbull/php-ups-api#260]
https://github.com/gabrielbull/php-ups-api/blob/e4cab940d76c0fb0b7ddbf2a0c6f6299fc9dcbcd/src/Tracking.php#L189

isMailInnovations() is returning false for a valid Mail Innovations number: 92612909841003543402721592 - This prevents the API from working properly.

```php
$tracking->track("92612909841003543402721592");
```
... throws an error that it's invalid. When forcing isMailInnovations() to return true, it works. The regex patterns probably need to be reviewed to catch this case.

**Comment by gabrielbull** [comment]
@brianherbert This library has no maintainer and is looking for one.
