### ISSUE TITLE
Shipper Class Problem

### ISSUE THREAD

**Issue by jpratt** [gabrielbull/php-ups-api#269]
I am trying to use the example for the shipper class to create a shipment. I am getting an error on this line:

```
$packageServiceOptions = new \Ups\Entity\PackageServiceOptions();
$packageServiceOptions->setShipperReleaseIndicator(true);
```
I am not seeing that method in the PackageServiceOptions class. Is this necessary?

**Comment by gabrielbull** [comment]
@jpratt This library has no maintainer and is looking for one.

**Comment by eduardo069** [comment]
@jpratt did you find out if it was necessary?

**Comment by ptondereau** [comment]
@eduardo069 xml entities are not very update to date with the current documentation. Can you please elaborate more?
