### ISSUE TITLE
DOMDocument::createElement(): unterminated entity reference *** in file /var/www/html/vendor/gabrielbull/ups-api/src/Shipping.php line 181. 

### ISSUE THREAD

**Issue by cottton** [gabrielbull/php-ups-api#270]
`DOMDocument::createElement(): unterminated entity reference *** in file /var/www/html/vendor/gabrielbull/ups-api/src/Shipping.php line 181. `

The problem was a `&` in the company name.

I didnt looked it up atm (time) but shouldnt all values added by `htmlspecialchars` into the xml?
(for security reasons!)

**Comment by gabrielbull** [comment]
@cottton This library has no maintainer and is looking for one.
