### ISSUE TITLE
UPS shipping request - XML form is well formed but document is invalid (10002)

### ISSUE THREAD

**Issue by jaydeeppedhadiya** [gabrielbull/php-ups-api#271]
`<?xml version="1.0"?><ShipmentConfirmRequest><Request><TransactionReference/><RequestAction>ShipConfirm</RequestAction><RequestOption>validate</RequestOption></Request><Shipment><Description>Order ID 3</Description><Shipper><Name>Planet Security USA - CCTV Store</Name><AttentionName>Planet Security USA - CCTV Store</AttentionName><ShipperNumber></ShipperNumber><PhoneNumber>+1 (305) 455-1722</PhoneNumber><EMailAddress>info@planetsecurityusa.com</EMailAddress><Address><AddressLine1>1936 NW 82nd Ave</AddressLine1><City>Doral</City><StateProvinceCode>FL</StateProvinceCode><PostalCode>33166</PostalCode><CountryCode>US</CountryCode></Address></Shipper><ShipTo><CompanyName>mmd</CompanyName><AttentionName>mmd</AttentionName><EMailAddress>mmsagencyusa@gmail.com</EMailAddress><Address><AddressLine1>228 Park Ave S</AddressLine1><StateProvinceCode>NY</StateProvinceCode><PostalCode>10003</PostalCode><CountryCode>US</CountryCode></Address></ShipTo><ShipFrom><CompanyName>Planet Security USA - CCTV Store</CompanyName><AttentionName>Planet Security USA - CCTV Store</AttentionName><PhoneNumber>+1 (305) 455-1722</PhoneNumber><Address><AddressLine1>1936 NW 82nd Ave</AddressLine1><City>Doral</City><StateProvinceCode>FL</StateProvinceCode><PostalCode>33166</PostalCode><CountryCode>US</CountryCode></Address></ShipFrom><SoldTo><CompanyName>mmd</CompanyName><AttentionName>mmd</AttentionName><Address><AddressLine1>228 Park Ave S</AddressLine1><StateProvinceCode>NY</StateProvinceCode><PostalCode>10003</PostalCode><CountryCode>US</CountryCode></Address></SoldTo><PaymentInformation><Prepaid><BillShipper><AccountNumber>14X6A9</AccountNumber></BillShipper></Prepaid></PaymentInformation><Service><Code>11</Code><Description>UPS Standard</Description></Service><RateInformation><NegotiatedRatesIndicator/></RateInformation><Package><Description>636</Description><PackagingType><Code>02</Code><Description></Description></PackagingType><PackageWeight><Weight>4</Weight><UnitOfMeasurement><Code>LBS</Code><Description></Description></UnitOfMeasurement></PackageWeight><Dimensions><Length>6</Length><Height>12</Height><Width>6</Width><UnitOfMeasurement><Code>IN</Code><Description></Description></UnitOfMeasurement></Dimensions><PackageServiceOptions/></Package><ShipmentServiceOptions/><ReferenceNumber><Code>IK</Code><Value>3</Value></ReferenceNumber></Shipment></ShipmentConfirmRequest>`

**Comment by gabrielbull** [comment]
@jaydeeppedhadiya This library has no maintainer and is looking for one.
