### ISSUE TITLE
Unencoded transaction reference causes errors when some characters are used

### ISSUE THREAD

**Issue by krisbailey** [gabrielbull/php-ups-api#274]
When characters that need to be escaped are used for the transaction reference it will break the xml.  Solution is to update file src/Ups.php line 162 from:
            $trxRef->appendChild($xml->createElement('CustomerContext', $this->context));
To:
            $trxRef->appendChild($xml->createElement('CustomerContext', htmlspecialchars($this->context)));

**Comment by gabrielbull** [comment]
@krisbailey This library has no maintainer and is looking for one.
