### ISSUE TITLE
SaturdayDelivery Option issue

### ISSUE THREAD

**Issue by franklininnocent** [gabrielbull/php-ups-api#278]
How to set setSaturdayDelivery option for rate list api.
I have tried with the following code

            $serviceOption= new \Ups\Entity\ShipmentServiceOptions();
            $serviceOption->setSaturdayDelivery(false);
            $shipment->setShipmentServiceOptions($serviceOption);

It returns the error "Failure: No matching Rate and Transit times available. (111562)". 

How to resolve this issue?

**Comment by gabrielbull** [comment]
@franklininnocent This library has no maintainer and is looking for one.
