### ISSUE TITLE
Failure: Invalid Shipment Contents Value. (111549)

### ISSUE THREAD

**Issue by franklininnocent** [gabrielbull/php-ups-api#279]
`<?xml version="1.0"?>
<RatingServiceSelectionRequest xml:lang="en-US">
  <Request>
    <TransactionReference/>
    <RequestAction>Rate</RequestAction>
    <RequestOption>Shoptimeintransit</RequestOption>
  </Request>
  <PickupType>
    <Code>01</Code>
    <Description/>
  </PickupType>
  <CustomerClassification>
    <Code>00</Code>
  </CustomerClassification>
  <Shipment>
    <Service>
      <Code>03</Code>
      <Description/>
    </Service>
    <Shipper>
      <ShipperNumber>XXXXXXX</ShipperNumber>
      <Address>
        <PostalCode>63114</PostalCode>
      </Address>
    </Shipper>
    <ShipFrom>
      <Address>
        <City>XXXXXX</City>
        <StateProvinceCode>MO</StateProvinceCode>
        <PostalCode>63114</PostalCode>
        <CountryCode>US</CountryCode>
      </Address>
    </ShipFrom>
    <ShipTo>
      <CompanyName>Test Ship To</CompanyName>
      <AttentionName/>
      <Address>
        <PostalCode>L4K2R5</PostalCode>
        <CountryCode>CA</CountryCode>
      </Address>
    </ShipTo>
    <RateInformation>
      <NegotiatedRatesIndicator/>
    </RateInformation>
    <Package>
      <PackagingType>
        <Code>02</Code>
        <Description/>
      </PackagingType>
      <PackageWeight>
        <Weight>21</Weight>
        <UnitOfMeasurement>
          <Code>LBS</Code>
          <Description/>
        </UnitOfMeasurement>
      </PackageWeight>
      <Dimensions>
        <Length>15</Length>
        <Height>13</Height>
        <Width>15</Width>
        <UnitOfMeasurement>
          <Code>IN</Code>
          <Description/>
        </UnitOfMeasurement>
      </Dimensions>
      <PackageServiceOptions/>
    </Package>
    <ShipmentServiceOptions/>
    <DeliveryTimeInformation>
      <PackageBillType>03</PackageBillType>
    </DeliveryTimeInformation>
  </Shipment>
</RatingServiceSelectionRequest>`

**Comment by gabrielbull** [comment]
@franklininnocent This library has no maintainer and is looking for one.
