### ISSUE TITLE
Failure: Missing or Invalid Total Number of Pieces in all Pallets in a Shipment. (120030)

### ISSUE THREAD

**Issue by mswaqas** [gabrielbull/php-ups-api#280]
I am facing this error when I am trying to the international shipment.

 // Set service
        $service = new \Ups\Entity\Service;
        $service->setCode(\Ups\Entity\Service::S_UPSWW_EXPRESSFREIGHT);
        $service->setDescription($service->getName());
        $shipment->setService($service);

 $package = new \Ups\Entity\Package();
 $package->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_UNKNOWN);

**Comment by gabrielbull** [comment]
@mswaqas This library has no maintainer and is looking for one.
