### ISSUE TITLE
Pairing Service to Package type

### ISSUE THREAD

**Issue by fpgroups** [gabrielbull/php-ups-api#281]
Playing with provided sample code.  If I submit the request as given, I get response and have successfully parsed the returned objects.

Now, one will have the need to ship a pallet in occasion, I tried changing the service to S_GROUND and the package to PT_PALLET but I am getting error

object(Ups\Exception\InvalidResponseException)#52 (7) {
  ["message":protected]=>
  string(80) "Failure: The selected service is not valid with the selected packaging. (111500)"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(111500)
  ["file":protected]=>

I have tried multiple combinations and still getting the same error.  

Here is a snippet of the shipment object

["shipmentIndicationType":"Ups\Entity\Shipment":private]=>
  NULL
  ["service":"Ups\Entity\Shipment":private]=>
  object(Ups\Entity\Service)#22 (3) {
    ["Description"]=>
    string(10) "UPS Ground"
    ["code":"Ups\Entity\Service":private]=>
    string(2) "03"
    ["description":"Ups\Entity\Service":private]=>
    string(10) "UPS Ground"
  }
  ["returnService":"Ups\Entity\Shipment":private]=>
  NULL
  ["documentsOnly":"Ups\Entity\Shipment":private]=>
  NULL
  ["packages":"Ups\Entity\Shipment":private]=>
  array(1) {
    [0]=>
    object(Ups\Entity\Package)#6 (12) {
      ["packagingType":"Ups\Entity\Package":private]=>
      object(Ups\Entity\PackagingType)#7 (3) {
        ["code":"Ups\Entity\PackagingType":private]=>
        string(2) "30"
        ["description":"Ups\Entity\PackagingType":private]=>
        NULL
        ["Code"]=>
        string(2) "30"
      }
      ["packageWeight":"Ups\Entity\Package":private]=>
      object(Ups\Entity\PackageWeight)#17 (4) {
        ["UnitOfMeasurement"]=>
        object(Ups\Entity\UnitOfMeasurement)#21 (4) {
          ["Code"]=>
          string(3) "LBS"
          ["Description"]=>
          NULL
          ["code":"Ups\Entity\UnitOfMeasurement":private]=>
          string(3) "LBS"
          ["description":"Ups\Entity\UnitOfMeasurement":private]=>
          NULL
        }
        ["Weight"]=>
        int(750)
        ["unitOfMeasurement":"Ups\Entity\PackageWeight":private]=>
        object(Ups\Entity\UnitOfMeasurement)#21 (4) {
          ["Code"]=>
          string(3) "LBS"
          ["Description"]=>
          NULL
          ["code":"Ups\Entity\UnitOfMeasurement":private]=>
          string(3) "LBS"
          ["description":"Ups\Entity\UnitOfMeasurement":private]=>
          NULL
        }
        ["weight":"Ups\Entity\PackageWeight":private]=>
        int(750)
      }

What am I missing?

Thank you so much for your assistance!

**Comment by gabrielbull** [comment]
@fpgroups This library has no maintainer and is looking for one.
