### ISSUE TITLE
How do I add the element node "UserCreatedForm"

### ISSUE THREAD

**Issue by Boy-W** [gabrielbull/php-ups-api#286]
![image](https://user-images.githubusercontent.com/37936633/89277941-082fee80-d678-11ea-80ec-6e131c3007e9.png)

Hi,<br>&nbsp;&nbsp;&nbsp;&nbsp;I want to add UserCreatedForm node and DocumentID node,what should I do?

**Comment by gabrielbull** [comment]
@Boy-W This library has no maintainer and is looking for one.
