### ISSUE TITLE
How do a shipping with pickup

### ISSUE THREAD

**Issue by JhovidReiber** [gabrielbull/php-ups-api#287]
Good morning colleagues I hope you are well
I would really appreciate if you could help me with a question, it is that I need to create a shipment through this api, and I'm using the shipping class and it works perfectly, but how can I schedule a pickup with the shipment? I'm not sure what kind of UPS PHP API to use, I would really appreciate your help with an example to be able to meet this requirement.

**Comment by imtommychan1215** [comment]
XML post is not supported for pickup request. 
You may need to use trigger PickupCreationRequest using Pickup web service instead.

Reference: https://www.ups.com/upsdeveloperkit?&loc=en_hk
