### ISSUE TITLE
你好，能否出ups的json和国际快递的API

### ISSUE THREAD

**Issue by mofeier** [gabrielbull/php-ups-api#297]
1、希望有国际版的API。因为ups的PDF文档写的，可能在他们看来是能看懂，但是对于刚接入的人来说，写的不好理解，有的接口参数需要对应查PDF的xml格式去转为对应的json格式对接。咱这个API也得查看文件对应方法才知道调用那个变量参数。
2、现在UPS已有json格式的API，但是他的PDF文档中不明确，能否出json格式的API，响应速度会比xml快些。

**Comment by ptondereau** [comment]
@mofeier Hello!, can you please speak in english as I am not familiar without your language 😄

**Comment by mofeier** [comment]
Hello, can you design ups json and international express API
1. Now UPS has an API in json format, but it is not clear in his PDF document. Whether it can produce an API in json format, the response speed will be faster than xml
2. I hope you can have more detailed documentation, because the international version is not the same as the transportation within the United States, you need an EDI face sheet, and you must check the UPS documentation and the variables named in the current API code.

**Comment by ptondereau** [comment]
@mofeier yes  I say it yesterday, it's planned that I should do a deep refactor on available services for v2.
But there is a problem with json API: I would like to refactor Tracking request but the documentation doesn't say anything about json... But JSON Api is available on other services such as Address Validation.

For the moment, I don't have any ETA as I'm working on this package on my spare time.

**Comment by mofeier** [comment]
I don't know what you think of Shippo API. Although he is a more comprehensive international express, his grammar needs to be packaged separately. For modern PHP, that way is old.
In addition, I know that I’m tired of doing open source, and I don’t have any additional income. Sometimes I don’t have enough motivation. Open source also has no good way to increase revenue. Some of the open source in my country comes from voluntary donations from people in need, and there are other ways similar to Shippo. At the beginning, I was rather dizzy when connecting with UPS. . Later, I connected several UPS json interfaces through payment, but I did not package them. If necessary, I can give you the code. My English is not good and it is difficult to read UPS documents. Now rely on Google Translate.

**Comment by ptondereau** [comment]
I don't known Shippo but in v2, I will (not sure) to choose a better open source licence for this package. There is a licence that tell you must contribute to the code when in private field you improve this codebase. That should be a good starting point. My reflexion for the v2 is still new and I don't give a deep reflexion on the future.

**Comment by ptondereau** [comment]
@mofeier closing for now but I gathered your feedback, thank you!
