### ISSUE TITLE
Invalid Shipper Number

### ISSUE THREAD

**Issue by Abdullah1404111** [gabrielbull/php-ups-api#305]
I keep getting [this error](https://prnt.sc/vwqote) .

My example is as [this](https://prnt.sc/vwqp41)

**Comment by ptondereau** [comment]
I guess your using Shipper API.

This error is self-explanatory: your shipper number is invalid.
Documentation says:
```
Must be associated with the UserId specified int the AccessRequest XML.
```

**Comment by Abdullah1404111** [comment]
Is ShipmentIdentificationNumber the tracking number?

Thanks in advance.

**Comment by ptondereau** [comment]
yes the tracking number is starting with `1Z`.
In documentation, you have some numbers for CIE url (integration URL)
page 34
[Shipping Package Web Service Developer Guide.pdf](https://github.com/gabrielbull/php-ups-api/files/5652490/Shipping.Package.Web.Service.Developer.Guide.pdf)

**Comment by Abdullah1404111** [comment]
But whenever I am I am calling track(traking_number); the attached error is
occured.

**Comment by Abdullah1404111** [comment]
What could be the problem? Thanks for your kind response.

**Comment by ptondereau** [comment]
I don't know then, sorry. Try to use the UPS website to double-check that if it is a valid one.

**Comment by ptondereau** [comment]
Closing for now feel free to reopen if you found the solution
