### ISSUE TITLE
v1.2.1 on packagist

### ISSUE THREAD

**Issue by Dryobs** [gabrielbull/php-ups-api#315]
It seems 1.2.1 release is not available in Packagist.

Is it possible to publish it ? Then we can use this wonderful lib with taxes :)

Thanks in advance

**Comment by ptondereau** [comment]
I don't have the right to publish on packagist.
ping @gabrielbull

**Comment by gabrielbull** [comment]
@ptondereau what's your packagist username?

**Comment by ptondereau** [comment]
rooferz 
Thank you

**Comment by ptondereau** [comment]
v1.2.2 released!
