### ISSUE TITLE
Address validation

### ISSUE THREAD

**Issue by vvh-empora** [gabrielbull/php-ups-api#36]
it is possible to validate a shipping address with this lib?

**Comment by stefandoorn** [comment]
There's no standalone wrapper for that yet, but you are welcome to submit a pull request with that feature. The Shipment API & the Rating API support address validation, but that's not a standalone validator. Besides that UPS Address validation only supports US addresses unfortunately.

**Comment by vvh-empora** [comment]
look this: https://github.com/bkuhl/simple-ups/#address-validation

**Comment by stefandoorn** [comment]
It would be nice to have a version also in this library, as it's more complete currently with other API calls also. If you have time for it, it would be nice to integrate it. I'm not able to look into it right now.

**Comment by vvh-empora** [comment]
sry, i dont have time to handle this too...
