### ISSUE TITLE
How to get rates for multiple packages?

### ISSUE THREAD

**Issue by varmad** [gabrielbull/php-ups-api#38]
Hello,

How I get shipping rates for multiple packages?
Is length, width, height values are mandate or optional?

Thanks,
Srinivasa Varma

**Comment by adnanhader** [comment]
Here it is bro
//Package 1
$package1 = new \Ups\Entity\Package();
$package1->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
$package1->getPackageWeight()->setWeight($weight);
        
$dimensions = new \Ups\Entity\Dimensions();
$dimensions->setHeight($height);
$dimensions->setWidth($width);
$dimensions->setLength($length);

$unit = new \Ups\Entity\UnitOfMeasurement;
$unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_IN);

$dimensions->setUnitOfMeasurement($unit);
$package1->setDimensions($dimensions);
///Package 2
$package2 = new \Ups\Entity\Package();
$package2->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
$package2->getPackageWeight()->setWeight($weight);
        
$dimensions = new \Ups\Entity\Dimensions();
$dimensions->setHeight($height);
$dimensions->setWidth($width);
$dimensions->setLength($length);

$unit = new \Ups\Entity\UnitOfMeasurement;
$unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_IN);

$dimensions->setUnitOfMeasurement($unit);
$package2->setDimensions($dimensions);
//Add package one
$shipment->addPackage($package1);
//Add package Two
$shipment->addPackage($package2);

**Comment by varmad** [comment]
Thanks.. @adnanhader
