### ISSUE TITLE
How to create shipment after my order is successfully?

### ISSUE THREAD

**Issue by varmad** [gabrielbull/php-ups-api#39]
Hello,

how to create shipment after my order is successfully? and how I get tracking code?

Thanks,
Srinivasa Varma

**Comment by adnanhader** [comment]
Hello Varmad,
Actually there are so many issues in this API specially in shipment confirm requests. I have made lot of changes to make it work for me. However the code is not clean so I have not pushed it. Lot of new updates are there since I have downloaded that API. So it might not be possible for me to push that API changes now. However for a starting point this code might help you

$shipping = new Ups\Shipping($accesskey, $userid, $password, true);
        
        try {
            $shipment = new \Ups\Entity\Shipment();

            $shipper = $shipment->getShipper();
            $shipper->setShipperNumber(self::getShipperNumber());
            $shipper->setName('BUSINESS NAME');
            $shipperAddress = $shipment->getShipper()->getAddress();
            $shipperAddress->setPostalCode('BUSINESS ZIP');
            $shipperAddress->setAddressLine1('BUSINESS ADDRESS 1');
            $shipperAddress->setAddressLine2('BUSINESS ADDRESS 2');
            $shipperAddress->setCity('BUSINESS CITY');
            $shipperAddress->setStateProvinceCode('BUSINESS STATE');
            
            $address = new \Ups\Entity\Address();
            $address->setPostalCode('BUSINESS ZIP');
            $address->setAddressLine1('BUSINESS ADD 1');
            $address->setAddressLine2('BUSINESS ADD 2');
            $address->setCity('BUSINESS CITY');
            $address->setStateProvinceCode('BUSINESS STATE');
            $shipFrom = new \Ups\Entity\ShipFrom();
            $shipFrom->setAddress($address);
            $shipFrom->setCompanyName('BUSINESS NAME');
            $shipment->setShipFrom($shipFrom);
            $ship = $shipment->getShipFrom();
            $ship->CompanyName = 'BUSINESS NAME';
            

            $shipTo = $shipment->getShipTo();
            $shipTo->setAttentionName('FULL NAME');
            $shipTo->setReceivingAddressName('FULL NAME');
            $shipTo->setPhoneNumber('PHONE');
            $shipTo->setEmailAddress('EMAIL');
            $shipTo->setCompanyName('COMPANY NAME');
            $shipToAddress = $shipTo->getAddress();
            $shipToAddress->setPostalCode('12345');
            $shipToAddress->setAddressLine1('ADDRESS 1');
            $shipToAddress->setAddressLine2('ADDRESS 2');
            $shipToAddress->setCity('CITY');
            $shipToAddress->setStateProvinceCode('STATE');
            //residenial address indicator will increase the shipping rate
            if($residential_address) {
                  $shipToAddress->setResidentialAddressIndicator('TRUE');
            } 
            $shipment->setShipTo($shipTo);
            //Add package
            $package = new \Ups\Entity\Package();
            $package->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
            $package->getPackageWeight()->setWeight('WEIGHT');
            
            $dimensions = new \Ups\Entity\Dimensions();
            $dimensions->setHeight($height);
            $dimensions->setWidth($width);
            $dimensions->setLength($length);

            $unit = new \Ups\Entity\UnitOfMeasurement;
            $unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_IN);

            $dimensions->setUnitOfMeasurement($unit);
            $package->setDimensions($dimensions);
            $shipment->addPackage($package);

            $shipment->Service->Code = '03';
            
            $paymentInformation = new \Ups\Entity\PaymentInformation;
            $paymentInformation->Prepaid->BillShipper->AccountNumber = 'SHIPPER_NUMBER';
            $shipment->setPaymentInformation($paymentInformation);
            //This will create UPS shipment
            $result = $shipping->confirm('nonvalidate', $shipment);

            $shipment_charges = $result->ShipmentCharges->TotalCharges->MonetaryValue;
            $shipment_weight = $result->BillingWeight->Weight." ".$result->BillingWeight->UnitOfMeasurement->Code;
            $tracking_number = $result->ShipmentIdentificationNumber;
            $shipment_digest = $result->ShipmentDigest; //can be used to print labels
        } catch (Exception $e) {
            $error = $e->getMessage();
        }

Regards,
Adnan Haider

**Comment by stefandoorn** [comment]
@adnanhader Could you create a pull request for your changes? Then we can see what the resulting code would be. There are so many exceptions in the UPS API that not all are included. I can imagine nobody using this library ever had the need to ship dry ice, e.g. I'm currently implementing UPS and making changes now and then based on my specific requirements.

**Comment by adnanhader** [comment]
@stefandoorn but the code is not clean bro :-( should I create pull request as it is?

**Comment by stefandoorn** [comment]
@adnanhader That's ok, we can always discuss later if we can and how to refactor some things, if that's ok with you :) Or, where can I find your changes? I can also review them a bit without a pull request.

**Comment by adnanhader** [comment]
yeah that will be great. Can you give me your email address so I can send you an archive of API?

**Comment by stefandoorn** [comment]
Sure, mail@{myusernamehere}.nl. It's not in a repository somewhere where you can add me?

**Comment by adnanhader** [comment]
yes its in a bitbucket repository but my client is owner of that repo. So I am sorry I cannot add you in there. However I can create a new repo and can add you there on bitbucket? what you suggest?

**Comment by stefandoorn** [comment]
That's a good one. My username is the same in there as in here.

**Comment by adnanhader** [comment]
great. I am doing that mate :-)

**Comment by adnanhader** [comment]
Its done @stefandoorn. You are added there in repo as admin.

**Comment by stefandoorn** [comment]
I'm afraid this ain't easy to merge, @adnanhader ;-) I see some good changes, but no way to move code over easily. It would be awesome - as you know best what's changed - if you could pass over some of the improvements ofcourse in a pull request based on the current master branch :)

**Comment by adnanhader** [comment]
yes that's what I was afraid of that time. Right now I really don't have time for this. May be I will do it once I got a chance to work on it again. I am sorry for right now.

**Comment by stefandoorn** [comment]
@adnanhader Ok, thanks. Looking forward to some pull requests if you have the time :) I think many people will be happy with that.
