### ISSUE TITLE
How to show all shipping services in drop-down with price?

### ISSUE THREAD

**Issue by varmad** [gabrielbull/php-ups-api#40]
How to show all shipping services in drop-down with price?
Now it's default to UPS_GROUND

**Comment by stefandoorn** [comment]
Hi @varmad,

If you want to show all available options to your customer, I would suggest using the 'shopRates' option. From the documentation:

````
Rate = The server rates (The default rates if an option is not provided).
Shop = The server validates the shipment, and return rates for all UPS products from the ShipFrom to the ShipTo 
````

Example code can be found here: https://github.com/gabrielbull/php-ups-api#rate-class.

Swap out the 'getRate' function for 'shopRates' and you will get a result in which all the services are shown that can be used between the ShipFrom to the ShipTo addresses. 

If you want to use getRate, you might need to get all the options available and loop over them (hightly unrecommended), which could be done something like this:

`````
$services = \Ups\Entity\Service::getServices()
````

The keys consist of the service codes to use, the values consist of a user friendly name of that service.

Is this what you are looking for?

**Comment by varmad** [comment]
Yes, exactly am looking for this.
I used "shopRates" function getting following array format 

[0] => Ups\Entity\RatedShipment Object
                (
                    [Service] => Ups\Entity\Service Object
                        (
                            [Description] => 
                            [code:Ups\Entity\Service:private] => 03
                            [description:Ups\Entity\Service:private] => 
                        )

                    [RateShipmentWarning] => Your invoice may vary from the displayed reference rates
                    [BillingWeight] => Ups\Entity\BillingWeight Object
                        (
                            [UnitOfMeasurement] => Ups\Entity\UnitOfMeasurement Object
                                (
                                    [Code] => LBS
                                    [Description] => 
                                    [code:Ups\Entity\UnitOfMeasurement:private] => LBS
                                    [description:Ups\Entity\UnitOfMeasurement:private] => 
                                )

                            [Weight] => 7.0
                        )

                    [TransportationCharges] => Ups\Entity\Charges Object
                        (
                            [CurrencyCode] => USD
                            [MonetaryValue] => 8.77
                            [Code] => 
                            [Description] => 
                            [SubType] => 
                        )

                    [ServiceOptionsCharges] => Ups\Entity\Charges Object
                        (
                            [CurrencyCode] => USD
                            [MonetaryValue] => 0
                            [Code] => 
                            [Description] => 
                            [SubType] => 
                        )

                    [TotalCharges] => Ups\Entity\Charges Object
                        (
                            [CurrencyCode] => USD
                            [MonetaryValue] => 8.77
                            [Code] => 
                            [Description] => 
                            [SubType] => 
                        )

                    [GuaranteedDaysToDelivery] => 
                    [ScheduledDeliveryTime] => 
                    [RatedPackage] => Array
                        (
                            [0] => Ups\Entity\RatedPackage Object
                                (
                                    [Weight] => 7.0
                                    [BillingWeight] => Ups\Entity\BillingWeight Object
                                        (
                                            [UnitOfMeasurement] => Ups\Entity\UnitOfMeasurement Object
                                                (
                                                    [Code] => LBS
                                                    [Description] => 
                                                    [code:Ups\Entity\UnitOfMeasurement:private] => LBS
                                                    [description:Ups\Entity\UnitOfMeasurement:private] => 
                                                )

                                            [Weight] => 7.0
                                        )

                                    [TransportationCharges] => Ups\Entity\Charges Object
                                        (
                                            [CurrencyCode] => USD
                                            [MonetaryValue] => 8.77
                                            [Code] => 
                                            [Description] => 
                                            [SubType] => 
                                        )

                                    [ServiceOptionsCharges] => Ups\Entity\Charges Object
                                        (
                                            [CurrencyCode] => USD
                                            [MonetaryValue] => 0
                                            [Code] => 
                                            [Description] => 
                                            [SubType] => 
                                        )

                                    [TotalCharges] => Ups\Entity\Charges Object
                                        (
                                            [CurrencyCode] => USD
                                            [MonetaryValue] => 8.77
                                            [Code] => 
                                            [Description] => 
                                            [SubType] => 
                                        )

                                )

                        )

                    [SurCharges] => Array
                        (
                        )

                    [NegotiatedRates] => 
                )
from this how can I get shipping service code?

Thanks,
Varma

**Comment by stefandoorn** [comment]
Hi @varmad,

Something like this will do:

````
foreach($ratedShipments as $ratedShipment) {
    $code = $ratedShipment->Service->getCode();
    $name = $ratedShipment->Service->getName();
}
````

A good trick to find out these methods yourself is to look in the printed output above, where you see Ups\Entity\Service that has the service code. The accompanying file can be find in the package folder in src/Ups/Entity/Service.php, in where you see a `getCode` and a `getName` function. 

The same goes for the other objects in your output.

**Comment by varmad** [comment]
Yes, this is helpful thank you so much for the help.
