### ISSUE TITLE
Shipping weight > 150lbs...?

### ISSUE THREAD

**Issue by xtremevision** [gabrielbull/php-ups-api#44]
Hi,

Does the class handle weight > 150lbs? From what I understand, anything over 150lbs needs to use LTL or Freight, but I don't see any reference to that in the code.

Cheers,
Michael.

**Comment by stefandoorn** [comment]
Hi @xtremevision. The lib itself doesnt check weights. If you change the service code to one of your needs and the weight is too high, the API will definitely return an error telling you it. I haven't tried it. Looking at the API docs the API should be ok to use for Packages, LTL and Freight shipments. In the documentation although I don't find any references to these types.

Would you be able to try and if not look into creating a PR to make it work?

**Comment by xtremevision** [comment]
Hi @stefandoorn,

Mmm... I am not sure myself to be honest. Their documentation is extremely bad, and the only reference I found, including their Rating api kit, is for the Freight Web Service API (soap), which is obviously completely different than the xml api.

I will let you know if I find anything useful.

Cheers,
Michael.

**Comment by stefandoorn** [comment]
Hm, I see now indeed. Doesnt look like the regular packages shipping API at all. They do have API support, to it might be worth trying them to find the best answer to your question. I'm looking forward to anything you find :)

**Comment by xtremevision** [comment]
Indeed, and it worries me because one shipment could have mixed items, like 1-2 small packages, and 1-2 very heavy items. That would mean using two different apis for rates...? Not to mention the Freight api has different packaging types, e.g. bags, pallets, etc....

**Comment by stefandoorn** [comment]
Sounds like an interesting challenge ;-) What I did myself was using a bin packing module first to calculate and identify the packages (small, big, weight, etc.). I only needed simple Package shipments, but this way you can split them in separate requests and combine them. I can imagine it gets harder if you also need to use TimeInTransit and show clients the expected delivery moment etc. Unfortunately I can't help you too much on this as I haven't used any Freight shipments yet.

**Comment by stefandoorn** [comment]
@xtremevision: did you find a solution?

**Comment by xtremevision** [comment]
Hi,

Sorry, not yet, have not had any time to play with it, too busy with 
other stuff. We've spoken numerous times to UPS and they confirmed that 
for orders > 150lbs we need to use the freight api, so we're waiting for 
them to activate freight on the account.

Cheers,
Mike.

On 06/08/2015 12:37, Stefan Doorn wrote:
>
> @xtremevision <https://github.com/xtremevision>: did you find a solution?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gabrielbull/php-ups-api/issues/44#issuecomment-128309411>.
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201
Reg Com: J40/23/03.01.2012
CUI: RO29505826

**Comment by stefandoorn** [comment]
@xtremevision Alright. I will close this one for now.

**Comment by scufa** [comment]
I've got my Freight account activated. They provide only SOAP interface for this API.
You can read more in the Rating Ground Freight - Web Services Developers Guide.pdf document from their dev website.

**Comment by xtremevision** [comment]
So you concur with me that you have to use two separate apis, xml for 
small packages, and soap for freight, right?

On 18/08/2015 16:16, scufa wrote:
>
> I've got my Freight account activated. They provide only SOAP 
> interface for this API.
> You can read more in the Rating Ground Freight - Web Services 
> Developers Guide.pdf document from their dev website.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gabrielbull/php-ups-api/issues/44#issuecomment-132201747>.
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201
Reg Com: J40/23/03.01.2012
CUI: RO29505826

**Comment by xtremevision** [comment]
ps. I've already got all their guides, but I find them extremely 
difficult to read and quite lacking...

On 18/08/2015 16:16, scufa wrote:
>
> I've got my Freight account activated. They provide only SOAP 
> interface for this API.
> You can read more in the Rating Ground Freight - Web Services 
> Developers Guide.pdf document from their dev website.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gabrielbull/php-ups-api/issues/44#issuecomment-132201747>.
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201
Reg Com: J40/23/03.01.2012
CUI: RO29505826

**Comment by scufa** [comment]
Yes, I do it this way. For weights < 150 lbs I use the php-ups-api code. For weights > 150 lbs I use SOAP client. Different APIs, different keys.

**Comment by xtremevision** [comment]
Ok.

On 18/08/2015 16:29, scufa wrote:
>
> Yes, I do it this way. For weights < 150 lbs I use the php-ups-api 
> code. For weights > 150 lbs I use SOAP client. Different APIs, 
> different keys.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gabrielbull/php-ups-api/issues/44#issuecomment-132205413>.
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201
Reg Com: J40/23/03.01.2012
CUI: RO29505826

**Comment by stefandoorn** [comment]
@xtremevision could you contact me at mail @ {myusername} . nl ?

**Comment by xtremevision** [comment]
Hi Stefan, I've sent you an email to you address... let me know if you 
got it... Mike.

On 18/08/2015 16:42, Stefan Doorn wrote:
>
> @xtremevision <https://github.com/xtremevision> could you contact me 
> at mail @ {myusername} . nl ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gabrielbull/php-ups-api/issues/44#issuecomment-132211121>.
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201
Reg Com: J40/23/03.01.2012
CUI: RO29505826

**Comment by harshsanghani** [comment]
> Yes, I do it this way. For weights < 150 lbs I use the php-ups-api code. For weights > 150 lbs I use SOAP client. Different APIs, different keys.

I am facing same issue, Can you please show me your code, So I can fix this in my website also.

**Comment by sergey-nechaev** [comment]
> > Yes, I do it this way. For weights < 150 lbs I use the php-ups-api code. For weights > 150 lbs I use SOAP client. Different APIs, different keys.
> 
> I am facing same issue, Can you please show me your code, So I can fix this in my website also.

I don't have the code now, but you got the idea. Not sure if it's still actual.
