### ISSUE TITLE
Are services for domestic shipping within Sweden also here?

### ISSUE THREAD

**Issue by pacid** [gabrielbull/php-ups-api#50]
Hi,
I come across methods for Sweden:
http://www.ups.com/content/se/sv/shipping/time/service/index.html?WT.svl=SubNav
UPS Express Plus
UPS Express
UPS Express Saver

But In here I've found those:
EXPRESS (75)
EXPRESSPLUS (54)
NEXTDAYAIRSAVER (13)

Naming similar but not quite, I'm not sure about NEXTDAYAIRSAVER - seems it's US only. 
Is there any info as to whether I can use it for a company based in Sweden as well?
Which service are you using in order to get the list of tranportation services?
Thank you!

**Comment by stefandoorn** [comment]
Hi @pacid, I'm using this service mainly for a client in The Netherlands, facing kind of the same problem. I manually figured out using the API documentation (Shipping API Webservices XML) what are the USA codes and what are the same Netherlands codes, to make a mapping of them whenever I need it, but: in my situation it seems okay to use the USA codes in the Rating API, plus in the Shipping API. 

When using the Time In Transit API you will get other codes returned which you cannot map with the Rating/Shipping API. UPS also doesn't have a mapping list, so I created my own in my code.

Scenario I'm using:
* Use Rating API to get rates & codes
* Use Time In Transit API to get transit times and map them with service codes from previous call (manual)
* Use Shipping API to save the shipment with UPS

The service codes in the code are mainly shortcuts to make it easier, but don't reflect the full names as they can also change over time from UPS marketing.

Does this help you?

**Comment by eduard-sukharev** [comment]
@pacid According to docs from 13th of July 2015, there're at least 3 "savers" available:
`13 = Next Day Air Saver`, `65 = UPS Saver` and `86 = UPS Today Express Saver`. Which of them might suit you better is up to you, as stated by @stefandoorn they're only const's for convenience. Adding the missing const via PR should be welcome :)

**Comment by stefandoorn** [comment]
True, but e.g. in NL 13 is not available, so is 86. I have 65, plus UPS Standard (11?) and some other less used ones (2 options) depending on location to ship to.

**Comment by pacid** [comment]
Thank you for your answers. The problem I have is that I might use the wrong method and therfore the rates are completely different, also this could be not available for my clients in some web panel. Is there really not some piece of documentations that lists the services for given countries? 
I wouldn't be surprised if there wasn't or if the support didn't have idea about cause I've been dealing with fedex recently ;). But still.. how to be sure?

**Comment by stefandoorn** [comment]
@pacid Easiest is to test first with UPS Standard, it should be available everywhere. It could also be your client uses Negotiated Rates, so be sure to activate that if it's necessary. The integration API can also display wrong prices due to client settings on UPS side, so then try the live API with the Rating API e.g.

In the Shipping API XML Webservices documentation there is an appendix showing services per country to other countries of same country. So you should get an idea of options there, also if you try the Rating API with a common address you should get all the possible services available. E.g. address in Stockholm to other address in Stockholm.

**Comment by pacid** [comment]
@stefandoorn Actually the domestic ones for Sweden are just fine (just don't know if UPS WORLDWIDE SAVER is the same as UPS Express Saver)
But can't get any results for **UPS Worldwide Express Freight** now (shipping SE->PL now which WORKS using web interface to check for services available - https://wwwapps.ups.com/ctc/request). Any additional settings for that. Anyone?

**Comment by pacid** [comment]
Aha! Could be that the UPS Freight Rating API is not available in Sweden :) ![image](https://cloud.githubusercontent.com/assets/1618052/9763136/2ad45790-5708-11e5-99a2-61c8e3944b50.png)

But it strangle comes up in web results somehow. I'm confused how is automation in web based businesses work then, cause it IS available for Sweden (according to http://www.ups.com/content/se/sv/shipping/time/service/shipping/index.html)

**Comment by stefandoorn** [comment]
According to https://www.ups.com/upsdeveloperkit it should be available, but the problem might be that the Rate API this package has is connected to the Packages Rating API, and not the Freight Rating API.  I believe that is different API, also when I open the XML Documentation I have a file regarding Freight API and a file regarding Package API.

Ofcourse we are open to Pull Requests to also cover the Freight Rating API :) Part can be probably be the same as the Package Rate API, but there are some differences..

**Comment by stefandoorn** [comment]
@pacid Did you manage in the meanwhile?
