### ISSUE TITLE
Specify Residential vs Business

### ISSUE THREAD

**Issue by mattpramschufer** [gabrielbull/php-ups-api#54]
Is there a way to specify a residential address vs a business address in the getRate function?

I am assuming it would be some flag to set in

```
$shipTo = $shipment->getShipTo();
$shipTo->setCompanyName('Test Ship To');
$shipToAddress = $shipTo->getAddress();
$shipToAddress->setPostalCode($inputs['shippingZip']);
```

Any help would be greatly appreciated!

**Comment by stefandoorn** [comment]
@mattpramschufer You need to use the residentialAddressIndicator on the Address class to get that working. 

So something like this:
````
$shipToAddress = $shipTo->getAddress();
$shipToAddress->setResidentialAddressIndicator(true);
$shipTo->setAddress($shipToAddress);
````

**Comment by mattpramschufer** [comment]
Awesome thank you so much!
