### ISSUE TITLE
Composer update not showing any update?

### ISSUE THREAD

**Issue by ankitsam** [gabrielbull/php-ups-api#60]
Composer update not showing any update.
Also, package weight unit Ounce is missing in UnitOfMeasurement class.

**Comment by stefandoorn** [comment]
@ankitsam I'm getting an update to 0.6. How does your composer version string look?

Regarding UnitOfMeasurement: would you be willing to create a PR for it?

**Comment by ankitsam** [comment]
Yes, changing version in composer from "0.2.*" to "dev-master" fixed it.
Official SDK docs only lists two valid values, so i think its fine.
But invoice showed 3 , K,L,O, so i thought. 
You can close this issue.
Thanks

**Comment by stefandoorn** [comment]
Hi @ankitsam, perfect. I would advice using something like '^0.6' as constraint, so you only get releases from 0.6 and up until 1.0. We dont want a bogus commit to ruin your system :)

I will close the issue, you are still welcome ofcourse to add Ounce.
