### ISSUE TITLE
Identifying a Package or Shipment to Track by Reference Numbers

### ISSUE THREAD

**Issue by rafacuest** [gabrielbull/php-ups-api#62]
Acording to UPS api documentation pag 30  section 

1.7.1.3 Reference Numbers  

you can Identifying a Package or Shipment to Track by a free tag called Reference Numbers the xml   request field is:
\<ReferenceNumber\>
  \<Value\> xxxxxxxxxxxxxxxx \</Value\>
\</ReferenceNumber\>

**Comment by stefandoorn** [comment]
Lets continue discussion in #63.
