### ISSUE TITLE
Failure: Invalid Access License number (250003)

### ISSUE THREAD

**Issue by hm122** [gabrielbull/php-ups-api#65]
Hi! Thanks for this great lib! Unfortunately I am not able to get it running. I tried out the address validation example, but always getting:

Failure: Invalid Access License number (250003)

Do you have any idea what could be the issue?

Thanks!

**Comment by stefandoorn** [comment]
Hi @hm122, assuming you have UPS credentials, it could be that you are not authorized for that specific API. I'm having the same trouble, trying to use that validation service from EU, while it is only available to US accounts it seems. There is another validation service, which we don't support yet, but that one is available to EU customers. It only doesn't provide street level validation, only at a higher level. We would be happy ofcourse for PR's adding that functionality :)

**Comment by hm122** [comment]
Hi Stefan! Thanks for the fast answer! I have now tried out the Tracking and Locator examples and still getting the same error. So there is probably a problem with the credentials? Access Key should be okay, for the userId/password I am using those which I use to login at the ups web login.

**Comment by stefandoorn** [comment]
Hi @hm122, that should be fine, but at UPS side they have to enable the API's also in my believe. Did you have one working at all or not? If not I think it's best to contact your UPS representative about it to activate things.

**Comment by hm122** [comment]
No, at the moment none of the APIs are working. So I will try to contact UPS directly. Thanks for the help!

**Comment by stefandoorn** [comment]
@hm122 Any success?

**Comment by hm122** [comment]
It seems like it is working now! Thanks for your help!  
Another question: Since the documentation for the shipping class is missing atm, do you have any examples or tests we can use as a reference? Thanks!

**Comment by stefandoorn** [comment]
Great :)

Maybe #61 helps you on the way, it's indeed missing even though it would be helpful to have it. Does this help you on the right track? Ofcourse a PR is very welcomed with some documentation ;-)

**Comment by hm122** [comment]
Alright! Thanks again, that really helped! Is it also possible to delete a shipment?

**Comment by stefandoorn** [comment]
Yep, then you have to use the void function :) Only note that that's only possible before sending it really to UPS. And, it wont work on the integration URLs as your shipments are not saved in there. I think the documentation has fake IDs you can use for it.

**Comment by hm122** [comment]
Great! You really saved my day(s)! :) I have a last question, which is regarding shipments with cash on delivery. According to the documentation, the COD Amount should be set within the ShipmentServiceOptions. But in the class those attributes aren't present - or am I missing something? 
I will send you my fully working example when I am done, so you can add it to the documentation! :)

**Comment by stefandoorn** [comment]
Not sure about how that should be, it could be that it aint implemented in the Shipping class at this moment due to nobody having the need to - eg I didn't need it. In that case you could make a PR if you want with the feature added that you need based on UPS docs :) + documentation ;) I'm happy to help you if you need ofcourse.

**Comment by hm122** [comment]
Ok, the ShipmentServiceOptions class (and COD/CODAmount class) needs to be adjusted in order to support cash on delivery. It's working now and I will make a PR asap. Thanks!

**Comment by stefandoorn** [comment]
Perfect, thanks!

**Comment by braydentraas** [comment]
> It seems like it is working now! Thanks for your help!
> Another question: Since the documentation for the shipping class is missing atm, do you have any examples or tests we can use as a reference? Thanks!

Hi @hm122, I'm having the same issue. Did you have to contact UPS to enable anything?

**Comment by jonne1993** [comment]
> > It seems like it is working now! Thanks for your help!
> > Another question: Since the documentation for the shipping class is missing atm, do you have any examples or tests we can use as a reference? Thanks!
> 
> Hi @hm122, I'm having the same issue. Did you have to contact UPS to enable anything?

 I'm having the same issue with you. Did you fix the problem?
