### ISSUE TITLE
How to add a second Reference to shippment?

### ISSUE THREAD

**Issue by ConvarDeutschland** [gabrielbull/php-ups-api#69]
Hi,
I use this code in my shippment to add a reference

<pre>$referencenumber=new ReferenceNumber;
$referencenumber->setValue($strPackageRef1);
$referencenumber->setBarCodeIndicator(true);
$shipment->setReferenceNumber($referencenumber);
</pre>

This is shown as "Reference No.1:" on the label.

But how to add a second reference ? to have "Reference No.2:" on the label?

CU Online

**Comment by hm122** [comment]
Hi,

I also need two reference numbers and just made a pull request for that feature
https://github.com/gabrielbull/php-ups-api/pull/70

cheers

**Comment by stefandoorn** [comment]
Release 0.7.1 adds this feature. See #70.
