### ISSUE TITLE
How to manage InvalidResponseException 

### ISSUE THREAD

**Issue by ConvarDeutschland** [gabrielbull/php-ups-api#71]
Hello, 

We use the return service for UPS in different countries. Sometimes we have cases where the standard service can not be use from Origin to Destination. In this case an InvalidResponseException is returned.
But this can in most of the cases be solved by switching from

<pre>InvalidResponseException in Request.php line 131:
Failure: The selected service is not available from the origin to the destination. (121210)</pre>

How can I catch this error and return a page to the customer with the given error Message ?
Because this is not really an exception it's a standard UPS error that is returned.

**Comment by stefandoorn** [comment]
I think you can try something like this:

````
try {
    $response = $api->...
} catch (InvalidResponseException $e) {
    if($e->getCode() == 121210) { 
         // Show message..
    }
    else {
        throw new Exception($e->getMessage(), $e->getCode(), $e);
    }
}
````

You can catch the Exception and define what you want to happen when it occurs. Ofcourse this is not working code, but it should give you a start in the right direction.
