### ISSUE TITLE
Set node value for entity RateInformation

### ISSUE THREAD

**Issue by p0lym0rphik** [gabrielbull/php-ups-api#72]
Hi
It seems that nodeValue is not set is toNode function of the RateInformation entity.
Second parameter of createElement is not set.

Patch example :

````
$negociatedRatesIndicator = $this->getNegotiatedRatesIndicator();
if ($this->getNegotiatedRatesIndicator()) {
    $node->appendChild($document->createElement('NegotiatedRatesIndicator', $negociatedRatesIndicator));
}

````

**Comment by stefandoorn** [comment]
Hi @p0lym0rphik 

I don't fully understand you I think. For the NegotiatedRatesIndicator it is enough to be present, no value needs to be present in the XML, so this is enough in the output: <NegotiatedRatesIndicator />

**Comment by p0lym0rphik** [comment]
Hi @stefandoorn !
I'm currently in touch with an UPS tech which set the value to Y. Maybe this change nothing but negociated rates response was empty. It seems that it could also be a missing Shipper Address object which trigger this bug. In this case maybe throwing an exception could prevent this.

**Comment by stefandoorn** [comment]
The docs state no value is necessary if I'm right. I have it working atleast with the current code. I do add a Shipper object, but I'm not sure that's required. But also be sure to check the XML Webservices documentation. It's big, but it includes nearly everything :)

**Comment by p0lym0rphik** [comment]
A teammate did the the test with and without the Shipper Address Object and this was relevant.
I don't no why exactly but specify it did the trick !
Thanks you for taking the time to answer ;), and thank you for the work here !

**Comment by stefandoorn** [comment]
Perfect! It could be that the right rates only work with the right shipper indeed. Not totally sure, but nice that it works :)
