### ISSUE TITLE
Shipping class

### ISSUE THREAD

**Issue by idoadiv** [gabrielbull/php-ups-api#76]
Is there any problem with it or it is ready to use but not documented?

Can someone please provide sample code if it is safe to use?

Thank you.

**Comment by stefandoorn** [comment]
@idoadiv I think #61 will get you started. It's ready to be used, but not all features are in it (but most are, for the exceptions we are open for PR's ofcourse) and documentation is missing. If you are willing, ofcourse we are also open to a documentation PR :)
