### ISSUE TITLE
Address Validation Missing Data

### ISSUE THREAD

**Issue by adear11** [gabrielbull/php-ups-api#77]
Hi,

When I attempt to do address validation on an ambiguous address, the response is only being returned with one of the, what I know to be, three suggested addresses. 

As an example:
```PHP
$address = new Address();
$address->setAddressLine1("1902 stonebridge blvd");
$address->setCity("ALPHARETTA");
$address->setStateProvinceCode('GA');
$address->setCountryCode('US');
$address->setPostalCode('30005');
```
I expect to get back a response with 3 suggested addresses from the `AddressKeyFormat` property of the response. However, I'm only being returned the first element in the array.

When I dump the response prior to `->convertXmlObject` on Line 186 I get this Object:
```
SimpleXMLElement {#797 ▼
  +"Response": SimpleXMLElement {#786 ▶}
  +"AmbiguousAddressIndicator": SimpleXMLElement {#785}
  +"AddressClassification": SimpleXMLElement {#776 ▼
    +"Code": "0"
    +"Description": "Unknown"
  }
  +"AddressKeyFormat": array:3 [▼
    0 => SimpleXMLElement {#775 ▼
      +"AddressClassification": SimpleXMLElement {#767 ▼
        +"Code": "0"
        +"Description": "Unknown"
      }
      +"AddressLine": "400-498 STAMBRIDGE CT"
      +"Region": "ALPHARETTA GA 30005-2567"
      +"PoliticalDivision2": "ALPHARETTA"
      +"PoliticalDivision1": "GA"
      +"PostcodePrimaryLow": "30005"
      +"PostcodeExtendedLow": "2567"
      +"CountryCode": "US"
    }
    1 => SimpleXMLElement {#774 ▼
      +"AddressClassification": SimpleXMLElement {#782 ▼
        +"Code": "0"
        +"Description": "Unknown"
      }
      +"AddressLine": "401-499 STAMBRIDGE CT"
      +"Region": "ALPHARETTA GA 30005-2565"
      +"PoliticalDivision2": "ALPHARETTA"
      +"PoliticalDivision1": "GA"
      +"PostcodePrimaryLow": "30005"
      +"PostcodeExtendedLow": "2565"
      +"CountryCode": "US"
    }
    2 => SimpleXMLElement {#772 ▼
      +"AddressClassification": SimpleXMLElement {#783 ▼
        +"Code": "0"
        +"Description": "Unknown"
      }
      +"AddressLine": "500-599 STAMBRIDGE CT"
      +"Region": "ALPHARETTA GA 30005-2568"
      +"PoliticalDivision2": "ALPHARETTA"
      +"PoliticalDivision1": "GA"
      +"PostcodePrimaryLow": "30005"
      +"PostcodeExtendedLow": "2568"
      +"CountryCode": "US"
    }
  ]
}
```

However, what is actually returned from the `convertXmlObject()` method is:
```
{#784 ▼
  +"AddressClassification": {#781 ▼
    +"Code": "0"
    +"Description": "Unknown"
  }
  +"AddressLine": "400-498 STAMBRIDGE CT"
  +"Region": "ALPHARETTA GA 30005-2567"
  +"PoliticalDivision2": "ALPHARETTA"
  +"PoliticalDivision1": "GA"
  +"PostcodePrimaryLow": "30005"
  +"PostcodeExtendedLow": "2567"
  +"CountryCode": "US"
}
```

So, all that said, is there a reason to know return the full response as an array? Instead of doing this `return $this->convertXmlObject($response->AddressKeyFormat);` can you not do this `return $this->convertXmlObject($response);`? This returns the full context of the response. 

An additional problem this would solve is in the case of an address that is so badly formatted that UPS is unable to even find a suggestion. Using the above address as an example, If I make the same call but without including the street address (so I'm just sending city, state, zip, and country), the actually response is:
```
SimpleXMLElement {#797 ▼
  +"Response": SimpleXMLElement {#786 ▶}
  +"NoCandidatesIndicator": SimpleXMLElement {#785}
  +"AddressClassification": SimpleXMLElement {#776 ▼
    +"Code": "0"
    +"Description": "Unknown"
  }
}
```
What is returned from this is an empty object that contains no properties
```
{#768}
```
That empty object is extraordinarily unhelpful.

So, that is a long way to say, is it possible to return the full response instead of just the tiny subset?

**Comment by stefandoorn** [comment]
The suggested change would introduce backwards incompatibility, but what we could do is adding an extra parameter to the validate() function and adding support to return the full response. Looking at the code I find it weird that you only get the first item in the AddressKeyFormat, I think it's intended to return all suggestions, but I'm not 100% sure about that right now. 

We are open to PR's, so if you are willing to make one with the proposed features, great. I can think of either an extra parameter or an extra method that does validation and returns the full body response, or something like that.

**Comment by adear11** [comment]
I'm more than happy to have a go a fixing this. But before I go to far with it, I need to know what approach to take.

I think the current behavior is caused by the call to `$this->convertXmlObject($response->AddressKeyFormat);` passing some kind of iterator or traversable that json_encode isn't properly recursing over (I'm not familiar enough with PHP internals to say for sure or to cast blame).

I can easily fix this to return an array that contains all of the address options, but I think, as you said, changing the behavior to the 'intended' behavior would technically be a BC break. 

I almost wonder if the 'better' solution isn't to wrap the current response in a new 'AddressValidationResponse` that will allow you to query different parts of the response. A custom response would let me do things like `$response->isAmbiguous()` or `$response->isValid()'. Then either add an optional parameter to the `validate()` method or set a flag on `AddressValidation` class to return the new Response type to maintain BC.

Thoughts?

**Comment by stefandoorn** [comment]
My personal preference is introducing a new method that does your proposed solution. So we leave validate() work as it does now, as it will break things else. Next to that you introduce a method, eg. validateExtendedInfo() or something like that :) Naming is hard but you will probably find something great, and then do as proposed in there. A separate method gives a clear API, just switches as arguments is often a bit unclear for users as its harder to discover.

**Comment by adear11** [comment]
I agree. So I'll implement a new method that will return a new AddressValidationResponse object that wraps the existing response and adds some new methods to allow query the response so that I don't necessarily have to know the exact name of the XML elements returned by the API.

**Comment by adear11** [comment]
PR #80 created.

I welcome your comments.

**Comment by stefandoorn** [comment]
PR is merged.
