### ISSUE TITLE
Failure: Invalid tracking number (150022)

### ISSUE THREAD

**Issue by pocketmax** [gabrielbull/php-ups-api#78]
When I try to use your api I get this error with valid tracking numbers. From what I can tell, your api looks good. Have there been any changes to the UPS api service lately that could break your API?

```php
<?php
date_default_timezone_set('America/Phoenix');
require_once('vendor/autoload.php');

$accessKey="secret";
$userId="secret";
$password="secret";

$tracking = new \Ups\Tracking($accessKey, $userId, $password, true);

try {
    $shipment = $tracking->track('I_USED_A_VALID_TRACKING_NUMBER_HERE');

    foreach($shipment->Package->Activity as $activity) {

        var_dump($activity);
    }

} catch (Exception $e) {
    echo "exception thrown";
    var_dump($e);
}
```

**Comment by stefandoorn** [comment]
How did you register the code? My code didn't break recently :) This code above is meant to use the real identification number UPS supplies, but if you want to use a reference number supplied on creating of the shipment (e.g. order number) you might want to look into issue #63. There is an option to use tracking by reference numbers but we only added it later.

**Comment by pocketmax** [comment]
What do you mean by "register the code"? I did a "composer require gabrielbull/ups-api && composer install", then I ran my test script. Also, I'm using a UPS innovations real tracking number, not a test one.

**Comment by stefandoorn** [comment]
Actually I meant how you register the shipment indeed. What does the identification number look like? 

But, maybe the problem lies in the fourth parameter (true) you are using. That is enabling the integration mode, which does not connect with UPS live system but with a development environment. Your registered shipping won't be available in there.

**Comment by pocketmax** [comment]
I tried it without the 4th parameter and it still didn't work. The UPS innovation tracking numbers I use look like this 9274844448416401323758. How do I use your lib to switch between live and dev UPS apis?

**Comment by stefandoorn** [comment]
I find that weird looking actually from my perspective. I only have tracking numbers in the form of 1Z...... Also 'UPS Innovation' doesn't ring a lot of bells in here. I have the impression that is mail (letters) instead of packages.. This Tracking API is this one: https://www.ups.com/content/us/en/tracking/tools/

**Comment by pocketmax** [comment]
Your docs mention "Optional processing. For Mail Innovations the only valid options are Last Activity and All activity." I was assuming Mail Innovations was UPS innovations and your api supported UPS innovations tracking numbers.

**Comment by stefandoorn** [comment]
Checked docs from here (https://www.ups.com/upsdeveloperkit/downloadresource?loc=en_US). I have the impression only ReferenceNumber option is possible, not the normal tracking by identification number. So you need the trackByReference method and supply the reference number supplied when you create the shipment. Hopefully that works..

**Comment by pocketmax** [comment]
when I use the trackByReference method, I get "Failure: No tracking information available (151044)" which tells me I'm getting closer. I think I'm hitting the test API. Is there a config option for your driver that allows me to toggle which api to use (dev or prod)? Or pass a custom url for it to use?

p.s. Thanks for all your help on this. I really appreciate it.

**Comment by stefandoorn** [comment]
Yep, the fourth argument on the line with 'new Ups\Tracking' means whether to use integration or not. True = integration, false = production. 

Be sure also to use the reference number, not the shipping number provided from UPS.

**Comment by pocketmax** [comment]
oh, so "integration" is there test API, correct?

**Comment by stefandoorn** [comment]
Yep!

**Comment by pocketmax** [comment]
is there a way to var dump the complete XML request doc and complete XML response doc?

**Comment by stefandoorn** [comment]
Yes. You can temporary adjust the request class, but that ain't a proper method. Best is to look at the logging part of the readme. It allows you to save request and response to a log file for easy access :-)

**Comment by pocketmax** [comment]
Thank you for the debugging help. I emailed the request xml to UPS dev support and they said I was missing the <IncludeMailInnovationIndicator/> xml tag in my <TrackRequest></TrackRequest> xml block. I did a quick test with curl adding the XML tag and they were right, it worked. I did a case insensitive search on your code and couldn't find the missing tag so I'm assuming the code isn't aware of a need to add the tag. Is there a way for me to polyfill or "pre patch" the request XML with the needed tag before it's sent to UPS?

-Thanks

**Comment by stefandoorn** [comment]
Not sure what tag is missing, can you provide an example? Else we are ofcourse open to a Pull Request to add this feature, so others have it available directly in the future.

**Comment by pocketmax** [comment]
This is what I got from UPS dev support...

> Thank you for this reply. Unlike your first request, this one is missing the Include Mail Innovation Indicator. 
> 
> If you add this the element the request will work in the test or production servers. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<AccessRequest xml:lang="en-US">
<AccessLicenseNumber>444444SECRET4444</AccessLicenseNumber>
<UserId>SECRET</UserId>
<Password>SECRET</Password>
</AccessRequest>
<?xml version="1.0" encoding="UTF-8"?>
<TrackRequest xml:lang="en-US">
<IncludeMailInnovationIndicator/>
<Request>
<TransactionReference/>
<RequestAction>Track</RequestAction>
<RequestOption>activity</RequestOption>
</Request>
<TrackingNumber>92748999SECRET03860</TrackingNumber>
</TrackRequest>
```

**Comment by pocketmax** [comment]
if this is legit, I would love to do a pull request. It would be a nerd honor of mine to contribute to your lib.

**Comment by stefandoorn** [comment]
It looks good. We don't support that right now. I think we could add an optional argument which could activate this feature. A PR for this would be great :) If you could also adjust the docs for it (and maybe unit tests), even greater.

**Comment by pocketmax** [comment]
sweet. I know what I'll be working on this weekend! :)
