### ISSUE TITLE
How to use Rate API with freight class instead of dimensions?

### ISSUE THREAD

**Issue by straube** [gabrielbull/php-ups-api#79]
I'm trying to use Rate API class with freight class instead of dimensions (H x W x L). I checked a couple classes' source code, but I couldn't find how to do that. Is that possible at all?

**Comment by stefandoorn** [comment]
If I check the Rating API from UPS I see:

> This guide applies to the following API:
> • Rating Package XML API
> This guide does not apply to the following APIs:
> • Rating Package Web Service API
> • Any API for Ground Freight or Air Freight

Not sure if you are really trying to use Freight shipments (that's huge shipments on a pallet etc), maybe I'm mistaking your question. It's mainly used for small packages with a weight / dimensions. Could you elaborate on your needs?

**Comment by straube** [comment]
If I'm not wrong, freight classes are related to LTL. Maybe the API docs I'm checking is not exactly related to your implementation. I see the following at the developer kit page related to Rating API:

> The Rating API allows applications to look up and compare rates for UPS services:
> - Package
> - Less-than-Truckload (LTL)

Go to https://www.ups.com/upsdeveloperkit/downloadresource?loc=en_US, and click on **Rating** (sorry, but there is no direct link to this page).

BTW, thanks for the fast response.

**Comment by stefandoorn** [comment]
I actually checked that link for the docs. Weird thing is that in that docs I found my quote. So I'm a bit in doubt how to make it work. I feel we don't support it right now, but if the XML guide in that link shows how to do it, we could implement it ofcourse (we are open to PR's also ofcourse) or find a way to make it work with the current code.

**Comment by straube** [comment]
I don't want to bother you with this specific function. I just wanted to check if there was a way to do that with your current implementation. Probably I'll fork your project and update it to support that. When I have it done, I open a PR.

**Comment by stefandoorn** [comment]
Great! Looking forward to it :-) And feel free to bump a question. I'm always willing to have a look :-)

**Comment by stefandoorn** [comment]
I haven't had to use this API ever, so haven't worked on adding it to the library. The library doesn't support it right now, but we are open to PR's of course :-)
