### ISSUE TITLE
How to set unit for weight in package

### ISSUE THREAD

**Issue by lchhieu** [gabrielbull/php-ups-api#83]
$package = new \Ups\Entity\Package();
$package->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
$package->getPackageWeight()->setWeight(10);
//set unit kilogam for package

**Comment by stefandoorn** [comment]
I use it like this:

```
            // Set weight of packages
            $package = new \Ups\Entity\Package();
            $package->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
            $package->getPackageWeight()->setWeight($weight);
            $unit = new \Ups\Entity\UnitOfMeasurement;
            $unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_KGS);
            $package->getPackageWeight()->setUnitOfMeasurement($unit);
```

**Comment by stefandoorn** [comment]
I don't understand your question unfortunately.

**Comment by lchhieu** [comment]
ah.
i want check money return from using package of you with from ups is correct , no difference.
Exaple: package is $3 but reality from UPS is $3

**Comment by stefandoorn** [comment]
Sorry, still don't get the question. $3 == $3 doesn't make a lot of sense to me.

**Comment by lchhieu** [comment]
Example: package UPS of you return is 3 USD but reality from UPS.com is 3.1 USD.

**Comment by stefandoorn** [comment]
Ah ok. Might be a rounding issue? I don't know exactly how it goes, as in my code it goes perfectly. Do you have a code example + returned XML + the parsed result? Might take a look in the code, maybe we have a bug.

**Comment by lchhieu** [comment]
Sorry @stefandoorn . I live in Vietnam, i try many time 1 address of my but not success.
I know UPS have support in Vietnam
This is address of my:
[country] => Vietnam
    [province] => Hồ Chí Minh
    [city] => Ho Chi Minh City
    [street] => 48 Trần Văn Đang
    [zipcode] => 70000 
    [country_code] => VN
    [address] => 48 Trần Văn Đang, phường 11, Quận 3, Hồ Chí Minh, Vietnam

**Comment by lchhieu** [comment]
And time that I get results quite long, sometimes up to 30 seconds. And you

**Comment by stefandoorn** [comment]
No, it's quite fast in here.

What I need:
* Result object (from Response.php) with the results
* Result object from the Shipping class to see how it's formatted

We need to see what UPS returns and what the class returns afterwards. I can't debug anything right now.

**Comment by lchhieu** [comment]
thanks. hope you can update the **document Shipping**. Currently I use to **_validation_** and **_rate_** for get rate.

This is website that i using api ups of you. http://aquaponic.kennjdemo.com
This is slow in _validate Address of customer_

**Comment by stefandoorn** [comment]
Shipping documentation can be found here: #61. Still need to put it in readme.

**Comment by lchhieu** [comment]
annoys you, you can check address your help. 
I fear that the result is not right

+ address to: 310 S Federal St, Chicago, IL 60604, USA	
+ address from: 833 N 13th St, Decatur, IN ,US	
--> this is rate ship that i get from check get rate: $ 15.31
-----------------------------------------------------------------
+ address to: 310 S Federal St, Chicago, IL 60604, USA
+ address from: 301 S Bowman Rd, Little Rock, AR ,US
--> this is rate ship that i get from check get rate: $ 20.94

Thank you. I want to know from you the same results of me.

**Comment by stefandoorn** [comment]
I honestly don't understand your English. To get a rate you just supply info in the request that you have, without address. If it works, that's nice. If it doesn't work, an error will be shown so you know how to fix it.
