### ISSUE TITLE
PoliticalDivision1 and PoliticalDivision2 are mismatched

### ISSUE THREAD

**Issue by beaudierman** [gabrielbull/php-ups-api#85]
I've had some issues with address validation almost always returning 0 or "Unknown" for addresses that I know are defined as commercial.  After some digging around, I've found that in AddressValidation.php

```
if ($this->address->getStateProvinceCode()) {
    $addressNode->appendChild($xml->createElement('PoliticalDivision2',
        $this->address->getStateProvinceCode()));
}
if ($this->address->getCity()) {
    $addressNode->appendChild($xml->createElement('PoliticalDivision1', $this->address->getCity()));
}
```

The use of PoliticalDivision2 for state/province and PoliticalDivision1 for city, are actually mismatched.

As per the [UPS Address Validation Street Level XML Developers Guide](https://github.com/gabrielbull/php-ups-api/files/138384/Address.Validation.Street.Level.XML.Developers.Guide.pdf), PoliticalDivision2 is for City or town name, and PoliticalDivision1 is for State or Province/Territory name.

**Comment by stefandoorn** [comment]
Thanks. Would you be able to submit a PR to fix this?

**Comment by beaudierman** [comment]
@stefandoorn Sure thing, #86

**Comment by stefandoorn** [comment]
Merged, thanks!
