### ISSUE TITLE
Failure: Multiple shipper numbers found with trackByReference

### ISSUE THREAD

**Issue by hm122** [gabrielbull/php-ups-api#87]
Hi!

To track shipments I am using track() (which works fine) and trackByReference(). With trackByReference I am getting "Failure: Multiple shipper numbers found (151085)."

Do you know what might cause this error and how I can solve this issue?

Thanks!

**Comment by hm122** [comment]
This pull request solves the issue:
https://github.com/gabrielbull/php-ups-api/pull/88

**Comment by stefandoorn** [comment]
Will be fixed when we accept the PR indeed.
