### ISSUE TITLE
Shipping class refactoring is not finished 

### ISSUE THREAD

**Issue by vandalizmo** [gabrielbull/php-ups-api#9]
Hey,

it seems that You are using old public properties during confirmRequest creation, but using getters and setters when preparing Shipping class does not populate them. ConfirmRequest ends up almost empty and of course that request is not accepted by UPS.

Also, PaymentInformation entity is missing both as class and in Shippment class.

**Comment by stefandoorn** [comment]
I will close this issue for now. If there are updates, feel free to submit a PR. Would be very welcome.
