### ISSUE TITLE
Getting rate information from Tracking object

### ISSUE THREAD

**Issue by pignataa** [gabrielbull/php-ups-api#95]
I am using this function in order to get my tracking object $tracking->track($order->provider->providers_tracking);

When using this I need to get the Rate of the package that I looked up. Is there a way to get this information?

Here is the package information - Replaced information with %%

object(stdClass)[1154]
  public 'Shipper' => 
    object(stdClass)[1155]
      public 'ShipperNumber' => string '%%' (length=6)
      public 'Address' => 
        object(stdClass)[1156]
          public 'AddressLine1' => string '%%' (length=15)
          public 'City' => string '%%' (length=6)
          public 'StateProvinceCode' => string '%%' (length=2)
          public 'PostalCode' => string '%%' (length=12)
          public 'CountryCode' => string 'US' (length=2)
  public 'ShipTo' => 
    object(stdClass)[1157]
      public 'Address' => 
        object(stdClass)[1158]
          public 'City' => string '%%' (length=16)
          public 'StateProvinceCode' => string '%%' (length=2)
          public 'PostalCode' => string '%%' (length=5)
          public 'CountryCode' => string 'US' (length=2)
  public 'ShipmentWeight' => 
    object(stdClass)[1159]
      public 'UnitOfMeasurement' => 
        object(stdClass)[1160]
          public 'Code' => string '%%' (length=3)
      public 'Weight' => string '%%' (length=4)
  public 'Service' => 
    object(stdClass)[1161]
      public 'Code' => string '%%' (length=3)
      public 'Description' => string '%%' (length=6)
  public 'ReferenceNumber' => 
    array (size=2)
      0 => 
        object(stdClass)[1162]
          public 'Code' => string '%%' (length=2)
          public 'Value' => string '%%' (length=5)
      1 => 
        object(stdClass)[1163]
          public 'Code' => string '%%' (length=2)
          public 'Value' => string '%%' (length=5)
  public 'ShipmentIdentificationNumber' => string '%%' (length=18)
  public 'PickupDate' => string '%%' (length=8)
  public 'DeliveryDateUnavailable' => 
    object(stdClass)[1164]
      public 'Type' => string 'Scheduled Delivery' (length=18)
      public 'Description' => string 'Scheduled Delivery Date is not currently available, please try back later' (length=73)
  public 'Package' => 
    object(stdClass)[1165]
      public 'TrackingNumber' => string '%%' (length=18)
      public 'Activity' => 
        array (size=6)
          0 => 
            object(stdClass)[1166]
              ...
          1 => 
            object(stdClass)[1172]
              ...
          2 => 
            object(stdClass)[1178]
              ...
          3 => 
            object(stdClass)[1184]
              ...
          4 => 
            object(stdClass)[1190]
              ...
          5 => 
            object(stdClass)[1196]
              ...
      public 'PackageWeight' => 
        object(stdClass)[1202]
          public 'UnitOfMeasurement' => 
            object(stdClass)[1203]
              ...
          public 'Weight' => string '3.00' (length=4)
      public 'ReferenceNumber' => 
        array (size=2)
          0 => 
            object(stdClass)[1204]
              ...
          1 => 
            object(stdClass)[1205]
              ...

**Comment by stefandoorn** [comment]
The Tracking API doesn't return any Rating information. It's also described in the UPS documentation what is returned in total, but as far as I know no rates are included.
