### ISSUE TITLE
Multiple rates with 1 call to API

### ISSUE THREAD

**Issue by Anthon95** [gabrielbull/php-ups-api#96]
Hello,

I wanted to know if it were possible to fetch multiple rates for various services using your API but with only one call to UPS.

I found the method to change the selected shipping service, and the default is "Ground", but can't find the method for multiple services.

Maybe I am missing something big or simple, but any help or example would be greatly appreciated.

Thank You.

**Comment by stefandoorn** [comment]
Sure, if you use this example it will be possible: https://github.com/gabrielbull/php-ups-api#rate-class-example. I normally get atleast 2 rates back, depending on location you are shipping to ofcourse. It takes one call and multiple options are returned at once.

**Comment by Anthon95** [comment]
Thank you for the response.

However I always only get 1 rate returned when using the example, even though I am able to return different rates when hard setting the service (using the Service class). Is this because the default service (set in the class) is equal to S_GROUND ?

Regards

**Comment by stefandoorn** [comment]
You have to define a service indeed, I'm setting it to ground myself. Why that is was also unclear for me, but it's the way UPS apparently works.

**Comment by gh-darvishani** [comment]
hi
I went to get rates for about 20 goods. it is possible to use your API. also, how I can pass multi-package to ups API?
