### ISSUE TITLE
Display ErrorLocation

### ISSUE THREAD

**Issue by valentinaungurean** [gabrielbull/php-ups-api#98]
Can you please add ErrorLocation field, to the message of InvalidResponseException, that is thrown in /src/Request.php on line 131? It will help a lot, as ErrorCode and ErrorDescription is not enough to understand where is the problem.

**Comment by stefandoorn** [comment]
Could be, but what is the content of that field? I don't have an example in here. Besides, we are open to PR's, so if you would want to add it yourself, please do so :)

**Comment by valentinaungurean** [comment]
It can be changed this way:
`
$error = 'Failure: ' . $xml->Response->Error->ErrorDescription . ' (' . $xml->Response->Error->ErrorCode . ').';
if ($xml->Response->Error->ErrorLocation->ErrorLocationElementName) {
    $error .= ' ErrorLocation: '.$xml->Response->Error->ErrorLocation->ErrorLocationElementName;
}

throw new InvalidResponseException($error);
`
instead of line 131 form file /src/Request.php

**Comment by stefandoorn** [comment]
But what is the content of that field? I would like to know what kind of information we gain of it to see if it's worth adding. Also, please create a Pull Request with the required adjustment if you could.

**Comment by scottcwilson** [comment]
Please add a PR if this functionality is still desired.
