### ISSUE TITLE
Error License 250003

### ISSUE THREAD

**Issue by sblondeau** [gabrielbull/php-ups-api#99]
Hello

I try to validate address (with AddressValidation class) but I get error message : 
Failure: Invalid Access License number (250003).

However, it works well with the Tracking class...
Furthermore, on UPS website, it seems that the API is valid for Adress validation.

Do you have any idea ?

**Comment by stefandoorn** [comment]
Are you having an EU account by accident? I'm running in the same problem that I can't use it due to having an EU account. I'm still trying to fix that with UPS, else you can only use the other Address Validation API (which we don't have implemented yet.. but feel free to create a PR).
